### ISSUE TITLE
Splunk app stuck when no API is connected

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-splunk#1002]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.0.4   | 8.1.1 | 67 |

**Description**
Hello team,

We have detected that the Splunk Wazuh app keeps stuck when the API isn't connected, we cannot do anything inside the rest of the menus. Besides, we couldn't return to the configuration screen without reloading the entire page.

**Steps to reproduce**

1. Deploy Splunk stack and install the Splunk Wazuh App without connecting with the Wazuh API.
2. Click on Wazuh app section.
3. Click on Agents preview.
4. See error.

**Screenshots**

https://user-images.githubusercontent.com/10661307/111752434-feb96680-8895-11eb-9c42-dba9208a2063.mp4

**Comment by Desvelao** [comment]
### Changes
- Fixed loading status when some state transition fails
- Fixed the selected tab in settings when fails some state transition.

PR: https://github.com/wazuh/wazuh-splunk/pull/1045
