### ISSUE TITLE
Missing dashboard for AWS wodle

### ISSUE THREAD

**Issue by pacoqack** [wazuh/wazuh-splunk#1003]
![image](https://user-images.githubusercontent.com/15269938/111754020-cdda3100-8897-11eb-9b4e-f759ad47737a.png)

This dashboard for Amazon AWS events is one of the mentioned in the [Wazuh demo use cases](https://github.com/wazuh/wazuh-automation/wiki/Wazuh-demo:-Execution-guide#aws-wodle) and it is not available yet at the Splunk app.

Maybe it should.

**Comment by frankeros** [comment]
The dashboard already exists
![image](https://user-images.githubusercontent.com/26828184/111797222-ba36c680-88a7-11eb-8b53-6f748f010452.png)
