### ISSUE TITLE
Interesting fields not working as would be expected

### ISSUE THREAD

**Issue by spothound** [wazuh/wazuh-splunk#1006]
On the Splunk app there are few interesting fields and they are the same for all hosts.

This is useless right now and there is an important lack of fields that would be required to extract and show, maybe using the splunk `spath` method. https://docs.splunk.com/Documentation/Splunk/6.3.3/SearchReference/spath 

![image](https://user-images.githubusercontent.com/15269938/111764102-2662fb80-88a3-11eb-9409-67a42272f9be.png)

It would be required to add interesting rule fields such as agent.id, rule.level, full_log, etc...

**Comment by pacoqack** [comment]
It seems that this happens only with the fast field discover mode, with the smart one the behaviour changes

![image](https://user-images.githubusercontent.com/15269938/111765121-4941df80-88a4-11eb-80b3-26325f629c82.png)
![image](https://user-images.githubusercontent.com/15269938/111765182-5f4fa000-88a4-11eb-8eec-8da818933bd3.png)


Maybe it should be the default behaviour?

**Comment by mpRegalado** [comment]
It seems that now, by default, Smart Mode is already the selected option.
Creating a new environment with the v4.2.0-rc4 manager and the splunk app from the 4.2-8.1 branch and navigating to the Discover section showed me the Smart Mode already selected.

However, it seems like the configuration of this panel is stored by Splunk server side on a per-user basis, so changing the mode persists across multiple browsers even after clearing cookies/using incognito.

![image](https://user-images.githubusercontent.com/80431234/118626428-2a3fcb00-b7cb-11eb-87b2-58256cf59509.png)
Screenshot after launching the Splunk Enviroment for the first time
