### ISSUE TITLE
Splunk App cannot authenticate correctly

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-splunk#1008]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.0.4   | 8.1.1     | 67 |

**Description**
Hello team,

We discovered that after register the API The Splunk App cannot access to API by some unknown error.
After a five minutes all start working well.

**Steps to reproduce**

1. Go to settings menu inside Wazuh app for Splunk.
2. Register a new API with good credentials.
3. Go to agents and register a new agent.
4. go to overview or another tab.
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/10661307/111774967-71cfd680-88b0-11eb-9d01-05facdc05f0f.png)

**Comment by eze9252** [comment]
Hi @okynos , I couldn't reproduce this bug ... I followed the steps that you mentioned and works OK for me. Could you test with the last package?
