### ISSUE TITLE
Management - status view -> changing cluster node breaks the daemon view

### ISSUE THREAD

**Issue by pacoqack** [wazuh/wazuh-splunk#1009]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.0.4   | 8.1.1     | 67 |

**Description**
If you select another cluster worker on the status (management) view the daemon status graph stop showing the correct information.

This should be fixed. 

**Steps to reproduce**

1. Go to Management > status view
2. Select a different worker

**Screenshots**
![image](https://user-images.githubusercontent.com/10661307/111774967-71cfd680-88b0-11eb-9d01-05facdc05f0f.png)
![image](https://user-images.githubusercontent.com/15269938/111776433-4cdc6300-88b2-11eb-9b89-811e07f093b3.png)
![image](https://user-images.githubusercontent.com/15269938/111777631-d6d8fb80-88b3-11eb-8dc8-56929fad7b5c.png)

going back to the master node also fails:

![image](https://user-images.githubusercontent.com/15269938/111777872-29b2b300-88b4-11eb-92e8-634d32972c5f.png)

**Comment by pacoqack** [comment]
It also happens on other views. After selecting worker 1 and then master again:

![image](https://user-images.githubusercontent.com/15269938/111779627-a6df2780-88b6-11eb-89f5-b7ce8bd25942.png)
![image](https://user-images.githubusercontent.com/15269938/111779703-bc545180-88b6-11eb-8a12-03e07563d246.png)

**Comment by pacoqack** [comment]
Hello guys, I've built a new package with the changes in the merged PR but the fail persist. Could we please review this?

**Comment by eze9252** [comment]
Hi Paco, I tested this whit the new package and works. Could you review again?
