### ISSUE TITLE
Cannot seach by incomplete name

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-splunk#1012]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.0.4   | 8.1.1     | 68 |

**Description**
Hi!
The agent's preview search box only finds agents by exact name. It doesn't search coincidences.
If I want to search all agents with a prefix name I couldn't do it.

**Steps to reproduce**

1. Go to agents preview
2. Click on search box
3. Set name tag and put partial name

**Screenshots**
![image](https://user-images.githubusercontent.com/10661307/111787679-86679b00-88bf-11eb-95d3-5588c33f038a.png)
![image](https://user-images.githubusercontent.com/10661307/111787862-c0d13800-88bf-11eb-9dc2-04676c1a6817.png)

**Comment by frankeros** [comment]
Check #857
