### ISSUE TITLE
Unknown version in search box doesn't work

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-splunk#1013]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.0.4  | 8.1.1     | 68 |

**Description**
Never connected agents have unknown version but I cannot search by this field.

**Steps to reproduce**

1. Go to agents preview
2. Click on search box
3. Select version tag.
4. Set it to unknown (only available if never connected agents are present).
4. See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/10661307/111788222-1efe1b00-88c0-11eb-9bc9-a5785a308887.png)

**Comment by frankeros** [comment]
related issue #1012
