### ISSUE TITLE
Glitch on action buttons (agents preview)

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-splunk#1014]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.0.4   | 8.1.1     | 68 |

**Description**
We saw that sometimes the dialog and the row starts to blink without limit.

**Steps to reproduce**

1. Go to agents preview
2. Move the mouse around action buttons
3. See error

**Screenshots**

https://user-images.githubusercontent.com/10661307/111790708-c714e380-88c2-11eb-9765-c5da83324cef.mp4

**Comment by gabiwassan** [comment]
Hi @okynos this bug was fixed on this [PR](https://github.com/wazuh/wazuh-splunk/pull/994)

Regards!
