### ISSUE TITLE
When trying to print in Discover, canceling lowers to the end and re-uploads

### ISSUE THREAD

**Issue by CPAlejandro** [wazuh/wazuh-splunk#1039]
https://user-images.githubusercontent.com/46006326/112990208-1500d580-9166-11eb-8e3b-08c6ea0fde74.mp4

**Comment by Desvelao** [comment]
I reviewed the reported issue and it is happening in the Splunk Search too, so it is not related to the Wazuh app.

Tested with:
- Wazuh app `4.2.0-8.1.1` (development)

I will close the issue.
