### ISSUE TITLE
Success message with error toast

### ISSUE THREAD

**Issue by sortizowlh** [wazuh/wazuh-splunk#1041]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.1.4-1   | 8.0.8     | 68|

**Description**
Error toast when with success message

**Steps to reproduce**

1. Go to management/groups
2. Edit agent.conf file
3. Save the new content
4. See the error

**Screenshots**
![imagen.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/a49f18b7-071a-4ac3-819a-3eaa9a50e382)

**Comment by eze9252** [comment]
I tested and it works
