### ISSUE TITLE
Uncontrolled error message when Wazuh API credentials are incorrect

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-splunk#1044]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.1.4   | 8.1.2     | 68 |

**Description**
When incorrect Wazuh API credentials are entered in the Splunk app API form, the error: `local variable 'e' referenced before assignment`. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3830293/113170330-c119ed80-9246-11eb-92fa-736614355f46.png)

**Comment by frankeros** [comment]
Fixed in #1045
