### ISSUE TITLE
Invalid template with disconnected agent

### ISSUE THREAD

**Issue by sortizowlh** [wazuh/wazuh-splunk#1067]
**Description**
Add more than one agent with the same hostname may cause connection errors. 
In some cases, the agent is shown as connected on agents list, but selecting this agent to show their data causes invalid API connection and shows a bad template.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5f2980436c83d247c928e37e/3b0a86f6-3bb4-4fc6-8ea4-d28eb5e03fe0)

**Comment by mpRegalado** [comment]
**Steps I took to replicate the issue**
I attempted to replicate the issue by creating 10 agents with the same hostname connecting and disconnecting every minute.
After a few cycles, the wazuh manager fails to give information about that agent while continuing to respond to requests about others.
The front end only displays a toast about an error, never loading a bad template.

**Screenshots**
![image](https://user-images.githubusercontent.com/80431234/118131052-52f84700-b3fe-11eb-90ab-6711e9cc7ae1.png)
![image](https://user-images.githubusercontent.com/80431234/118131132-69060780-b3fe-11eb-93b7-1dccd87dd5f2.png)
