### ISSUE TITLE
Add cache control for the Splunk app

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1072]
**Describe the solution you'd like**
Improve some strategies for cache control.

- [x] Add meta for cache-control in the head section of the page.
- [x] Verify the app version for backend vs browser version (then force update bundles).
- [x] Avoid infinite loop for the previous step. Then show a message to clear the cache manually.

**Comment by Machi3mfl** [comment]
<img width="1440" alt="Screen Shot 2021-04-28 at 17 57 40" src="https://user-images.githubusercontent.com/6089438/116548483-a7fa7000-a8ca-11eb-939c-6aab07f24907.png">

**Comment by frankeros** [comment]
![Uploading image.png…]()
