### ISSUE TITLE
MITRE integration - Framework

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1073]
Hi team,

We need to show all the MITRE ids in a table and show their details.

Core issue wazuh/wazuh#3709
Related to #884

Features under development:

- [x] Modal filter
- [x] Add Navigation to Mitre pages
- [x] Code refactor
- [x] Change some CSS features
- [x] Change some icons
- [x] Implement the possibility to search using multiple words
- [x] Add spinner when data is loading
- [x] Fix pinned filter for Mitre tabs

**Comment by sortizowlh** [comment]
Adding table with details subtable.
Under development

**Comment by sortizowlh** [comment]
Empty table component. Trying to add some data.

![imagen](https://user-images.githubusercontent.com/47242022/116905325-1b8bdc80-ac3f-11eb-930d-af7d7fe34766.png)

**Comment by sortizowlh** [comment]
Loading Mitre information

![imagen](https://user-images.githubusercontent.com/47242022/117180524-8f132280-add4-11eb-9230-995bc0705805.png)

**Comment by sortizowlh** [comment]
Display modal with testing data. Under development...

![imagen](https://user-images.githubusercontent.com/47242022/117697327-a41bf700-b1c2-11eb-8882-346a0d48a42b.png)

**Comment by sortizowlh** [comment]
Numer ob tactics and techniques -->By @asteriscos 

![imagen](https://user-images.githubusercontent.com/47242022/117854864-30452180-b28a-11eb-9668-3e3725332a69.png)

Technique information into modal.

![imagen](https://user-images.githubusercontent.com/47242022/117854961-4bb02c80-b28a-11eb-9418-ff9b71d0375c.png)

**Comment by sortizowlh** [comment]
![imagen](https://user-images.githubusercontent.com/47242022/118018724-71a40280-b358-11eb-919d-8763a628c507.png)

**Comment by sortizowlh** [comment]
New Technique table format by @asteriscos 
Now, the table can be sorted and have pagination

![imagen](https://user-images.githubusercontent.com/47242022/118286952-47c31b00-b4d3-11eb-98f5-3d335a5c2746.png)
