### ISSUE TITLE
Unable to create a Wazuh API user from Dev Tools

### ISSUE THREAD

**Issue by c3sar0n** [wazuh/wazuh-splunk#1081]
| Wazuh | Splunk | Rev |
| ------- | ------- | ----- |
| 4.1.5    | 8.1.2    | 444 |

### Description
Unable to create a Wazuh manager API's user from **Wazuh App for Splunk** -> **>_Dev Tools**

### Steps to reproduce

1. Go to `Wazuh for Splunk`
2. Click on `>_Dev Tools`
3. Try to send a `POST` request to the manager endpoint API `/security/users/` as follows:
```
POST /security/users/
{ "username": "cesar_test", 
 "password": "Pa$$word123", 
 "allow_run_as": true 
}
```
4. See **error 400 - Bad Request**:
> {
>   "error": "{'title': 'Bad Request', 'detail': \"'username=cesar_test&password=Pa%24%24word123&allow_run_as=true' is not of type 'object'\"}"
> }
5. If you execute a `GET` command in the same window to this endpoint, it works as expected and shows the users.
6. If the same `POST` is executed with `cURL` from the same server to create the API user, it works as expected:
`curl -k -X POST "https://192.168.58.136:55000/security/users" -H  "Authorization: Bearer $TOKEN"  -H  "Content-Type: application/json" -d "{\"username\":\"cesar-remote-test2\",\"password\":\"Test.1234\"}"`
> {"data": {"affected_items": [{"id": 101, "username": "cesar-remote-test2", "allow_run_as": false, "roles": []}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "User was successfully created", "error": 0}[

### Screenshots
**Error Screenshot:**
![image](https://user-images.githubusercontent.com/73619442/117377824-87be4880-aeaa-11eb-8e4f-6f486ab325ee.png)

**Executed GET command screenshot:**
![image](https://user-images.githubusercontent.com/73619442/117377879-a58bad80-aeaa-11eb-9f27-20bafcf3fd49.png)

### Additional context
The Wazuh manager was updated from 3.x to 4.1. The same POST execution worked previously.
It seems that the Wazuh app for Splunk is sending a wrong formatted request to the API that couldn't be interpreted as an object. 
**Please find some debug logs during the API call from Dev Tools:**
> 2021/05/03 19:58:56 INFO: wazuh 192.168.58.129 "GET /manager/status" with parameters {} and body {} done in 0.059s: 200
> 2021/05/03 19:58:56 DEBUG2: Receiving headers {'Host': '192.168.58.136:55000', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjIwMDg2MTkxLCJleHAiOjE2MjAwODcwOTEsInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.gYVHAdD-NP6DoT83uJnJn-k5N6ICfnZIAgsCVb2872M', 'Content-Length': '62', 'Content-Type': 'application/x-www-form-urlencoded'}
> 2021/05/03 19:58:56 DEBUG: Getting data and status code
> 2021/05/03 19:58:56 DEBUG: Decoded token {'username': 'wazuh', 'roles': [1], 'token_nbf_time': 1620086191, 'run_as': False}
> 2021/05/03 19:58:56 DEBUG2: Starting to execute request locally
> 2021/05/03 19:58:56 DEBUG2: Finished executing request locally
> 2021/05/03 19:58:56 DEBUG2: Time calculating request result: 0.048s
> 2021/05/03 19:58:56 DEBUG2: Receiving parameters {}
> 2021/05/03 19:58:56 DEBUG2: Starting to execute request locally
> 2021/05/03 19:58:56 DEBUG2: Finished executing request locally
> 2021/05/03 19:58:56 DEBUG2: Time calculating request result: 0.002s
> 2021/05/03 19:58:56 INFO: wazuh 192.168.58.129 "POST /security/users/" with parameters {} and body {} done in 0.053s: **400**

**Some more debug logs during the API call from cURL:**
> 2021/05/03 20:03:27 DEBUG2: Receiving parameters {'username': 'cesar-remote-test3', 'password': '*'}
> 2021/05/03 20:03:27 DEBUG2: Starting to execute request locally
> 2021/05/03 20:03:27 DEBUG2: Finished executing request locally
> 2021/05/03 20:03:27 DEBUG2: Time calculating request result: 0.134s
> 2021/05/03 20:03:27 INFO: wazuh 192.168.58.129 "POST /security/users" with parameters {} and body {"username": "cesar-remote-test3", "password": "*"} done in 0.190s: **200**

Thanks and best regards,
Cesar Moreno.

**Comment by AlexRuiz7** [comment]
Solved in #1296 

![image](https://user-images.githubusercontent.com/15186973/171845290-a8ee56b9-6364-418e-a1d6-86201d6611e1.png)
