### ISSUE TITLE
Testing Wazuh 4.2.0 revision 4202 compatibility 8.1.3

### ISSUE THREAD

**Issue by Machi3mfl** [wazuh/wazuh-splunk#1082]
We need to perform testing of the changes introduced in the code revision 4202 in production mode.
Also, we need to perform a regression test with these changes over our general checks.

General checks:

- [x]  Firefox - Splunk 8.1.2
- [x]  Chrome - Splunk 8.1.2
- [x]  Safari - Splunk 8.1.2

**Comment by frankeros** [comment]
The compatibility was successfully passed for Splunk 8.1.3, but using Forwarder for 8.1.1
