### ISSUE TITLE
API connection error from Splunk Cloud instance

### ISSUE THREAD

**Issue by rosslyn-alexadamovici** [wazuh/wazuh-splunk#1085]
Using Wazuh App for Splunk 3.13.1. API configured to listen on port 55000 using the public IP of the server.
I can reach the API from my machine. But when putting in the configuration in Wazuh App for Splunk on my Splunk Cloud instance I get Unreachable API. Any help would be appreciated.

Wazuh App for Splunk v3.13.1
Splunk Cloud Version: v8.2.2104.1
Wazuh v4.1.5

**Comment by frankeros** [comment]
Hi @rosslyn-alexadamovici, 
first of all, if you are using Wazuh v4.1.5 you should use the compatible Wazuh app for Splunk, you can find it [here](https://packages.wazuh.com/4.x/ui/splunk/wazuh_splunk-4.1.5_8.1.2-1.tar.gz).
On the other hand, the issue sounds like the Splunk Cloud instance is refusing the connection with the API. 
Are you getting some related logs in the App? 
![image](https://user-images.githubusercontent.com/26828184/121590771-19bbf280-ca0f-11eb-9b29-92f43352d886.png)

You could get the complete logs from the indicated file.

**Comment by rosslyn-alexadamovici** [comment]
Hello,

               I discussed with Splunk and they opened the appropriate port. Now I am getting the following error:
***@***.***D761FF.B61BA9E0]

               Unfortunately the app needs to be installed via Splunk, as we have the cloud version of Splunk and cannot upload the apps.

Regards,

Alexandru Adamovici
Support Infrastructure Manager

**Comment by frankeros** [comment]
Hi @rosslyn-alexadamovici 
We just published the release 4.1.5 of Wazuh in the Splunk base repository
you can find it [here](https://splunkbase.splunk.com/app/3688/)
Can you try this version, please?

**Comment by frankeros** [comment]
Hi @rosslyn-alexadamovici we published a few days ago the last release of the Wazuh app for Splunk in SplunkBase, you can check it [here](https://splunkbase.splunk.com/app/3688/)
The app is not yet available for Splunk Cloud, "a Splunk Cloud customer needs to request it before it happens", Splunk support says.
Are you able to request it?

**Comment by frankeros** [comment]
Due to inactivity, I'm closing this issue. Feel free to reopen it. If you have any questions, you can also use our [slack channel](https://wazuh.com/community/join-us-on-slack/) or subscribe to our [mailing list](https://groups.google.com/forum/#!forum/wazuh).

**Comment by rosslyn-alexadamovici** [comment]
I am sorry for the late reply.

I did request it, and this is the answer I got from them:
Hello Alexandru-Emilian, 


Thank you for your recent Splunk Cloud App request. Our Splunk Cloud operations and security teams have determined that the #3688 4.1.5 - SplunkAppForWazuh is not compatible and/or secure within the Splunk Cloud service architecture. Please see their comments below:
[The application can be configured for unencrypted communication, which is not permitted in Splunk Cloud. All communication must be encrypted (HTTPS preferred).]
•	Only files under the bin, lib, appserver/controllers directories may have executable permissions. File: appserver/static/js/libs/codemirror-conv/javascript.js
•	tmpUrl (endpoint) is not verified to have a 'https' schema. Only URLs with a 'https' schema may be requested from a Splunk cloud environment. File: appserver/static/js/services/requestService/requestService.js Line Number: 47,50,53,56
•	The default/inputs.conf specifies splunktcp, which is prohibited in Splunk Cloud. An alternative is to use splunktcp-ssl. Stanza: [splunktcp://9997]. File: default/inputs.conf Line Number: 1

If you wish to make changes to the app, you can find documentation and utilities to assist you here: http://dev.splunk.com/view/appinspect/SP-CAAAE9U

Please let us know if you wish to resubmit app once issues are resolved or if we can close this case

Regards,
Sukhjitkaur
Splunk > Customer Support
