### ISSUE TITLE
[Help Needed] Empty Wazuh Index, no logs of security events or Vulnerabilities.

### ISSUE THREAD

**Issue by kiraitachi** [wazuh/wazuh-splunk#1087]
| Wazuh           | Splunk | 
|--------------| ------- | 
| 4.1.3 Build 2  | 8.1.2     | 

**Description**
I have installed 2 agents that are reporting correctly and are shown in the Agent Management. I can see the inventory and all the data regarding the agent, but dashboards are empty. No vulnerability or Log events are shown on the agents.

I have tried checking all possible steps and nothing is being shown. Index wazuh is empty only wazuh-monitoring index is showing some relevant data regarding the Agent status.

**Steps to reproduce**

1.Installed Wazuh Splunk App.
2.Installed Wazuh Server Manager.
3.Configured API from Splunk App to Wazuh Server Manager.
4.Configured the Index for Wazuh and Inputs.conf as per documentation.
5.Deployed 2 agents.
6.Agents are displayed data but all dashboards are empty and no logs are being sent.

**Comment by Machi3mfl** [comment]
Hi @kiraitachi. Thanks for contact us. 
In order to help you. I need some additional information about your environment.
In some cases, the dashboards can be empty because the Splunk forwarder is doesn't installed correctly. First, we need to check out if your Splunk forwarder is installed correctly. And if you don't have it installed, you must download the forwarder from the Splunk official website. 
Splunk download section: https://www.splunk.com/en_us/download/universal-forwarder.html
Also, check your logs in Splunk settings section.
I leave you a guide from our website: https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/splunk/splunk-basic.html#splunk-basic
Please, add screenshots from logs and the empty dashboards. 
Thank you

**Comment by frankeros** [comment]
Hi @kiraitachi 
were you able to solve your problem? If don't, kindly send the information requested above.
Best

**Comment by kiraitachi** [comment]
> Hi @kiraitachi. Thanks for contact us.
> In order to help you. I need some additional information about your environment.
> In some cases, the dashboards can be empty because the Splunk forwarder is doesn't installed correctly. First, we need to check out if your Splunk forwarder is installed correctly. And if you don't have it installed, you must download the forwarder from the Splunk official website.
> **Splunk download section:** https://www.splunk.com/en_us/download/universal-forwarder.html
> **Installation guide:** https://docs.splunk.com/Documentation/Forwarder/8.2.1/Forwarder/Configuretheuniversalforwarder
> Also, check your logs in the Splunk settings section.
> I leave you a guide from our website: https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/splunk/splunk-basic.html#splunk-basic
> Please, add screenshots from logs and the empty dashboards.
> Thank you

Hi.

Sorry for the delay, my kid was just born a couple weeks ago and its been busy...

I read the documentation and unless I missed it, it was not clearly stated or mentioned that it needed the universal forwarder from Splunk in order to send those logs. If that's the case then, I have already installed it and I would suggest maybe updating those docs since they are a bit unclear regarding Splunk.

In any case, I'm still wondering if there are any aditional configuration steps for the forwarder that I need to deploy in order to define what logs and index it needs. I believed that the wazuh agent was sending those logs to be honest...

Thanks again for your time and clarification.

**Comment by Machi3mfl** [comment]
Hi @kiraitachi. No problem, thanks for your reply.
We gonna try to help you with your issue. 
The Splunk forwarder must be installed together with the Wazuh manager. The forwarder collects data from a data source (in this case, the Wazuh manager) and sends it to the Splunk Indexer.
I leave you an official Splunk documentation link, this article explains how it works Splunk forwarder. https://docs.splunk.com/Documentation/Forwarder/8.2.1/Forwarder/Abouttheuniversalforwarder
I understand when you think that it's not necessary to install the forwarder if the manager and indexer are in the same host but I tried to do that and is impossible. Splunk indexer cannot collect the data of the Wazuh manager without the forwarder.
I recommend this solution but if you find another, please add the resources in this thread and we can try to apply it.
Thanks again and Congrats.

**Comment by Machi3mfl** [comment]
Hi @kiraitachi, were you able to solve your issue? 
Best regards

**Comment by kiraitachi** [comment]
Good afternoon.

After installing the forwarder in the same host as the Wazuh Manager and Splunk ES, should I deploy any configuration to the forwarder? Or default config should be enough?

Cheers!

**Comment by Machi3mfl** [comment]
Hi @kiraitachi. Thanks for your reply and sorry for the late.
Yes, I leave you a article that explain how install and configure splunk forwarder: [Install and configure splunk forwarder](https://documentation.wazuh.com/current/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html#install-and-configure-splunk-forwarder).
Please, tell me how it was.
Best regards

**Comment by frankeros** [comment]
Hi @kiraitachi, were you able to solve your problem?

**Comment by kiraitachi** [comment]
Good night.

Sorry but I finally gave up on the issue. Lack of time....

Closing the issue, thanks for your support and time.
