### ISSUE TITLE
Testing compatibility Splunk 8.1.4

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1089]
Hi team, we need to perform a regression test to determine the compatibility of our app with Splunk 8.1.4.

Wazuh target version: `4.2.0 r4202` (branch `4.2-8.1`)

General checks:

- [x]  Firefox - Splunk 8.1.4
- [x]  Chrome - Splunk 8.1.4
- [x]  Safari - Splunk 8.1.4

**Comment by asteriscos** [comment]
The following issues were found, but they're not specific to Splunk `8.1.4`, as they also happened in `8.1.1`

[Unformatted dates and long agent name overflow in agents configuration report](https://github.com/wazuh/wazuh-splunk/issues/1091)
[Long agent's name overflows in agent overview](https://github.com/wazuh/wazuh-splunk/issues/1090)
[Cannot save rules o decoders file](https://github.com/wazuh/wazuh-splunk/issues/1095) 
[Group PDF report is a blank page](https://github.com/wazuh/wazuh-splunk/issues/1093)
[New created indexes are not listed in the index selector](https://github.com/wazuh/wazuh-splunk/issues/1094) 
[Group agent management table does not update on error](https://github.com/wazuh/wazuh-splunk/issues/1092) 
[Agent table keeps refreshing when window changes size](https://github.com/wazuh/wazuh-splunk/issues/1096)
