### ISSUE TITLE
Long agent's name overflows in agent overview

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-splunk#1090]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.2   | 8.1.4     | 444 |

**Description**
When an agent's name is very long it overflows on the agent overview's name

**Steps to reproduce**

1. Go to Agents
2. Click on an agent in the agents table
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/9343732/122543887-a152c400-d002-11eb-8a64-c488df0ae882.png)

**Comment by yenienserrano** [comment]
**Description**

The container of the agent name is adapted for the length.

![image.png](https://images.zenhubusercontent.com/61360f7fdb792dac2bd3f3a6/5b939a67-e8e1-4e32-a09c-e96ac55cfa2f)

![image.png](https://images.zenhubusercontent.com/61360f7fdb792dac2bd3f3a6/1fdc05d6-5d11-40e5-9f88-8d304a965b46)
