### ISSUE TITLE
Cannot save rules or decoders file

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-splunk#1095]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.2   | 8.1.4     | 444 |

**Description**
Issues when saving rules or decoders file:

- 404 error when editing rules file
- Never-ending loader when editing decoders file

**Steps to reproduce**

1. Go to Management -> Ruleset
2. Click on Custom rules switch
3. Select the first one
4. Click on the XML filename
5. Try to save the file and see the error

**Screenshots**
![edit_rules](https://user-images.githubusercontent.com/9343732/122551341-38bc1500-d00b-11eb-83ff-313017e6b4dc.gif)

![edit_decoders](https://user-images.githubusercontent.com/9343732/122552767-1a571900-d00d-11eb-85dd-046c15537308.gif)

**Additional context**
**This feature works fine when using the "**Manage rules/decoders files**" view**

**Comment by yenienserrano** [comment]
**Description**

Rules and decoders can be saved.

![image.png](https://images.zenhubusercontent.com/61360f7fdb792dac2bd3f3a6/afa192e4-150e-45b0-87b0-b665ab0a00f7)
![image.png](https://images.zenhubusercontent.com/61360f7fdb792dac2bd3f3a6/abb325c0-b569-4197-a135-40c52db2eeae)
