### ISSUE TITLE
Agent table keeps refreshing when window changes size

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-splunk#1096]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.2.0   | 8.1.x     | 4202 |

**Description**
In the agents overview window, whenever you resize the width or height of the window, the agent table refreshes, showing an animation and sending a new `/api/request` with an `/agents` request
This can happen multiple times per second while the window is being resized.

**Steps to reproduce**

1. Go to 'Agents'
2. Open the network log
3. Resize the window
4. Observe how the agent list keeps entering a loading state and how the network registers multiple requests.

**Screenshots**
![agentsReload.gif](https://images.zenhubusercontent.com/609a3b93e47a8d8edbaeef34/8f59d2d0-ac6b-4573-aea1-cce7d2f6ab68)

**Comment by yenienserrano** [comment]
**Description**

When the height of the page is changed, it waits 1 second to make the request with the desired height.

![image.png](https://images.zenhubusercontent.com/61360f7fdb792dac2bd3f3a6/2bc0faa7-df70-4f6c-9f68-b15df9645656)

![image.png](https://images.zenhubusercontent.com/61360f7fdb792dac2bd3f3a6/4c51c21b-9052-4885-a7e0-e8a1ed0ae65f)
