### ISSUE TITLE
Node status shows agent info that do not belong to the node

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-splunk#1097]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.2   | 8.1.x     | 4204 |

**Description**
Changing the node in a wazuh cluster on the management status switches information about the cluster, but not about the agents.
We should check whether this is the intended behavior.

**Steps to reproduce**

1. Go to 'Management - > Status -> Cluster'
2. Switch the node
3. See result

**Comment by AlexRuiz7** [comment]
Not a bug.

A cluster is conformed by a master node, optionally several workers nodes, and the agents.

The dropdown allows the user to see the information of the nodes conforming the cluster. The agents connected to the cluster are the same no matter the node queried.

This is applicable to environments with several clusters. In this case, the selected cluster can be picked from the Quick Settings dialog.
 
![image](https://user-images.githubusercontent.com/15186973/172885282-11eef536-2cbe-4c77-a024-cd03d6b54ba1.png)
