### ISSUE TITLE
Splunk Support for 8.1.4 and 8.2.1

### ISSUE THREAD

**Issue by sgulbetekin** [wazuh/wazuh-splunk#1100]
**Describe the solution you'd like**
AWS Marketplace has 2 versions of Splunk right now (8.1.4 and 8.2.1) however the Plugin doesn't work on those versions. Would love to have Splunk 8.1.4 and 8.2.1 supported.

**Describe alternatives you've considered**
Wazuh with ElasticSearch however, would be nice to get Splunk support.

**Additional context**
None.

**Comment by sgulbetekin** [comment]
New release from Splunk 8.2.2: https://docs.splunk.com/Documentation/Splunk/8.2.2/ReleaseNotes/MeetSplunk

**Comment by AlexRuiz7** [comment]
We are providing support for Splunk 8.2.2 on the next release
