### ISSUE TITLE
Enhancements for Wazuh App

### ISSUE THREAD

**Issue by orsifacundo** [wazuh/wazuh-splunk#1102]
Hi team, I'm requesting some enhancements for the Wazuh app on Splunk.

- [x]  Download pdf reports with selectable columns or at least the same columns as shown on the visualizations

As an example, when downloading a report of the vulnerabilities found for a specific agent, the report doesn't show the Severity but the visualization on the dashboards does.

**NOTE**: the perfect enhancement would be the CVE inventory added on Wazuh 4.2 with the possibility to download at least the CSV list.

![CVE](https://user-images.githubusercontent.com/46934023/131201421-fcdd9fc4-54fa-4151-8bb9-30a1e742ab18.png)

- [x]  Cluster node information that the Wazuh Agent is connected to.

As it's shown on the Kibana Wazuh App.

![Screenshot_20210826_181808](https://user-images.githubusercontent.com/46934023/131037483-1fd7b2cb-30a4-4c21-a5ae-88e72921fd98.png)

![Screenshot_20210826_181939](https://user-images.githubusercontent.com/46934023/131037592-61eaf564-a840-4353-9a2e-75bb4207e089.png)

I'll be adding more items.

**Comment by orsifacundo** [comment]
Update: [Added NOTE on first item]

**Comment by frankeros** [comment]
Hi @orsifacundo please move to another issue the enhancement about CVE inventory.

**Comment by orsifacundo** [comment]
Doe. Issue related to CVE inventory on Wazuh Splunk App: https://github.com/wazuh/wazuh-splunk/issues/1105
