### ISSUE TITLE
CVE inventory for App

### ISSUE THREAD

**Issue by orsifacundo** [wazuh/wazuh-splunk#1105]
Hi team, 

It would be a nice feature to have CVE inventory on the Wazuh Splunk App as the one on the Kibana App (starting from Wazuh 4.2)

![image](https://user-images.githubusercontent.com/46934023/131581732-2ba5f0ba-4446-4e30-a575-77d3af3ecf8b.png)

Regards.

**Comment by AlexRuiz7** [comment]
![image](https://user-images.githubusercontent.com/15186973/132011328-f47bab5a-b082-4b2f-a6d5-a9c87ffce8e5.png)

Needs further testing in order to verify that the filters, the search bar and the export functions work as expected

**Comment by AlexRuiz7** [comment]
[Pull Request](https://github.com/wazuh/wazuh-splunk/issues) opened to integrate the new funcionality.

After some more testing the funtionality seems to work properly. More details can be seen on the pull request
