### ISSUE TITLE
Upgrade JQuery libraries to version 3.5 or higher

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-splunk#1108]
Hello Team!

For the new versions of Splunk, in this case, 8.22 is required for all add-on apps JQuery 3.5.0.
It is needed for the Wazuh App for Splunk to upgrade its JQuery libraries to the requested version, or newer.
Reference: https://www.splunk.com/en_us/blog/platform/how-to-upgrade-your-app-to-jquery-v3-5-or-newer.html

Thank you in advance!

**Comment by AlexRuiz7** [comment]
(Just a note to myself)

Current jQuery version is 2.1.0
Uses jQuery-UI v1.12.1 (latest-stable)

**Comment by MauGaP** [comment]
testing finished | no compatibility issues found
