### ISSUE TITLE
Update references to deprecated authd options and consider the new ones.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-splunk#1110]
As part of epic [#9550](https://github.com/wazuh/wazuh/issues/9550) it is required to add new configuration options to the authd module to decide what actions should be taken during an agent replacement. That being said, it is needed to modify some config files to consider the new configuration block for authd new options, and remove the deprecated ones.

```
<force>
  <enabled>yes|no</enabled>
  <key_mismatch>yes|no</key_mismatch>  
  <disconnected_time enabled="yes"|"no">1h</disconnected_time>  
  <after_registration_time>1h</after_registration_time>  
</force>
```
- SplunkAppForWazuh/appserver/static/js/controllers/management/configuration/registration-service/registration-service.html
- SplunkAppForWazuh/bin/api_info/endpoints.json

**Comment by Machi3mfl** [comment]
<img width="1438" alt="Screen Shot 2021-11-09 at 00 21 19" src="https://user-images.githubusercontent.com/6089438/140923693-ddaddee6-a3ed-4afa-868e-1355738be88b.png">
<img width="1439" alt="Screen Shot 2021-11-09 at 00 21 51" src="https://user-images.githubusercontent.com/6089438/140923702-fafe1548-3ae0-4cc7-bee1-5be33fe66040.png">
