### ISSUE TITLE
[Feature request] Agent status visualization over time in the Agent tab

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-splunk#1113]
**Describe the solution you'd like**
It will be great to have a visualization with the status of the agents in the Splunk app to check the status in the last minutes. Like this:
![image](https://user-images.githubusercontent.com/23264276/132568118-9926fc22-e5fe-4632-a7a2-6a79f092c575.png)

Additionally, we can add a search bar to search for older days in that tab.

Regards,

Miguel Casares

**Comment by gabiwassan** [comment]
Added LinearChart on Agents view
![image](https://user-images.githubusercontent.com/11060558/135084625-bb07cf15-7be6-49a8-8eec-4a5262ca2928.png)

**Comment by AlexRuiz7** [comment]
Related issues:
https://github.com/wazuh/wazuh-splunk/issues/1209
https://github.com/wazuh/wazuh-splunk/issues/1201
