### ISSUE TITLE
API name can overflow it's cell in the table

### ISSUE THREAD

**Issue by mpRegalado** [wazuh/wazuh-splunk#1131]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.2.2   | 8.2.2    | 4203-1 |

**Description**
For long api names, when there are not enough spaces or `-` where the page can break the line, text can overflow into the adjacent cell.

**Steps to reproduce**

1. Have an API with a long name without any spaces or `-`
2. Reduce width as needed
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/80431234/134050087-433fa93e-53d9-4542-ae7c-302ea4c36c4b.png)

**Comment by AlexRuiz7** [comment]
Solved in 4.3, as part of the RBAC Epic https://github.com/wazuh/wazuh-splunk/issues/389
