### ISSUE TITLE
Research Wazuh RBAC implementation

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#1139]
|Wazuh| Splunk |
| --- | --- |
| 4.2.x| 8.1.x |

We need to investigate about implement Wazuh RBAC in the Splunk app. 
We should determine: 
- [x] Strategy to configure `run_as`.
- [x] Strategy to map Splunk users with Wazuh users
    > Search for the Splunk API to get the logged user, and the list of users from the front side and the backside.
- [x] Services (resolvers) to implement permissions to the resources. 
    > We should use the same function as the Wazuh API to check the permissions. 
    > We should use a centralized dictionary for the relation between the sections and permission that they need
- [x] Management (users, policies, role mapping, etc).

**Comment by sortizowlh** [comment]
At settings/authentication methods. Possibility to add an option for RBAC authentication.

![image](https://user-images.githubusercontent.com/47242022/135058084-fd501ea8-323e-44f4-9ef0-1d313016344a.png)

**Comment by sortizowlh** [comment]
- To implement run_as option into Wazuh plugin, it should have an option in the management panel, inside the configuration option.
This option should enable or disable run_as option to manage user permissions inside the plugin.

- To implement the relationship between each user and each permission, it should be as simple to manage.  
The main option is to create a list with all the permissions. Then, when the users send a request, the first step should be to check if the user has the requested permission.

- When a user hasn't permissions about the request, the response would be a warning message or redirecting the user to a common page showing that they do not have enough permissions. The method to advise the user that they do not have enough permissions could change by another different method.

- To manage the permissions inside the UI, the admin could have a role mapping page to add/remove permission to each user.

**Comment by sortizowlh** [comment]
Example of RBAC configuration at configuration section in management panel
![imagen](https://user-images.githubusercontent.com/47242022/135482514-609184fc-65b4-4bbc-9072-fab185168f82.png)

**Comment by sortizowlh** [comment]
Options to implement RBAC in Splunk:
- Inside manager section could be the sections User, Roles, Policies, and Role-mapping to manage the user permissions for RBAC.

- One option to implement the permissions management could be adding a middleware. When users send a request to the server, this middleware checks if the user has enough permissions to do the action requested. If there are not enough permissions, the middleware returns an error to show in a toast message.

**Comment by AlexRuiz7** [comment]
In order to keep it consistent with Wazuh's Kibana App, I think it would be better to add a new section with the only responsability of manage RBAC. This would mean a new section on the navigation bar named "Security", with a secondary navigation bar in it (as in Kibana) to toggle between Users, Roles, Policies and Roles mapping.

Kibana's RBAC
![image](https://user-images.githubusercontent.com/15186973/135825887-a16cad1e-46e7-4bed-bb89-86af3656547b.png)

Proposed Splunk's RBAC
_Note: ignore the icon, it's just a fast mockup_
![image](https://user-images.githubusercontent.com/15186973/135825945-4f061630-f62d-4c3b-9d44-f45d2be2e73a.png)

As a result, new views and controllers would be created leaving the rest untouched (for now), providing a cleaner and easier approach in terms of implementation.

**Comment by AlexRuiz7** [comment]
## Strategy to map Splunk users with Wazuh users

- [X] Search for the Splunk API to get the logged user
[Splunk's official documentation](https://docs.splunk.com/Documentation/Splunk/8.2.2/RESTREF/RESTaccess#authentication.2Fcurrent-context)
```bash
curl -k -u admin:adminpass https://localhost:8089/services/authentication/current-context
```

- [ ] Search for the list of users from the front side and the backside.
?????????

**Comment by AlexRuiz7** [comment]
## Strategy to map Splunk users with Wazuh users
- [X] Search for the Splunk API to get the logged user, and the list of users from the front side and the backside.
- [ ] Check how it's done in Kibana
- [ ] Check XML handler in Splunk backend
