### ISSUE TITLE
CRUD operations for Policies

### ISSUE THREAD

**Issue by sortizowlh** [wazuh/wazuh-splunk#1152]
|Wazuh| Splunk |
| --- | --- |
| 4.2.x| 8.1.4 / 8.2.2 |

**Description**
Add CRUD operations to manage policies in the new Splunk Security section.

**Tasks**
- [x] Add policie
- [x] Edit policie
- [x] Delete policie

**Comment by gabiwassan** [comment]
Added new table for resources 
![image](https://user-images.githubusercontent.com/11060558/140175385-bc8ac1af-e3dd-44e7-a5bd-87edb6bdf55e.png)

Remove confirm on the table:
![image](https://user-images.githubusercontent.com/11060558/140175651-8d287816-0f11-4184-8078-6ca6c12e5d28.png)
