### ISSUE TITLE
CRUD operations for Role mapping

### ISSUE THREAD

**Issue by sortizowlh** [wazuh/wazuh-splunk#1153]
|Wazuh| Splunk |
| --- | --- |
| 4.2.x| 8.1.4 / 8.2.2 |

**Description**
Add CRUD operations to manage role mapping in the new Splunk Security section.

Tasks:

- [x] List Role Mappings.
- [x] Add Role Mapping.
- [x] Edit Role Mapping.
- [x] Delete Role Mapping.

**Comment by eze9252** [comment]
Role Mapping List View: 

![Captura de pantalla de 2021-11-01 17-08-56](https://user-images.githubusercontent.com/36004787/139703603-0bc24326-e9b8-4af4-b093-fbaed6a7f2c2.png)

**Comment by eze9252** [comment]
Create a New Role Mapping View:

![Captura de pantalla de 2021-11-01 17-08-43](https://user-images.githubusercontent.com/36004787/139703699-a54cf22a-743a-45fe-be02-3cf2775fa15f.png)
