### ISSUE TITLE
Improve error handling in Wazuh app messages

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-splunk#1180]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.2.5   | 8.2.2    | - |

Hello team,

In a high loaded environment with more than 50k agents when navigating in the Wazuh app in Splunk and the page is not loading in time, the following error appears:

![image](https://user-images.githubusercontent.com/23264276/147353999-e2c61168-4809-4843-925f-abbfdbc50cd2.png)

Sometimes, Wazuh API timeout errors appear as well.

We should improve error handling messages in the Wazuh app for better error checking.

Regards,

Miguel Casares

**Comment by AlexRuiz7** [comment]
Might be solved or greatly improved with #389

**Comment by AlexRuiz7** [comment]
We are closing this issue as this situation has been greatly mitigated due to the recent works performed on the App, as stated before.

Here's an example:
![image](https://user-images.githubusercontent.com/15186973/163801965-7ba5c302-108e-47a2-bf8d-5b60d5dc7ec0.png)
