### ISSUE TITLE
Splunk - There are not options to edit or delete agent from a particular group

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-splunk#1189]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.2.2     | 1 |

**Description**
On a particular group page, the action column is displayed empty. There are no interact buttons to edit agents or remove them from a group

Preconditions

It needs to have created a new group and added at least one agent to it.

**Steps to reproduce**

- Navigate to the Groups page
- Click on a group name

**Expected Result**

The action column should display action buttons (edit, remove agent)
**Actual Result**

The action column it's displayed empty, this provokes that the agent could be deleted from a group

**Screenshots**
![Screenshot from 2022-01-21 09-30-51.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/3faa8a76-19dd-48ad-baad-cf876e10f60e)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by yenienserrano** [comment]
to be able to see the actions the user must have the role of `agent:modify_group`
