### ISSUE TITLE
Splunk - The background of the headers is overlapping with the security options

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-splunk#1190]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.2.2     | 1 |

**Description**
The background of Splunk headers is overlapping with the security options

**Steps to reproduce**

1. Navigates to security option

**Expected Result:** The background of Splunk headers is not overlapping with the security options
**Actual Result:** The background of Splunk headers is overlapping with the security options

**Screenshots**
![Screenshot from 2022-01-21 09-51-46.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/4b1b50f2-4e4c-496f-a8ea-9018d4dc8d00)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Mayons** [comment]
![Screenshot from 2022-01-21 10-04-37](https://user-images.githubusercontent.com/33849347/150531947-4ac446f4-38a2-4955-9d4c-b0d3f0d4a54a.png)

**Comment by yenienserrano** [comment]
Description:

The background of Splunk headers is overlapping with the security options

Resolve:

added class wz-margin-top-10 to security options

Test:

Navigates to security option

PR:

[1217](https://github.com/wazuh/wazuh-splunk/pull/1217)
