### ISSUE TITLE
Splunk - RBAC - User with read-only access can add new agents

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-splunk#1193]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3  | 8.2.2     | 1|

**Description**
Users that have read-only access can access to "Add new agent option"

Preconditions: Log with a user that has read-only access

**Steps to reproduce**

1. Go to the Agent page
2. Click on the "Add new agent" option

Expected Result:
The user should see a toast or an information message that display a message like "You don't have access to add a new agent"

Actual Result:
The add agent screen it's displayed and the user can completed the data and copy the installation curl

**Screenshots**
![Screenshot from 2022-01-21 12-14-42.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/ef076742-dd20-416a-b022-aecba687b32f)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by yenienserrano** [comment]
Description:

Users that have read-only access can access to "Add new agent option"

Resolve:

add create agent check

Test:

Preconditions: Log with a user that has read-only access

Go to the Agent page

PR:

[1216](https://github.com/wazuh/wazuh-splunk/pull/1216)
