### ISSUE TITLE
Agent count are not centered

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-splunk#1195]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.2.2     | 1 |

**Description**
On the agent page the numbers of connect/disconnect/never-connected agents are not displayed at the center of the label

**Steps to reproduce**

1. Go to the agent page

Expected result: Agent counts should be center hit the agent status header
Actual result:  Agent counts are aligned at the right of the header
**Screenshots**

![Screenshot from 2022-01-21 12-54-43.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/be2bec6d-851d-4595-80fc-897e84b3b551)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by yenienserrano** [comment]
Description:

On the agent page the numbers of connect/disconnect/never-connected agents are not displayed at the center of the label

Resolve:

added class wz-text-align-center in counter

Test:

Navigate to Agents

PR:

[1215](https://github.com/wazuh/wazuh-splunk/pull/1215)
