### ISSUE TITLE
Splunk - RBAC - A user that only has access to a particular agent can see alerts for other agents

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-splunk#1198]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3 | 8.2.2     |1 |

**Description**
A user that only has access to a particular agent can see alerts for other agents

**Steps to reproduce**

1. Go to the security events module
 Expected result: The user can only see alerts related to the agent that the user has access
Actual result: The user can see alerts related to all the agents connected to the manager

**Screenshots**
![Screenshot from 2022-01-21 15-00-07.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/d794186c-3b16-4070-99e7-7095322046ba)
![Screenshot from 2022-01-21 14-58-48.png](https://images.zenhubusercontent.com/61aa085f76e57e2cf22704e0/81457f4c-1be0-43ee-9790-a9bc63cf2c40)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by AlexRuiz7** [comment]
Not an issue
