### ISSUE TITLE
Restart manager options still displayed after the restarting of the manager process ended

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-splunk#1202]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3  | 8.1.4 | 1|

**Description**
Restart manager options still displayed after the restarting of the manager process ended

**Steps to reproduce**

1. Navigate to settings/status
2. Click on the restart manager option
3. Click on Confirm button 

Expected Result: The reboot manager options should not be displayed after the reboot process
Actual Result: Reboot manager reboot options still display after the reboot process

**Screenshots**

![Screenshot from 2022-01-25 09-23-46](https://user-images.githubusercontent.com/33849347/150977322-58baff78-709e-4898-a4fa-2c005c934245.png)
![Screenshot from 2022-01-25 09-30-53](https://user-images.githubusercontent.com/33849347/150977428-9a74c7f5-8411-486e-880f-5a6c07c3fda2.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by yenienserrano** [comment]
**Description:**

Restart manager options still displayed after the restarting of the manager process ended

**Resolve:**

Removed one of the functions that was executed when clicking commit

**Test:**

Navigate to management/status
Click on the restart manager option
Click on Confirm button

**PR:**

[1205](https://github.com/wazuh/wazuh-splunk/pull/1205)
