### ISSUE TITLE
Most active agent feature is not working

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-splunk#1204]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.1.4   | 1|

**Description**
Most active agent feature is not working, it's displayed cero, and when the user clicks on the most active agent link a toast is displayed with an error message

**Steps to reproduce**

1. Navigates to the agent's page

Expected result: The user should see the name of the most active agent down of the "Most active agent" label and when the user clicks on the agent name it's being redirected to the particular agent page.
Actual result: It's displayed a "0" instead of an agent name, and when the link is clicked, a toast is displayed with the error message: " agentInfo.data.data.affected_items[0] is undefined"

**Screenshots**
![Screenshot from 2022-01-25 09-55-48](https://user-images.githubusercontent.com/33849347/150981883-7937ccdc-691c-4b6a-aeef-8f54e8dc0700.png)
![Screenshot from 2022-01-25 09-56-14](https://user-images.githubusercontent.com/33849347/150981892-aba27e0e-507b-4254-a3f3-7cb9693cc051.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by yenienserrano** [comment]
This error appears when you are not receiving the alerts, adding the `forward-server` solves the problem.

Example:

`/opt/splunkforwarder/bin/splunk add forward-server indexer:9997 `
