### ISSUE TITLE
Filters preseted on modules

### ISSUE THREAD

**Issue by Mayons** [wazuh/wazuh-splunk#1207]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3 | 8.1.4| 1 |

**Description**
Accessing to all the modules there is apply a preset filter
On Splunk 8.1.4 version is: the manager's name
On Splunk 8.2.2 version is: the cluster name
And this filter can't be deleted

**Steps to reproduce**
1. Navigate to the security event module

Expected result: The dashboard is displayed correctly and no filters are applied
Actual result: The dashboard is displayed filter by a preset filter.

![image](https://user-images.githubusercontent.com/33849347/150993532-4110bb20-e2d7-4707-aaea-a2357a7a65e1.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by AlexRuiz7** [comment]
Not a bug. That's an implicit filter procedurarly generated based on the selected manager/agent
