### ISSUE TITLE
searchTopAgent component failes to be re-initiailized

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1222]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.2.2   | 4301 |

**Description**
Using an user with no permissions to enter the Agents section produces an error on the controller. There is already a component with such DOM element's ID.

**Steps to reproduce**
Using RBAC and an user with no `agents:read` permissions:

1. Open the browser's Dev Tools (F12) and Console
1. Go to 'Agents' view
2. The App is hidden (Ok)
3. Navigate out of `Agents` and then back in.

```js
Error: Already have instance with id: searchTopAgent
    at child.registerInstance (index.js:1148:1511968)
    at child.constructor (index.js:1148:1372929)
    at child [as constructor] (index.js:653:141099)
    at new child (index.js:653:141099)
    at new SearchHandler (search-handler.js:38:9)
    at new Agents (agentsCtrl.js:165:23)
    at Object.instantiate (angular.js:50:104)
    at angular.js:100:67
    at Object.<anonymous> (router.js:16:102526)
    at angular.js:22:134 '<ui-view class="ng-scope" data-ng-animate="1">'
```

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6107e5607e1305c767c43b95/b9023465-c2d9-494f-b6d0-a79313df91b7)

**Comment by yenienserrano** [comment]
Resolve:

Added destroy if this.linearChartAgent exists to call this.linearChartAgent.destroy(), which did not allow doing this.topAgent.destroy()

Steps to reproduce
Using RBAC and an user with no agents:read permissions:

1.Open the browser's Dev Tools (F12) and Console
2.Go to 'Agents' view
3.The App is hidden (Ok)
4.Navigate out of Agents and then back in.
5.See that no error appears

PR:

Added condition for destroy [#1223](https://github.com/wazuh/wazuh-splunk/pull/1223)
