### ISSUE TITLE
Creating new group with spaces in the name is not validated in the UI

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-splunk#1245]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.2.4     | 444 |

**Description**
The user interface allows to create a new group with a space in its name which makes the request fail.

The UI should control valid group names.

**Steps to reproduce**

1. Go to `Management / Groups`
2. Click on (+) button to create a new group
3. Fill in a group name with spaces
4. Press the save button and see error

**Screenshots**
![image](https://user-images.githubusercontent.com/9343732/153267222-085f2e22-30f0-480e-bf3c-33ec36b913e0.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by AlexRuiz7** [comment]
The Wazuh API responds with a `Bad Request` message as group names (IDs) cannot contain spaces.

The issue can be resolved in two differente ways that affect User's Experience:
1. Validating the data and displaying an error message indicating that group names can't use whitespaces (requires user interaction).
2. Validating the data and replacing any whitespace with an underscore (does not require user interaction).

![image](https://user-images.githubusercontent.com/15186973/153457378-a4ef1b91-4a27-4a52-9000-892505c28495.png)

**Comment by AlexRuiz7** [comment]
Nice to have
----------
Bind the Eenter key with the save action
