### ISSUE TITLE
CDB List should validate white spaces in keys

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-splunk#1252]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.2.4 | 444 |

**Description**
Create new CDB List form should validate white spaces in keys to prevent server side errors.

**Steps to reproduce**

1. Go to `Management / Ruleset`
2. Click on `Lists` tab
3. Click on `Add new list`
4. Fill in a file name without spaces
5. Create keys and values with spaces
6. Click Save file button and see error
. 
**Screenshots**
![image](https://user-images.githubusercontent.com/9343732/153471639-0bb86f22-9c0f-40db-940c-c60a5d55ac09.png)

![image](https://user-images.githubusercontent.com/9343732/153471714-23e5fc88-c1d5-4b9b-9131-dbf3d8b1b831.png)

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by AlexRuiz7** [comment]
Related issue: #1245

Nice to have
-------------
Centralized input validator for re-usability
