### ISSUE TITLE
Empty Alerts Summary despite there is a lot of vulnerablities in the index

### ISSUE THREAD

**Issue by frippen7** [wazuh/wazuh-splunk#1264]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.2.5   | 8.2.2     | 4206 |

**Description**
Allerts summary on the vulnerability page is empty because an error in the search. It uses data.vulnerablity.references instead of dta.vulnerabilities.refrences{}. When I change the search string it works in my environment

**Steps to reproduce**

1. Go to Overview\Vulnerabilities\
2. Scroll down to Alerts Summary
3. The view is empty

**Comment by AlexRuiz7** [comment]
Hi @frippen7 

Thank you for the report. 

In fact, there is a problem on the search string that prevents the table from showing data. I've applied your solution and it works perfectly. We will include it as soon as possible.

Also, as you reported the issue and provided a solution, you could create a Pull Request if you wish that your contribution gets recorded on GitHub and becomes part of this Open Source Project.

Best regards,
Alex

**Comment by AlexRuiz7** [comment]
Expected result
-----------------
This is how the table must be shown (applies the fix described above).
![image](https://user-images.githubusercontent.com/15186973/154944825-9f25bb11-f58d-4c95-bb79-c5da762f0826.png)


Actual result
----------------
This is how the table is behaving on the latest build.
![image](https://user-images.githubusercontent.com/15186973/154944889-24ba48a1-5440-4e2a-b7e2-8f62e0991dd2.png)
