### ISSUE TITLE
Error message on Agents tab

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-splunk#1299]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3.0   | 8.2.2     |  4303 |

**Description**
I set up Splunk indexer node and another node with Manager and forwarder to test.
Without agents the message:
```
  Unable to retrieve results. It may be due to a connection problem with the Splunk forwarder, please try restarting this service. 
```
Always appears when tab `Agents` is selected.

**Steps to reproduce**

1. Go to `Agents` without agents configured.
2. See the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/10661307/162740539-993542e1-d641-4f24-a484-5a29019173c7.png)

**Comment by Desvelao** [comment]
# Research
Replicating the exposed case: without registered agents, the toast message appears.

# Cause

The `Agents` section can displays:
- no registered agents or without permissions to get data of agents: the agent deployment guide
- with data of agents: agent status visualizations, some indicators, agents evolution visualization, agent's table

The controller for this UI section, initiates the search for the `Most active agent` indicator indepently of if there are agents or not.

Only in the case that the agents details go to be displayed, have sense to initiate the search for the `Most active agent` indicator.

# Remediantion

A proposed solution is to initiate the search for the `Most active agent` indicator only when there are agents and the agents' details will be displayed.

**Comment by Desvelao** [comment]
Solved in https://github.com/wazuh/wazuh-splunk/pull/1320.
