### ISSUE TITLE
Include RBAC messages in management/configuration section

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-splunk#1300]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3.0   | 8.2.2     |  4303 |

**Description**
Some RBAC messages aren't clear.

**Steps to reproduce**

Commands used to configure RBAC:
1. `TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")`
2. `curl -k -XPOST https://localhost:55000/security/roles -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"name": "app_demo_role"}`
3. `curl -k -XPOST https://localhost:55000/security/policies -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"name": "manager_deny_read", "policy": {"actions": ["manager:read", "cluster:read"], "resources": ["*:*:*", "node:id:*"], "effect": "deny"} }'`
4. `curl -k -XPOST https://localhost:55000/security/roles/100/policies?policy_ids=4,5,12,13,16,17,20,22,25,26,28,31,32,33,35,100 -H "Authorization: Bearer $TOKEN"`
5. `curl -k -XPOST https://localhost:55000/security/rules -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"name": "splunk_wazuh_demo_ro", "rule":{ "FIND": {"user_name": "demo"} } }'`
6. `curl -k -XPOST https://localhost:55000/security/roles/100/rules?rule_ids=100 -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"`
7. `curl -k -XPOST https://localhost:55000/security/rules -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json" -d '{"name": "splunk_wazuh_admin", "rule":{ "FIND": {"user_name": "wazuh"} } }'`
8. `curl -k -XPOST https://localhost:55000/security/roles/1/rules?rule_ids=1,2,101 -H "Authorization: Bearer $TOKEN"`

Steps to check error
1. Go to `management` inside Wazuh app with `demo` user logged in.
2. Click on `Configuration` option.
3. Click on any field, maybe Global configuration

**Screenshots**
Configuration error message ❌ 
![image](https://user-images.githubusercontent.com/10661307/162958709-093bb61f-50ba-4f76-a230-47155560fdda.png)
Security error message ✔️ 
![image](https://user-images.githubusercontent.com/10661307/162958815-53c7212a-f199-4764-97ef-82adbdb5e3c2.png)

**Comment by yenienserrano** [comment]
solved:
- #1316
