### ISSUE TITLE
Error loading the data: this.apiList.map is not a function

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-splunk#1301]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3.0   | 8.2.2     | 4303 |

**Description**
An error message appears on API section.

**Steps to reproduce**

This steps sometimes doesn't produce the error.
1. Go to API section
2. Add new API
3. Add another API connection 2 in total.
4. Remove one
5. Get out of such section and go again.
6. Check the error

**Screenshots**
![image](https://user-images.githubusercontent.com/10661307/163168320-79bb318e-ae32-4db7-a2f8-5218e67253d3.png)

**Comment by Machi3mfl** [comment]
### I couldn't reproduce this error.

https://user-images.githubusercontent.com/6089438/166815495-2abe969f-7053-44e8-a6da-58602711cf8f.mov

**Comment by yenienserrano** [comment]
### I couldn't reproduce this error.

https://user-images.githubusercontent.com/63758389/166898940-664e9c4c-a469-428b-b549-7a46f5e9395a.mp4

**Comment by AlexRuiz7** [comment]
I've seen this error myself a couple of times, and my guess is that this is related to the browser's cache. The focus to reproduce should be set on fresh environments and/or upgraded environments.

**Comment by asteriscos** [comment]
This issue happens after the app is idle for a long period of time. Seems the token used to get the API list from the DB is no longer valid.

![image](https://user-images.githubusercontent.com/9343732/169359589-9deee7ef-a832-42ad-bf51-05c9d2400b5f.png)


When it tries to check the API connection it fails even though a proper API ID is provided. 
![image](https://user-images.githubusercontent.com/9343732/169360055-0e4a2db7-04c3-444b-90be-fab33b9f19be.png)
![image](https://user-images.githubusercontent.com/9343732/169360078-85e54ab9-995d-4757-bd0e-3f8c71a9e446.png)


![image](https://user-images.githubusercontent.com/9343732/169359746-d971833e-c63b-4264-a1cd-fd166c66795a.png)
