### ISSUE TITLE
Splunk support for all minor versions 8.1.X and 8.2.X

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-splunk#1306]
## Description

We need to generate packages for all minor versions of Splunk 8.1.X and 8.2.X

We need to start from latest to older.

We need to ensure:

>  - The release notes do not contain information which might cause our app to malfunction
>  - Our app installs without errors
>  - We test the application with a single browser
>    - We can navigate through all main modules
>    - We can contact the API and get results
>    - The discover works with sample data
>    - These smoke tests should focus in general functionality, as the detailed test were already done in major versions.

## Found Issues
- https://github.com/wazuh/wazuh-splunk/issues/1234
- https://github.com/wazuh/wazuh-splunk/issues/1311

**Comment by AlexRuiz7** [comment]
## Splunk 8.2.x

- [ ] 8.2.6
- [ ] 8.2.5
- [x] 8.2.4
- [ ] 8.2.3
- [x] 8.2.2
- [ ] 8.2.1
- [ ] 8.2.0


## Splunk 8.1.x

- [ ] 8.1.10
- [ ] 8.1.9
- [ ] 8.1.8
- [ ] 8.1.7
- [ ] 8.1.6
- [ ] 8.1.5
- [x] 8.1.4
- [ ] 8.1.3
- [ ] 8.1.2
- [ ] 8.1.1
- [ ] 8.1.0

**Comment by AlexRuiz7** [comment]
## Splunk 8.2.6

 - [ ] The release notes do not contain information which might cause our app to malfunction
 - [ ] Our app installs without errors
 - [ ]  We test the application with a single browser
   - [ ]  We can navigate through all main modules
   - [ ]  We can contact the API and get results
   - [ ] The discover works with sample data
   - [ ] These smoke tests should focus in general functionality, as the detailed test were already done in major versions.

**Comment by mauceballos** [comment]
15 minor versions to test.

## Splunk 8.2.x

[Release Notes](https://docs.splunk.com/Documentation/Splunk/8.2.6/ReleaseNotes/MeetSplunk)

- [ ] 8.2.6
- [ ] 8.2.5
- [ ] 8.2.4
- [x] 8.2.3
- [ ] 8.2.2
- [ ] 8.2.1
- [ ] 8.2.0

**Comment by mauceballos** [comment]
## Splunk 8.2.3

 - [x] The release notes do not contain information which might cause our app to malfunction
 - [x] Our app installs without errors
 - [x]  We test the application with a single browser
   - [x]  We can navigate through all main modules
   - [x]  We can contact the API and get results
   - [x] The discover works with sample data
   - [x] These smoke tests should focus in general functionality, as the detailed test were already done in major versions.

**Comment by yenienserrano** [comment]
## Splunk 8.1.0 -  8.1.1 - 8.1.2 -  8.1.3 - 8.1.5

 - [x] The release notes do not contain information which might cause our app to malfunction
 - [x] Our app installs without errors
 - [ ]  We test the application with a single browser
   - [ ]  We can navigate through all main modules
   - [x]  We can contact the API and get results
   - [x] The discover works with sample data
   - [ ] These smoke tests should focus in general functionality, as the detailed test were already done in major versions.
   
In all the versions I had the same problem that I did with the FIM and Vulnerability configuration and it does not show me any data. The same configuration was tested in kibana and it shows the corresponding data.

![image](https://user-images.githubusercontent.com/63758389/164486676-e422e716-00d0-434d-873b-67f8c7d776be.png)
![image](https://user-images.githubusercontent.com/63758389/164486770-f2dbcf2e-d287-4bc9-8c0f-43d60848401c.png)

**Comment by yenienserrano** [comment]
## Splunk 8.1.0

FIM and Vulnerability views break when you have an agent selected

![image](https://user-images.githubusercontent.com/63758389/164488026-c474a79d-0206-48b0-a907-12796683bad7.png)
![image](https://user-images.githubusercontent.com/63758389/164488087-9bab8ead-beeb-4711-b717-0e31d459ad1c.png)
![image](https://user-images.githubusercontent.com/63758389/164488292-d260555c-e1f2-4c06-ae6f-b0ff521b55d7.png)

**Comment by mauceballos** [comment]
## Splunk 8.2.0, 8.2.1

 - [x] The release notes do not contain information which might cause our app to malfunction
 - [x] Our app installs without errors
 - [ ]  We test the application with a single browser
   - [ ]  We can navigate through all main modules
   - [x]  We can contact the API and get results
   - [x] The discover works with sample data
   - [ ] These smoke tests should focus in general functionality, as the detailed test were already done in major versions.

**Comment by AlexRuiz7** [comment]
Work in progress and pending review.

**Comment by mauceballos** [comment]
## Splunk 

<details><summary>v4.3.0-8.2.5</summary>

![Screenshot from 2022-04-22 13-38-18](https://user-images.githubusercontent.com/76791841/165097404-a17f1eed-ca3a-4a2c-b26c-42eaf724b1de.png)

![Screenshot from 2022-04-22 15-13-22](https://user-images.githubusercontent.com/76791841/165097860-cf0584e4-a78b-4623-a128-78ae809e26ff.png)

</details>

<details><summary>v4.3.0-8.2.3</summary>

![Screenshot from 2022-04-22 15-31-20](https://user-images.githubusercontent.com/76791841/165098020-d5018701-d8d3-4665-9ff9-e22435885a83.png)

![Screenshot from 2022-04-22 15-31-32](https://user-images.githubusercontent.com/76791841/165098026-376a5855-645a-43e1-8af8-4e4af5bf2496.png)

</details>

- <summary>v4.3.0-8.2.1</summary>

- <summary>v4.3.0-8.2.0</summary>


<details><summary>v4.3.0-8.1.10</summary>

![Screenshot from 2022-04-22 15-49-27](https://user-images.githubusercontent.com/76791841/165098290-537409e8-ce1c-4d7a-9c46-0f10f943fd92.png)

![Screenshot from 2022-04-22 16-46-29](https://user-images.githubusercontent.com/76791841/165100214-99d529e1-6962-4f01-9783-defaca3d4dee.png) 

![Screenshot from 2022-04-22 16-46-42](https://user-images.githubusercontent.com/76791841/165100238-d764e291-f83b-40b2-aa27-eb3b9c839e27.png)

</details>




<details><summary>v4.3.0-8.1.9</summary>

![Screenshot from 2022-04-22 16-00-32](https://user-images.githubusercontent.com/76791841/165098596-979810b7-3b49-4fe5-852e-ee66c227e01f.png)

![Screenshot from 2022-04-22 16-01-07](https://user-images.githubusercontent.com/76791841/165098660-0af6df3b-6209-4cb5-a180-383330e97757.png)

</details>

<details><summary>v4.3.0-8.1.8</summary>

![Screenshot from 2022-04-22 16-20-41](https://user-images.githubusercontent.com/76791841/165098821-229474cd-d17c-42f2-ad38-49bf30749e90.png)

![Screenshot from 2022-04-22 16-21-34](https://user-images.githubusercontent.com/76791841/165098867-8a116429-26ad-43c0-8d71-4cbcedd0428d.png)

</details>


<details><summary>v4.3.0-8.1.7.1</summary>

![Screenshot from 2022-04-22 16-34-29](https://user-images.githubusercontent.com/76791841/165099183-e097ecad-ed13-4ac6-9aa1-d9b4a9afbfa7.png)

![Screenshot from 2022-04-22 16-34-57](https://user-images.githubusercontent.com/76791841/165099202-4948a343-d4d6-4858-be7a-6f3e859bc87d.png)

</details>

<details><summary>v4.3.0-8.1.7</summary>

![Screenshot from 2022-04-22 16-46-42](https://user-images.githubusercontent.com/76791841/165098473-2501c342-f6bf-4794-9c41-fdf1bdd08d3b.png)

![Screenshot from 2022-04-22 16-46-29](https://user-images.githubusercontent.com/76791841/165098506-4b8318f9-b990-4b4e-a60a-cb0fb50527e5.png)

</details>

- [x] The release notes do not contain information that might cause our app to malfunction
 - [x] Our app installs without errors
 - [x]  We test the application with a single browser
   - [x]  We can navigate through all main modules
   - [x]  We can contact the API and get results
   - [x] The discover works with sample data
   - [x ] These smoke tests should focus on general functionality, as the detailed test was already done in major versions.

**Comment by AlexRuiz7** [comment]
## Summary

Only 8.1.0 is not fully compatible, as some views break down, as reported on #1311
