### ISSUE TITLE
RBAC - Management- Configuration in single-node does not allow visualization

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-splunk#1317]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3   | 8.X.X     | 4301 |

**Description**
When the Wazuh manager is set up as a single node, the ACL of the RBAC does not allow seeing or modifying its configuration from the UI. 
If we configure the manager in cluster mode, it works as expected.

**Steps to reproduce**

1. Deploy wazuh with a single manager
2. Deploy splunk
3. Login using admin 
4. Navigate to Management -> Configuration

**Screenshots**

Got: 

![image](https://user-images.githubusercontent.com/2181918/166980866-440a1085-1d4a-4989-a973-066725a2eadd.png)

Expected:

![image](https://user-images.githubusercontent.com/2181918/166980597-c5ac210f-927e-487a-877d-1b847b2f860d.png)

**Additional context**
 
Additional tests must be done against the RBAC implementation.

**Comment by Machi3mfl** [comment]
### Solution:
For testing check issue #1300 
- Test with `admin` and `demo` user on cluster mode enabled
- Test `admin` and `demo` user on cluster mode disabled

https://user-images.githubusercontent.com/6089438/166987087-a0f8e53c-baa0-41e3-a564-850641cf70ed.mov

**Comment by Desvelao** [comment]
Solved in: https://github.com/wazuh/wazuh-splunk/pull/1318
