### ISSUE TITLE
Release 4.3.4 RC1 - Wazuh UI Manual Testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1333]
# CHANGELOG

### Added
- Support for Wazuh 4.3.4
  - **Test 0**: validate the package
      Check that the package installs correctly, and that it's possible no navigate through the App without errors.

### Changed
- Improved Splunk search-handler event management to avoid forwarder toast error misinterpretation.
  - **Test 1**: check that no error of the kind "Unable to retrieve results" occurs when there are results on the visualizations (the environment is correctly configured).
  - **Test 2**: if there are no results for the visualizations, the "Unable to retrieve results" message should show up on a toast, but as a warning (the forwarder might be down).
  - **Test 3**: no error of any other kind should happen.

### Fixed
- Fixed unhandled expired session when requesting Splunk DB documents. [#1329](https://github.com/wazuh/wazuh-splunk/pull/1329)
  - **Test 4**: APIs can be added, deleted and updated without errors.
  - **Test 5**: the steps indicated on the issue #1301 do not produce an error.

## Tests template

Use the template to document the tests done.

|Test      | Chrome | Safari | Firefox  | Package |
| -- | -- | -- | -- | -- |
| Test 1   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    🟢 /🔴        |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In case of 🔴, create and link the issue.

## Known issues to date

- #1331
- #1332

**Comment by AlexRuiz7** [comment]
## Summary

|Test      | Chrome | Safari | Firefox  | Package |
| -- | -- | -- | -- | -- |
| Test 1   |     🟢 /🔴     |     🟢 /🔴   |       🟢 /🔴    |    🟢 /🔴        |

**Comment by Mayons95** [comment]
## Splunk 4.3.4 - 8.1.4

|Test      | Chrome | Safari | Firefox  | Package | 
| -- | -- | -- | -- | -- |
| Test 1   |  🟢   |      🟢 |      🟢 /🔴    | 4.3.4 - 8.14
| Test 2   |  🟢  |      🟢/🔴  |      🟢 /🔴    | 4.3.4 - 8.14 
| Test 3   |  🟢  |      🟢    |      🟢 /🔴    | 4.3.4 - 8.14  
| Test 4   |  🟢 |      🟢    |      🟢 /🔴    | 4.3.4 - 8.14 
| Test 5  |  🟢 |      🟢 /🔴   |      🟢 /🔴    | 4.3.4 - 8.14

**Comment by Mayons95** [comment]
## Splunk 4.3.4 - 8.2.6

|Test      | Chrome | Safari | Firefox  | Package | 
| -- | -- | -- | -- | -- |
| Test 1   |  🟢   |      🟢 |      🟢 /🔴    | 4.3.4 - 8.2.6
| Test 2   |  🟢  |      🟢/🔴  |      🟢 /🔴    | 4.3.4 - 8.2.6
| Test 3   |  🟢  |      🟢    |      🟢 /🔴    | 4.3.4 - 8.2.6
| Test 4   |  🟢 |      🟢    |      🟢 /🔴    | 4.3.4 - 8.2.6
| Test 5  |  🟢 |      🟢    |      🟢 /🔴    | 4.3.4 - 8.2.6

**Comment by Mayons95** [comment]
## Splunk 4.3.4 - 8.2.6

|Test      | Chrome | Safari | Firefox  | Package | 
| -- | -- | -- | -- | -- |
| Test 1   |  🟢   |     :black_circle:  |      🟢     | 4.3.4 - 8.2.0
| Test 2   |  🟢  |      :black_circle:   |      :green_circle:     | 4.3.4 - 8.2.0
| Test 3   |  🟢  |      :black_circle:    |      🟢  | 4.3.4 - 8.2.0
| Test 4   |  🟢 |      :black_circle:    |      🟢     | 4.3.4 - 8.2.0
| Test 5  |  🟢 |      :black_circle:    |      🟢    | 4.3.4 - 8.2.0

**Comment by AlexRuiz7** [comment]
## Splunk 4.3.4 - 8.1.8

| Test   | Chrome         | Safari         | Firefox        | Package       |
| ------ | -------------- | -------------- | -------------- | ------------- |
| Test 1 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.1.8 |
| Test 2 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.1.8 |
| Test 3 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.1.8 |
| Test 4 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.1.8 |
| Test 5 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.1.8 |

**Comment by AlexRuiz7** [comment]
## Splunk 4.3.4 - 8.2.4

| Test   | Chrome         | Safari         | Firefox        | Package       |
| ------ | -------------- | -------------- | -------------- | ------------- |
| Test 1 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.4 |
| Test 2 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.4 |
| Test 3 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.4 |
| Test 4 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.4 |
| Test 5 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.4 |

## Splunk 4.3.4 - 8.2.3

| Test   | Chrome         | Safari         | Firefox        | Package       |
| ------ | -------------- | -------------- | -------------- | ------------- |
| Test 1 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.3 |
| Test 2 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.3 |
| Test 3 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.3 |
| Test 4 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.3 |
| Test 5 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.3 |

## Splunk 4.3.4 - 8.2.2

| Test   | Chrome         | Safari         | Firefox        | Package       |
| ------ | -------------- | -------------- | -------------- | ------------- |
| Test 1 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.2 |
| Test 2 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.2 |
| Test 3 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.2 |
| Test 4 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.2 |
| Test 5 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.2 |

## Splunk 4.3.4 - 8.2.1

| Test   | Chrome         | Safari         | Firefox        | Package       |
| ------ | -------------- | -------------- | -------------- | ------------- |
| Test 1 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.1 |
| Test 2 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.1 |
| Test 3 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.1 |
| Test 4 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.1 |
| Test 5 | :green_circle: | :black_circle: | :green_circle: | 4.3.4 - 8.2.1 |

**Comment by mauceballos** [comment]
## Splunk 4.3.4 - 8.1.3

|Test      | Chrome | Safari | Firefox  | Package | 
| -- | -- | -- | -- | -- |
| Test 1   |  🟢   |      🟢   |      ⚫️   | 4.3.4 - 8.1.3
| Test 2   |  🟢   |       🟢    |      ⚫️    | 4.3.4 - 8.1.3
| Test 3   |  🟢  |      🟢   |      ⚫️   | 4.3.4 - 8.1.3
| Test 4   |  🟢  |      🟢   |      ⚫️    | 4.3.4 - 8.1.3
| Test 5  |  🟢  |      🟢   |      ⚫️    | 4.3.4 - 8.1.3

**Comment by AlexRuiz7** [comment]
All tests passed succesfully.
