### ISSUE TITLE
Release 4.3.5 RC1 - Wazuh UI Manual Testing

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1347]
# Wazuh v4.3.5 - Splunk Enterprise 8.1.x, 8.2.x - Revision 4308

| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢/🔴  | 🟢/🔴 | 🟢/🔴    | 🟢/🔴  |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue. 

### Added

- Support for Wazuh 4.3.5

### Fixed

- Fixed a bug that didn't allow adding a Wazuh API if some other Apps were installed, reporting Unexpected Wazuh version [#1340](https://github.com/wazuh/wazuh-splunk/pull/1340)
- Outdated documentation links have been updated https://github.com/wazuh/wazuh-splunk/pull/1290
- The Alerts view from the MITRE section has been hardened in case of errors during the requests to the API (for example timeouts) https://github.com/wazuh/wazuh-splunk/pull/1343

### Changed

- Added the status Pending to the Agents sections. https://github.com/wazuh/wazuh-splunk/pull/1292
- Added a disabled state to the Apply changes button on the Agents group editor when no changes to the group are made. https://github.com/wazuh/wazuh-splunk/pull/1276

## Tests for [#1340](https://github.com/wazuh/wazuh-splunk/pull/1340)

Splunk behaviour living together with another splunk apps  -  [#1340](https://github.com/wazuh/wazuh-splunk/pull/1340)
**Scenario: Install other apps in addition to Wazuh**
```
Preconditions: There has to be installed more than one third-party application must be installed
Given The Splunk admin user is logged 
When The user starts Wazuh app
Then there is no displayed toast informing a mismatch error
```

## Tests for [#1290](https://github.com/wazuh/wazuh-splunk/pull/1290)
Documentation links  -  [#1290](https://github.com/wazuh/wazuh-splunk/pull/1290)
**Scenario: Check the navigation between the documentation links.**
```
Given The Splunk admin user is logged
When The user navigates to Management/Configuraion 
And The user selects an a <Section>
And The user clicks on the ‘?’ button
Then The user is redirected to the expected documentation link
Example:
 |Submodule |
 |Azure|
 |Cluster|
```

Documentation links - Agent Page  -  [#1290](https://github.com/wazuh/wazuh-splunk/pull/1290)
**Scenario: Check the navigation between the documentation links - Agent Page**
```
Given The Splunk admin user is logged
When The user navigates to the agent page
And The user navigates to an agent settings
And The user selects an a <Subsection>
And The user clicks on the ‘?’ button
Then The user is redirected to the expected documentation link
Example:
 |Submodule |
 |Global Configuration|
 |Client configuration|
 |Anti-flooding settings|
 |Labels|
 |Policy Monitoring|
 |OpenSCAP|
 |CIS-CAT|
 |Osquery|
 |Inventory data|
 |Active response|
 |Commands|
 |Docker Listener|
 |Log Collection|
 |Integrity Monitoring|
```

Documentation links - Roles Mapping Page  -  [#1290](https://github.com/wazuh/wazuh-splunk/pull/1290)
**Scenario: Check the navigation between the documentation links - Roles Mapping Page.**
```
Given The Splunk admin user is logged
When The user navigates to Security/roles-mapping
And The user clicks on the “Add new role” button
And The user clicks on the “Learn more” link
Then The user is redirected to the expected documentation link
```

## Tests for #1343

Mitre Dashboard Handle Errors by a Time Out  -  [#1343](https://github.com/wazuh/wazuh-splunk/pull/1343)
**Scenario: Time out for Mitre Alerts Request**
How to Test
Build a fresh environment.
Go to MITRE.
Click on Show Alerts
Check that the error shown is related to a timeout, as seen on the image above.
Check that the view do not break, as seen on the comparison above.
Re-enter the same view or refresh. Check that no timeout error happens, and the view is rendered correctly.
How to reproduce once the API response has been cached
Remove the manager_forwarder container in VS code (Docker plugin) --> Right click --> Remove.
Rebuild the container: docker-compose up -d.
Add the forwarder: addForwarder utility.
Continue from step 2 on How to test.

## Tests for [#1292](https://github.com/wazuh/wazuh-splunk/pull/1292)
Status Chart  -  [#1292](https://github.com/wazuh/wazuh-splunk/pull/1292)
**Scenario: Check the pending status is displayed on the status chart**
```
Given The Splunk admin user is logged
When The user navigates to the agent page
Then The status chart is displayed with the next combination of status
 |Status|  |assigned color|
|Active|  |Green|
|Pending|  |Yellow|
|Disconnecred|  |Red|
|Never connected|  |Grey|
```

## Tests for [#1276](https://github.com/wazuh/wazuh-splunk/pull/1276)
Manage agents - Groups  -  [#1276](https://github.com/wazuh/wazuh-splunk/pull/1276)
**Scenario: Check that the Apply changes button is disabled when there is no selected agent**
```
Given The Splunk admin user is logged
When The user navigates to Management/groups
And The user selects a group
And The user clicks on the “Add or remove agents” button
And The user no select any agent to move
Then The “Apply changes” button should be disabled
```

Manage agents - Groups  -  [#1276](https://github.com/wazuh/wazuh-splunk/pull/1276)
**Scenario: Check that the Apply changes button is enabled when there is a selected agent**
```
Given The Splunk admin user is logged
When The user navigates to Management/groups
And The user selects a group
And The user clicks on the “Add or remove agents” button
And The user selects an agent to move
Then The “Apply changes” button should be enabled
```

**Comment by Machi3mfl** [comment]
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 1340| :green_circle: | :green_circle: | :black_circle | 4.3.5 - 8.1.10 |
| 1290| :green_circle: | :green_circle: | :black_circle: | 4.3.5 - 8.1.10 |
| 1343| :green_circle: | :green_circle: | :black_circle: | 4.3.5 - 8.1.10 |
| 1292| :green_circle: | :green_circle: | :black_circle: | 4.3.5 - 8.1.10 |
| 1276| :green_circle: | :green_circle: | :black_circle: | 4.3.5 - 8.1.10 |

**Comment by chantal-kelm** [comment]
| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 1340| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.1.4 |
| 1290| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.1.4 |
| 1343| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.1.4 |
| 1292| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.1.4 |
| 1276| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.1.4 |

**Screenshots**

![Screenshot from 2022-06-24 13-48-12](https://user-images.githubusercontent.com/99441266/175611914-3044ecbd-4cdd-4c23-a014-d4516edfd63a.png)
![Screenshot from 2022-06-24 13-52-11](https://user-images.githubusercontent.com/99441266/175611921-dc8b96af-216d-4a41-815a-1c7a5ed09312.png)
![Screenshot from 2022-06-24 13-54-42](https://user-images.githubusercontent.com/99441266/175611923-8c6d7b0c-cc3e-43a3-973f-bb4f3745e101.png)
![Screenshot from 2022-06-24 13-57-28](https://user-images.githubusercontent.com/99441266/175611980-02851166-338f-41c3-ad4b-fbc0226a2a72.png)
![Screenshot from 2022-06-24 13-58-05](https://user-images.githubusercontent.com/99441266/175612054-801a4756-0ec4-4429-aa3b-d2065d21ec44.png)
![Screenshot from 2022-06-24 13-58-13](https://user-images.githubusercontent.com/99441266/175612057-faf059ae-c58e-453d-a116-ea1ddf7f0055.png)
![Screenshot from 2022-06-24 14-04-55](https://user-images.githubusercontent.com/99441266/175612145-64025ac2-1d08-459c-9f6e-4e1c1630ab96.png)
![Screenshot from 2022-06-24 14-05-02](https://user-images.githubusercontent.com/99441266/175612152-cf49dbb4-9bea-4a30-9d2b-e64d67ef2097.png)
![Screenshot from 2022-06-24 14-17-18](https://user-images.githubusercontent.com/99441266/175612250-ec3a7ad8-d5d0-4447-b036-efdafa72a56f.png)
![Screenshot from 2022-06-24 14-18-30](https://user-images.githubusercontent.com/99441266/175612255-d4cf3ae4-5046-40df-8b66-34c022b293e2.png)
![Screenshot from 2022-06-24 14-20-47](https://user-images.githubusercontent.com/99441266/175612344-cb58690e-0316-4ec3-8e2b-8bfbcb4c58ce.png)

**Comment by yenienserrano** [comment]
### Splunk 8.2.5

| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 1340| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.5 |
| 1290| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.5 |
| 1343| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.5 |
| 1292| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.5 |
| 1276| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.5 |

**Comment by yenienserrano** [comment]
### Splunk 8.2.4

| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 1340| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.4 |
| 1290| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.4 |
| 1343| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.4 |
| 1292| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.4 |
| 1276| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.4 |

**Comment by yenienserrano** [comment]
### Splunk 8.2.3

| Test | Chrome | Safari | Firefox | Package |
| --- | --- | --- | --- | --- |
| 1340| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.3 |
| 1290| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.3 |
| 1343| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.3 |
| 1292| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.3 |
| 1276| :green_circle: | :black_circle: | :green_circle: | 4.3.5 - 8.2.3 |

**Comment by AlexRuiz7** [comment]
Testing done.

Only this minor bug has been found: #1348
