### ISSUE TITLE
Documentation link has an invalid URL

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-splunk#1348]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.3.5   | 8.1.4     | 4301 |

**Description**
Documentation links lead to 404.

- Management < Configuration < Registration Service < "How to use the registration service"
- Management < Configuration < Alerts < "Use cases about alerts generation"
- Management < Configuration < Vulnerabilities-Detector < "Vulnerabilities detection documentation"
- Management < Configuration < Vulnerabilities-Detector < "Vulnerabilities detection reference"

**Steps to reproduce**

1. Navigate to the sections above.
2. Click on documentation links described above.

Expected result: The link should redirect to a valid URL
Actual result: The link is redirecting to an invalid URL

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by Mayons95** [comment]
Same happens on:
Alerts/Use cases about alerts generation
Vulnerabilities-Detector - Vulnerabilities detection documentation
Vulnerabilities-Detector - Vulnerabiltiies detection reference

**Comment by AlexRuiz7** [comment]
## Comparison with Kibana

The **bold** links are the **broken** ones.

- Management < Configuration < Registration Service < "How to use the registration service"

  - **Kibana**: https://documentation.wazuh.com/current/user-manual/registering/simple-registration-method.html
  - **Splunk**: https://documentation.wazuh.com/4.3/user-manual/registering/use-registration-service.html
  
This link is also broken on Kibana. This one must be used: https://documentation.wazuh.com/current/user-manual/agent-enrollment/index.html

- Management < Configuration < Alerts < "Use cases about alerts generation"

  - Kibana: https://documentation.wazuh.com/current/getting-started/use-cases/index.html
  - **Splunk**: https://documentation.wazuh.com/4.3/getting-started/use-cases.html

- Management < Configuration < Vulnerabilities-Detector < "Vulnerabilities detection documentation"

  - Kibana: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/index.html
  - **Splunk**: https://documentation.wazuh.com/4.3/getting-started/use-cases.html

- Management < Configuration < Vulnerabilities-Detector < "Vulnerabilities detection reference"

  - Kibana: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/vuln-detector.html
  - **Splunk**: https://documentation.wazuh.com/4.3/user-manual/reference/ossec-conf/wodle-vuln-detector.html
