### ISSUE TITLE
Release 4.3.6 RC1 - Wazuh UI Manual Testing

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-splunk#1357]
# Wazuh v4.3.6

| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢/🔴  | 🟢/🔴 | 🟢/🔴    | 🟢/🔴  |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue. 

##  Scenarios to test:
1) Install the Wazuh app on Splunk
2) Set the connection to Wazuh API
3) Set the configuration to Wazuh Forwarder
4) Check that the charts are displayed.

###Test cases for Wazuh Splunk App 4.3.6

### @External-Documentation-Links
Fix Links to Wazuh Documentation [#1351](https://github.com/wazuh/wazuh-splunk/pull/1351)
Scenario: Documentation links redirect to Wazuh documentation
   Given The Wazuh admin user is logged
   When The user navigates to Configuration/Registration service
   And The user clicks on the ”How to use the registration service” option
   Then The user should be redirected to the Wazuh documentation.
   And the section of the documentation should match the Wazuh section name where the user was.

### Fix API console to allow payloads in requests [#1296](https://github.com/wazuh/wazuh-splunk/pull/1296)

Test comments: On the linked PR there are more path to check the documentation links.

Test 1: common use
Test that any available API endpoint works properly. The followings requests can be used:

GET /security/users/

POST /security/users/
{
	"username": "user_test",
	"password": "Pa$$word123"
}

PUT /security/users/100/
{
	"password": "pa$$word"
}

PUT /security/users/100/
{
	"password": "A$61a78e492"
}

DELETE /security/users?user_ids=100

GET /agents/999/key
GET /bsdg
GET /syscollector/000/packages?search=ssh&limit=1

GET /mitre/techniques

GET /agents/
{
	"invalid": "query param"
}
Test 2: edge cases
Test that unexpected errors are handled properly, for example, when a timeout happens.

The GET /mitre/techniques timeouts every time on a fresh environment. To force this behavior, reduce the App's timeout setting, then down any manager node (Docker), and rebuild it, so its cache is cleared. Finally go to the API console and launch the request.

### @Logs
Management log section[#1354](https://github.com/wazuh/wazuh-splunk/pull/1354)
Scenario: Reallow demon processors 
   Given The Wazuh admin user is logged
   When The user navigates to management/logs
   And The user clicks on the log selector
   And The user should be able to see task-manager and agent-upgrade on the log list
   And The user selects any of these logs
   Then The user could see log entries for the selected log

**Comment by Mayons95** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| External-Documentation-Links | 🟢 | ⚫  | 🟢 | 🟢  |

**Comment by Mayons95** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| External-Documentation-Links | 🟢 | ⚫  | 🟢 | 8.1.10|
| Fix API console to allow payloads in requests | 🟢 | ⚫  | 🟢 | 8.1.10 |
|Management - logs | 🟢 | ⚫  | 🟢 | 8.1.10|



![Image](https://user-images.githubusercontent.com/104914131/179568525-983b0347-e551-45f6-9390-eb6df568d8c0.png)
![Image](https://user-images.githubusercontent.com/104914131/179568524-6eb94a72-5764-4f6a-a6f9-d70a554938e9.png)
![Image](https://user-images.githubusercontent.com/104914131/179568529-852df656-aebf-41ef-8448-f9e5716fd849.png)
![Image](https://user-images.githubusercontent.com/104914131/179568523-3e2c046a-21aa-4679-9ac7-e08c9eafff73.png)
![Image](https://user-images.githubusercontent.com/104914131/179568528-25f6ec48-61d9-45e9-9a92-a0dbd69bab7e.png)
![Image](https://user-images.githubusercontent.com/104914131/179568526-b2ffb216-3f85-41b3-94f9-ca3ee937a1d2.png)
![Image](https://user-images.githubusercontent.com/104914131/179568527-5c227c5c-e496-43e1-b500-6af6ee0cfad8.png)

**Comment by chantal-kelm** [comment]
#1351 

![Screenshot from 2022-07-18 13-55-15](https://user-images.githubusercontent.com/99441266/179563572-b1935d66-7e85-459b-8e6a-035104127aaf.png)
![Screenshot from 2022-07-18 13-55-49](https://user-images.githubusercontent.com/99441266/179563573-bc116d57-1848-4ce0-b647-70cd86431b43.png)
![Screenshot from 2022-07-18 13-56-20](https://user-images.githubusercontent.com/99441266/179563574-8ee3f45c-a3a7-471e-a606-9530a633f577.png)
![Screenshot from 2022-07-18 13-56-34](https://user-images.githubusercontent.com/99441266/179563579-82ac88e5-b333-4de0-b37b-fa6cbffdc336.png)

#1296 

https://user-images.githubusercontent.com/99441266/179569074-3b95a5d0-e189-4fa5-a872-02fac5a194e4.mp4

#1354 

![Screenshot from 2022-07-18 14-13-39](https://user-images.githubusercontent.com/99441266/179567723-adfc4944-b5e9-48d6-a8f4-94a17b4da9a6.png)
![Screenshot from 2022-07-18 14-13-57](https://user-images.githubusercontent.com/99441266/179567728-9c027227-8c3f-40b3-b9be-209abf6a0e03.png)

**Comment by AlexRuiz7** [comment]
All tests have passed
