### ISSUE TITLE
Release 4.3.7 RC1 - Wazuh UI Manual Testing 

### ISSUE THREAD

**Issue by Mayons95** [wazuh/wazuh-splunk#1360]
# Wazuh v4.3.7

| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢/🔴  | 🟢/🔴 | 🟢/🔴    | 🟢/🔴  |
 
Status legend:
⚫ - None
🔴 - Rejected
🟢 - Approved

In the case of 🔴, create and link the issue. 

##  Scenarios to test:
1) Install the Wazuh app on Splunk
2) Set the connection to Wazuh API
3) Set the configuration to Wazuh Forwarder
4) Check that the charts are displayed.

### [1358](https://github.com/wazuh/wazuh-splunk/issues/1358) Broken suggestions in the API console
Given the user is in Wazuh Splunk App
And the user navigates to dev tools
And the user writes a part of a command (EX /get Agents)
And a list of suggestions should be displayed
And the user clicks a suggestion
Then the suggestion text is displayed on the query

**Comment by yenienserrano** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢 | ⚫  | 🟢    | wazuh_splunk-4.3.7_8.2.6-1  |

![image](https://user-images.githubusercontent.com/63758389/185101961-8baa92ef-de81-42b0-ab8e-01bb758316b9.png)

**Comment by asteriscos** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| Test 1 | 🟢 | ⚫  | 🟢    | wazuh_splunk-4.3.7_8.2.6-1  |

![Peek 2022-08-17 13-00](https://user-images.githubusercontent.com/9343732/185102892-110aa8f2-07a2-44d0-aecb-45de61149f4d.gif)

**Comment by asteriscos** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| https://github.com/wazuh/wazuh-splunk/issues/1358 | 🟢 | ⚫  | 🟢    | wazuh_splunk-4.3.7_8.1.7-1  |

![Peek 2022-08-17 13-18](https://user-images.githubusercontent.com/9343732/185105962-00786ceb-4979-4531-b47c-164c57819110.gif)

**Comment by yenienserrano** [comment]
| Test   | Chrome | Safari | Firefox | Package |
|--------|--------|--------|---------|---------|
| https://github.com/wazuh/wazuh-splunk/issues/1358 | 🟢 | ⚫  | 🟢    | wazuh_splunk-4.3.7_8.1.10-1  |

![image](https://user-images.githubusercontent.com/63758389/185106659-364f81f0-46f8-4130-bb05-216477887532.png)
