### ISSUE TITLE
Compatibility with Splunk 9.x

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-splunk#1363]
## Description

There is a new Splunk version released in the summer of 2022, Splunk 9. Currently, our application only supports 8.x versions. We will evaluate if we can support Splunk 9.x.

For that, we need to:

- [x] Review Splunk's latest stable changelog. 
- [x] Identify improvements and potential impact on the UI.
- [x] Develop a testing environment to verify our components would work under this new build.
- [x] Execute a regression test to detect additional problems.

[Splunk 9.0 Release Notes](https://docs.splunk.com/Documentation/Splunk/9.0.1/ReleaseNotes/MeetSplunk)

## Related issues:

- #1378

## Issues
-  _List here the detected issues_
- #1381

**Comment by yenienserrano** [comment]
The tests with the installation of Wazuh 4.3.9, it can be said that the app works correctly, I found an [error](https://github.com/wazuh/wazuh-splunk/issues/1381) that happens in previous versions of Splunk but does not break the application.

**Comment by yenienserrano** [comment]
I share evidence of wazuh working in Splunk 9.0.1:

### Screenshots:

<details>
<summary>Overview</summary>

![image](https://user-images.githubusercontent.com/63758389/198570978-0794678b-5011-4e65-9cbc-6a960d6bf34e.png)
</details>

<details>
<summary>Security events</summary>

![image](https://user-images.githubusercontent.com/63758389/198571464-2cc08e02-e324-4784-9e6e-2089fd9718ef.png)
</details>

<details>
<summary>FIM</summary>

without information
![image](https://user-images.githubusercontent.com/63758389/198572594-26fc4bdc-87a8-454a-a564-72801f187922.png)

with information
![image](https://user-images.githubusercontent.com/63758389/198576228-2452e3b7-aa79-472e-8b5d-eac69445ee7a.png)

</details>

<details>
<summary>Vulnerabilities</summary>

![image](https://user-images.githubusercontent.com/63758389/198576526-d2c38444-0082-4259-97c6-7d93d1b41f54.png)</details>

<details>
<summary>HIPAA</summary>

![image](https://user-images.githubusercontent.com/63758389/198576703-c719af01-2ef7-437b-b6eb-0411e1032afc.png)
</details>

<details>
<summary>Management</summary>

![image](https://user-images.githubusercontent.com/63758389/198576887-d05cace3-0dc3-43b9-876e-810e45b8b53e.png)</details>

<details>
<summary>Rules</summary>

![image](https://user-images.githubusercontent.com/63758389/198576984-9b07df83-cd3d-4a32-a228-2ecec5c6d94a.png)</details>

<details>
<summary>Agents</summary>

![image](https://user-images.githubusercontent.com/63758389/198577069-2fa93c5a-cc5d-4cdd-b381-bc832d95261a.png)</details>

<details>
<summary>Overview agent</summary>

![image](https://user-images.githubusercontent.com/63758389/198577142-fdf00067-7446-4cc0-ab0b-47f063afba5b.png)</details>

<details>
<summary>Dev tools</summary>

![image](https://user-images.githubusercontent.com/63758389/198577223-577897b7-5772-42d6-9094-293de31c615d.png)</details>

<details>
<summary>Security</summary>

![image](https://user-images.githubusercontent.com/63758389/198577290-1b67c054-ed4b-41f5-9c45-c31977fb110a.png)</details>

<details>
<summary>configuration/API</summary>

![image](https://user-images.githubusercontent.com/63758389/198577320-2d2215b3-f898-4258-bacd-60c79d39e403.png)
</details>

**Comment by Mayons95** [comment]
I connected a new agent for ubuntu 22.04, and also I enabled all the modules on the ossec.config file to check if all the Wazuh modules are working as expected.

<details>

[Screencast from 31-10-22 14:47:40.webm](https://user-images.githubusercontent.com/104914131/199079962-9b27a020-d34b-4ae7-9e18-ea7fdb7a5c49.webm)

[Screencast from 31-10-22 14:48:26.webm](https://user-images.githubusercontent.com/104914131/199079985-b13aecce-445b-4021-b096-f5f73ad48f9b.webm)

[Screencast from 31-10-22 14:50:40.webm](https://user-images.githubusercontent.com/104914131/199080022-537048c4-efe8-4b88-ace9-09f9f4c2d3b2.webm)

[Screencast from 31-10-22 14:51:58.webm](https://user-images.githubusercontent.com/104914131/199080093-c3898c39-2dc1-44c8-947f-53302275a5db.webm)

[Screencast from 31-10-22 14:53:48.webm](https://user-images.githubusercontent.com/104914131/199080141-fa745a7d-1128-4a4d-a097-a2b36f48f3c0.webm)






<details/>

**Comment by AlexRuiz7** [comment]
All checks have passed
