### ISSUE TITLE
Splunk has deprecated HTML dashboards. Wazuh app Dashboards migration to Splunk Dashboard Studio format 

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-splunk#1378]
Hello team,

I'm creating this issue because Splunk has deprecated HTML dashboards. Then, the Wazuh app Dashboards will be not compatible with next versions and they should be migrated to the Splunk Dashboard Studio format.

https://docs.splunk.com/Documentation/SplunkCloud/9.0.2208/DashStudio/DelApp?ref=hk#Migrate_your_dashboards_out_of_the_Splunk_Dashboards_app

Regards,

Miguel Casares

**Comment by gdiazlo** [comment]
@MiguelCasaresRobles we're closing this issue. Please review:
 - https://github.com/wazuh/wazuh-splunk/issues/1363
The app is working in Splunk 9 even though it is using a deprecated SDK.
