### ISSUE TITLE
Test the packages, to verify they install, and the app works as expected.

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-splunk#1385]
## Description

We'll track the effort to test the new version 4.3.10 of the Wazuh app for Splunk in this issue. Evidence will be provided for each individual Splunk version tested.

## Target versions

The new version of the Wazuh app will be tested in the following Splunk versions:

- [x] Splunk 8.2.8
- [x] Splunk 8.2.7.1
- [x] Splunk 8.2.6
- [x] Splunk 8.1.10
- [x] Splunk 8.1.7.2
- [x] Splunk 8.1.7.1
- [x] Splunk 8.1.6
- [x] Splunk 8.1.5
- [x] Splunk 8.1.4

**Comment by yenienserrano** [comment]
Splunk 8.2.8: ✔️ 
<details>

<summary>
Screenshots
</summary>

![image](https://user-images.githubusercontent.com/63758389/201714073-bf9c7de1-f41e-4e65-9fea-5684f673e1f4.png)

![image](https://user-images.githubusercontent.com/63758389/201713829-d0709963-2bc3-40cf-bd43-2872256c989c.png)
</details>

**Comment by yenienserrano** [comment]
Splunk 8.2.7.1: ✔️ 
<details>

<summary>
Screenshots
</summary>

![image](https://user-images.githubusercontent.com/63758389/201718433-7cb77254-c053-4e1b-997c-e784dab87356.png)

![image](https://user-images.githubusercontent.com/63758389/201718495-f5ac1f57-fe6f-49d7-bc20-854912dc1020.png)

![image](https://user-images.githubusercontent.com/63758389/201718548-59fb9049-8be1-4bd6-84f2-e8ba49837532.png)


</details>

**Comment by asteriscos** [comment]
<details>

<summary>
Splunk 8.1.7.1 :heavy_check_mark: 
</summary>

![Screenshot from 2022-11-14 18-38-02](https://user-images.githubusercontent.com/9343732/201733007-464b831a-66a6-4355-9bf5-c04d275caed5.png)

</details>

<details>

<summary>
Splunk 8.1.6 :heavy_check_mark: 
</summary>

![Screenshot from 2022-11-14 18-40-05](https://user-images.githubusercontent.com/9343732/201733204-fdd50b9b-2b0d-4053-927a-bb1021c5a401.png)

</details>

<details>

<summary>
Splunk 8.1.5
 :heavy_check_mark: 
</summary>

![Screenshot from 2022-11-14 18-48-52](https://user-images.githubusercontent.com/9343732/201733473-2ea5df8c-9379-4d6a-8797-47246ff25aac.png)

</details>

<details>

<summary>
Splunk 8.1.4 :heavy_check_mark: 
</summary>

![Screenshot from 2022-11-14 18-44-37](https://user-images.githubusercontent.com/9343732/201733303-d8d2f727-edf0-4813-8273-3ff1b44453ff.png)
![Screenshot from 2022-11-14 18-43-05](https://user-images.githubusercontent.com/9343732/201733312-b4ac4eeb-56f9-44bf-8bfb-ce781d1139f7.png)

</details>

**Comment by Mayons95** [comment]
Splunk 8.1.7.2 :heavy_check_mark: 
<details>

![Screenshot from 2022-11-14 16-20-28](https://user-images.githubusercontent.com/104914131/201747128-5990d55b-52f1-451e-900d-f915b3646f17.png)

![Screenshot from 2022-11-14 16-19-45](https://user-images.githubusercontent.com/104914131/201747137-083dc0f5-ab87-4b1c-a2cc-f6416670a9b2.png)


</details>

**Comment by Mayons95** [comment]
Splunk 8.1.7.2 :heavy_check_mark: 
<details>

![Screenshot from 2022-11-14 16-53-01](https://user-images.githubusercontent.com/104914131/201753084-b2ffebe2-8fd7-4b6d-8631-1d98b959f63f.png)



</details>

**Comment by AlexRuiz7** [comment]
All tests passed without problems.
