### ISSUE TITLE
Unimplemented method `setReportMetrics`

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-splunk#1389]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 4.4.0-alpha-2   | 8.2.X     | 4400 |

## Description
Checking the agent's security events this warning is raised (together with other warnings that are shown in the entire app) 

## Steps to reproduce

1. Go to the agents page
2. Choose an Agent and click it
3. Open the Security Events module

## Screenshots
![task-4-splunk-agent-security-events](https://user-images.githubusercontent.com/44633633/209682580-bca5a7b9-91bd-433d-a905-27802adc7d0d.png)

**Comment by AlexRuiz7** [comment]
That log is intentional and expected
