### ISSUE TITLE
Agent Summary Page Error

### ISSUE THREAD

**Issue by Justangatang** [wazuh/wazuh-splunk#197]
Hello,

I'm running a test lab with the latest version of Splunk/Wazuh app and Wazuh Manager, and currently having an issue in the Splunk Wazuh App when pressing on Agents/Summary. (Pic Attached)

Error reported in Browser:
Error: Error from backend:'data'
(Tested with Chrome, IE, and Firefox)

![image](https://user-images.githubusercontent.com/41699624/44161126-05e6bb00-a082-11e8-8c61-63fa3fb375eb.png)

In the Wazuh Manager Server, api.log files I can see multiple requests sent from Splunk. Under the requests below are the responses (manually tested). It looks like GET /agents/?limit=0 is causing the issue, and if I add a higher limit to the manual test it comes back with data. Because of the error in Splunk I'm not able to do anything in the Agents/Summary Page.

```
GET /cluster/status - 200 - error: '0'.
{"error":0,"data":{"running":"no","enabled":"no"}}

GET /agents/000 - 200 - error: '0'.
{"error":0,"data":{"status":"Active","name":"NEW-WAZUHMANAGER","ip":"127.0.0.1","dateAdd":"2018-08-13 16:09:46","version":"Wazuh v3.5.0","manager_host":"NEW-WAZUHMANAGER","lastKeepAlive":"9999-12-31 23:59:59","os":{"major":"16","name":"Ubuntu","platform":"ubuntu","uname":"Linux |NEW-WAZUHMANAGER |4.13.0-36-generic |#40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 |x86_64","version":"16.04.4 LTS","codename":"Xenial Xerus","arch":"x86_64","minor":"04"},"id":"000"}}

GET /agents/?limit=1&offset=0&search=%22%22&sort=-dateAdd&os.platform=all&version=all&status=all - 200 - error: '0'.
{"error":0,"data":{"totalItems":6,"items":[{"status":"Active","configSum":"3bf07cc6dbf0d657613a3c2dcf810622","group":"default","name":"Debian-Agent","mergedSum":"4627ce0a47ec543d1339b5c75aea18c8","ip":"any","node_name":"node01","dateAdd":"2018-08-14 09:40:29","version":"Wazuh v3.5.0","key":"fc5dcd282ee8e079959d4e54c1ade9d9a2e5f2fc76e433e20be359f5cd7433b8","manager_host":"NEW-WAZUHMANAGER","lastKeepAlive":"2018-08-15 11:40:43","os":{"major":"8","name":"Debian GNU/Linux","uname":"Linux |Debian-Agent |3.16.0-6-amd64 |#1 SMP Debian 3.16.57-2 (2018-07-14) |x86_64","platform":"debian","version":"8","codename":"jessie","arch":"x86_64"},"id":"005"}]}}

GET /agents/summary - 200 - error: '0'.
{"error":604,"message":"Filter error. Allowed filters: [ offset  limit  sort  select  search  status  os.platform  os.version  manager  version  node  older_than  group ]  "}

GET /agents/?limit=0 - 200 - error: '1406'.
{"error":1406,"message":"0 is not a valid limit."}

GET /rootcheck/005/last_scan - 200 - error: '0'.
{"error":0,"data":{"start":"2018-08-15 09:23:22","end":"2018-08-15 09:23:50"}}

GET /syscheck/005/last_scan - 200 - error: '0'.
{"error":0,"data":{"start":"2018-08-15 09:22:16","end":"2018-08-15 09:23:12"}}
```

**Comment by manuasir** [comment]
Hi @Justangatang,

Thank you for your well-detailed report.
I've just fixed the issue and the commit will be merged soon.  I'll let you know when it's ready for deploying it and I will tell you about the necessary steps for applying the update, if you need it.
Sorry for the inconveniences.

Best regards

**Comment by manuasir** [comment]
Hi again @Justangatang 

You can follow these steps in order to apply the fix:

Download the latest [release](https://github.com/wazuh/wazuh-splunk/releases/tag/v3.5.0-7.1.2) from the repository section:
```
wget https://github.com/wazuh/wazuh-splunk/releases/download/v3.5.0-7.1.2/v3.5.0_7.1.2.tar.gz
```
Stop the Splunk service:
```
# $SPLUNK_HOME/bin/splunk stop
```
Remove the previous Splunk app for Wazuh:
```
# $SPLUNK_HOME/bin/splunk remove app SplunkAppForWazuh
```
Install the previously downloaded latest Splunk app for Wazuh:
```
# $SPLUNK_HOME/bin/splunk install app v3.5.0-7.1.2.tar.gz
```
Startthe Splunk service:
```
# $SPLUNK_HOME/bin/splunk start
```
Notice that any index will be deleted or modify along this process, also remember that $SPLUNK_HOME is a reference to your Splunk base directory, by default /opt/splunk/. Change it in accordance with your installation if changed.
I'd like to thank you again for your report and  do not hesitate to open another issue whenever you may need it.

Regards,
Manu
