### ISSUE TITLE
Implement Dev-Tools

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#217]
Hi, it'd be great if the app had a Dev Tools section where the server side endpoints could be tested easily and fast, following the Wazuh Kibana app functionality.

**Comment by havidarou** [comment]
Maybe @jesusgn90 can help here.

**Comment by jesusgn90** [comment]
@manuasir take a look into https://github.com/wazuh/wazuh-kibana-app/pull/871/commits/1c972c90bbb48b92b84a721ddec8c1dd8d12ecfd (white line fix)
