### ISSUE TITLE
Connecting to Multiple Managers

### ISSUE THREAD

**Issue by aslap5** [wazuh/wazuh-splunk#24]
We've started to use Wazuh in a distributed environment.  Initially we installed a manager and agents at a single location.  We're now wanting to roll it out to other locations but keep logging centralized to our one splunk instance.  Will things work correctly if we have the Splunk app connect to multiple standalone managers?

I've attached a rough drawing to display what I'm talking about.
![drawing2](https://user-images.githubusercontent.com/34276357/38577718-5774ef24-3cc7-11e8-9e8b-a478df44515a.jpg)

**Comment by manuasir** [comment]
This issue is being developed [in this branch](https://github.com/wazuh/wazuh-splunk/tree/3.2-dev-multi-manager).

**Comment by manuasir** [comment]
This issue was done in [#79](https://github.com/wazuh/wazuh-splunk/pull/79/) and is going to be tested.

**Comment by manuasir** [comment]
Hi @aslap5 ,
this feature is now available in our last [v3.2.4-7.1.1](https://github.com/wazuh/wazuh-splunk/releases/tag/v3.2.4-7.1.1) release. I'd like to thank you for your interest and let you know that any feedback from you will be appreciated.

Best regards,
Manu
