### ISSUE TITLE
Undefined fields for agent never connected

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh-splunk#280]
At Splunk, the data of an agent which has never been connected to the manager shows that its OS information is set to 'undefined' three times, this should display an '-' instead of that word.
```
Name: rhel7
IP: any
OS: undefined undefined undefined
```

**Comment by manuasir** [comment]
Done here https://github.com/wazuh/wazuh-splunk/pull/282. Thanks @cristgl :smiley_cat:
