### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#312]
Hi, this feature is very interesting. It's about exporting metrics as reports in PDF format, having visualizations and valuable information on it.
This huge issue should have the following tasks:

### Iteration 1 (49th week sprint):

- [x] Create a new HTML section for this.
- [x] Include third-party libraries in AngularJS using RequireJS.
- [x] Backend: add a third-party library for handling PDF files.
- [x] Implement new AngularJS controller.
- [x] Implement a new service for creating reports from controllers.
- [x] Add ui.router state.
- [x] Backend: capacity of creating and storing PDF files.
- [x] Obtain the rendered DOM and send it to the backend.
- [x] Write rendered DOM into a PDF file.

https://github.com/wazuh/wazuh-splunk/pull/401

### Iteration 2 (50th week sprint):

- [x] Replicate Kibana reporting feature

**Comment by adri9valle** [comment]
Solved => https://github.com/wazuh/wazuh-splunk/pull/424
