### ISSUE TITLE
Wrong Management button highlight

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#332]
I just realized that the `Management` button doesn't shine properly when clicking on it.

**Comment by manuasir** [comment]
Hey @adri9valle, I just realized that a few casuistics are still provoking unexpected behavior.
For example:
- Being in `Management > Monitoring` section -> then I click on the `agents` list of each node, the app redirects me to `Agents` section but the `Management` button of the top menu bar is still highlighted.

**Comment by adri9valle** [comment]
> Hey @adri9valle, I just realized that a few casuistics are still provoking unexpected behavior.
> For example:
> 
> * Being in `Management > Monitoring` section -> then I click on the `agents` list of each node, the app redirects me to `Agents` section but the `Management` button of the top menu bar is still highlighted.

Hi @manuasir  this PR solved this problem => https://github.com/wazuh/wazuh-splunk/pull/365

**Comment by manuasir** [comment]
Thanks, @adri9valle. This fix will be tested soon. Meanwhile, this issue will be closed.
