### ISSUE TITLE
Agents status monitoring doesn't draw timeline properly

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#350]
Hi, 

I just realized that this feature is not working as expected:
- The backend Python script is working great, it indeed performs requests to agents and indexes the data correctly.
- The visualization needs some tweaking, the timeline is not currently showing actual data.

Regards

**Comment by adri9valle** [comment]
Fixed in this commit => https://github.com/wazuh/wazuh-splunk/commit/b279ff5922f7745db8fe08c9931c388649e5100c
