### ISSUE TITLE
Amazon AWS tab rework

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#385]
Improve our current Amazon AWS extension to include:

- [x] Service name selector, using native Splunk selector visualization. This modifies the filters depending on the selected service.
- [x] Show the accounts in use.
- [x] Show active rules in AWS config (regions and accounts).
- [x] Add/Modify visualizations
- [x] Fully test this tab including the data flow, Splunk...
- [x] Use `data.aws.service.action.networkConnectionAction.remoteIpDetails.geoLocation`

Regards,

**Comment by adri9valle** [comment]
Solved => https://github.com/wazuh/wazuh-splunk/pull/407
