### ISSUE TITLE
Check API connection removes the yellow star icon on Settings

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-splunk#415]
Hi team,

If we click on check connection for the currently selected API, the yellow star icon (which indicates that this is the current API) disappears.
![splunk](https://user-images.githubusercontent.com/10928321/49855519-cb055180-fded-11e8-8748-c73e3dd3438d.png)

This happened with the latest Wazuh app for Splunk (3.7.1-7.2.1).

Regards,
Juanjo

**Comment by adri9valle** [comment]
Fixed => https://github.com/wazuh/wazuh-splunk/pull/425
