### ISSUE TITLE
Reporting iterations

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#431]
Hi, the reporting section of the Splunk app for Wazuh should have the following features, following the Kibana app functionalities:

- [x] Use the reporting service in all `Overview` and `Agents` dashboards.
- [x] Use custom section title.
- [x] Fix error when a second PDF is generated.
- [x] Fix visualization injection from the previous PDF.
- [x] Refresh button doesn't work in reporting controller.
- [x] Improve report id name.
- [x] Implement metrics.
- [x] Wait until visualizations are loaded.
- [x] Rescale images programmatically.
- [x] Get data from tables and render them in a pretty format.
- [x] Content of reports change in function of the selected.
- [x] Include timestamps in PDF metrics.
- [x] Improve styles.
- [x] Copyright at the bottom of each page.
- [x] Implement new features of reporting service in all `Overview` and `Agents` dashboards.

**Comment by adri9valle** [comment]
Solved => https://github.com/wazuh/wazuh-splunk/pull/446
