### ISSUE TITLE
Refactor of reporting methods along the controllers

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#458]
There are coupling issues between the reporting service and the controllers, due to the are methods that are implemented over the controllers that reference to the reporting service, and they're not implemented on that service.

- [x] Take off the logic of the dashboard controllers.
- [x] Set the logic into a service.
- [x] Test the reporting service.

Cheers

**Comment by adri9valle** [comment]
Solved => https://github.com/wazuh/wazuh-splunk/pull/504
