### ISSUE TITLE
Secure Wazuh API (HTTPS)

### ISSUE THREAD

**Issue by DMHS** [wazuh/wazuh-splunk#46]
The wazuh-splunk app does not connect to the Wazuh API when the Wazuh API is secured with HTTPS with a self-signed cert using [this guide](https://documentation.wazuh.com/current/installation-guide/optional-configurations/securing-api.html).

It works when using HTTP for the Wazuh API.

**Comment by manuasir** [comment]
Hi @DMHS , 

Thank you for your report, this is a known issue and it's been planified to be included in the next app release. So I'm tagging and import this to the repo project kanban in order to you can check the progress. Anyway I will let you know when it's ready.

Regards,
Manu

**Comment by DMHS** [comment]
Thank you.

**Comment by manuasir** [comment]
Hi @DMHS ,

I wanted you to know that this issue is fixed in the already available [v3.2.2 release](https://github.com/wazuh/wazuh-splunk/releases/tag/v3.2.2) for Splunk 7.1.0. Please, don't hesitate to open a new issue about anything you may need.

Regards,
Manu
