### ISSUE TITLE
Distribute local API database in a Search Head cluster architecture

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#473]
It's been reported that the API entries have to be inserted one by one on each node in a Search Head cluster architecture. So, it'd be necessary to implement a way to broadcast the API database to the rest of the nodes automatically.

Cheers

**Comment by adri9valle** [comment]
Hi, 

With the new way to save the APIs using the Splunk kvStore is no necessary to implements nothing more because once search head cluster is enabled the kvStore data will be automatically replicated to the search head cluster members.

Regards,
