### ISSUE TITLE
Splunk 7.1 Errors

### ISSUE THREAD

**Issue by suryjuto** [wazuh/wazuh-splunk#48]
Errors are encountered post-upgrade to Splunk 7.1.0.  

**Manager > Ruleset**
`DataTables warning: table id=myTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

**Manager > Configuration** does not load correctly.  No errors.

**Manager > Decoders**
`DataTables warning: table id=myTable - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

Similar errors on **Manager > Logs** and **Manager > Groups**

**Comment by manuasir** [comment]
Hello @suryjuto ,

It seems like an API configuration related issue. Could you please navigate to Configuration -> API and check the connectivity status? You should observe a green light at the bottom of the dashboard. If it isn't green but red, you can press 'Clear' button in 'Remove credentials' section and then fill the API data again.
If it didn't work, please proceed to clean the browser cache and navigation data, after the upgrading process the browser is maybe storing old data from Splunk previous version. For doing that please follow these steps:
- Chrome:
 1. Press F12
 2. Inside Chrome Developer Tools navigate to > Application tab > Clear storage in left tree > Select the data items to clear, then click Clear site data.
- Firefox:
 1. Navigate to Menu button on the upper right corner-> Options -> Privacy and Security -> Manage data -> Choose Splunk website -> Delete selected
Thank you for your report, I'm awaiting for your feedback.

Regards,
Manu

**Comment by suryjuto** [comment]
Thanks for getting back to me so fast, Manu!

I confirmed that the API status is red.  I did notice, however, that the legacy TA-wazuh_api_connector was still installed.  I removed that and restarted Splunk.  No change.  I've also cleared the storage and such as you requested.  No change.

I have uninstalled all instances of Wazuh, downloaded the latest package and installed and still have the same issue.

**Comment by manuasir** [comment]
Hi again @suryjuto ,

The red light in Configuration API means that there's not connectivity with Wazuh API, so let's check a few things:
- Fist, could you try to _curl_ the Wazuh API from your Splunk machine? 
 1. Open a terminal in your Splunk machine
 2. Execute the following command:
     ```
     curl http://foo:bar@<IP-wazuh-API>:55000
     ```
     -  Supossing the API is not securized and using default credentials
     - The curl should return a welcome message from the API
     - This could help to know if the source of your problem you're facing is related to Wazuh API,not Splunk app.
     
- Also please, could you show me the data you're filling the API Configuration fields with? Maybe you're filling them in a wrong way. Please use the following formats:
    - *IP*: Example 10.0.0.50. Rememeber not including any http or https protocol, the last released version of the app only support http
    - *Port*: by default '55000'
    - *Username*: by default 'foo'
    - *Password*: by default 'bar'

I'm awaiting for your feedback.

Regards,
Manu

**Comment by suryjuto** [comment]
Much happier, Manu.

Looks like it did not like the special characters in my API password.  I
reset the password to something less secure and it seemed to work just fine.

**Comment by manuasir** [comment]
Hi @suryjuto ,

I'd like to thank you for your patience and your report, this will be very helpful for other users in the future for sure. Proper field validation will be included in next versions of the app along with other fixes and improvements. As you may note, Splunk 7.1 update changes some styles so some visual changes over the app are upcoming too.
Please keep a close eye to next releases and don't hesitate to open a new issue whenever you need it.

Regards,
Manu
