### ISSUE TITLE
Configuration assessment

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#491]
We need to add on each agent the next capabilities:

- [x] Add the ability to navigate through the configuration assessment policies
- [x] Add "Run scan" 
- [x] Each policy must be clickable, then we show all the checks

**Comment by jesusgn90** [comment]
Check this ticket https://github.com/wazuh/wazuh-api/issues/289#issuecomment-459002973 team!

**Comment by adri9valle** [comment]
Working on this branch => [3.9-491](https://github.com/wazuh/wazuh-splunk/tree/3.9-491)

- `Changed`: Switch between alerts and policies.
- `Added`: Show a table with the policies.

**Comment by adri9valle** [comment]
- `Added`: Get checks of policy monitoring(stall, waiting for a correct API response)

**Comment by adri9valle** [comment]
- `Added`:  Add the ability to navigate through the configuration assessment policies

**Comment by adri9valle** [comment]
`Pending-core`: When it finish would be necessary to make a few changes in `dataService.js`
