### ISSUE TITLE
Edit manager configuration - 1st iteration - single node

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#492]
Tasks:

- [x] Create specific tab under Management 
- [x] Use the editor directive we've already made for `agent.conf`
- [x] Only allowed if admin mode is enabled
- [x] Manager

**Comment by adri9valle** [comment]
Working on this branch => [3.9-edit-config](https://github.com/wazuh/wazuh-splunk/tree/3.9-edit-conf)

**Comment by adri9valle** [comment]
- `Added`: If the cluster is disabled open the manager ossec.conf file directly
- `Changed`: Table to dropdown and open directly the ossec.conf in cluster mode
