### ISSUE TITLE
Edit local rules/decoders

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#493]
Tasks:

- [x] Create specific tab under Management > Ruleset
- [x] Use the editor directive we've already made for `agent.conf`
- [x] Just edit local rules/decoders
- [x] Only allowed if admin mode is enabled
- [x] Implement edit of CDB lists
- [x] API calls
- [x] Change the UI to adapt it to these new sections

Reference:
- https://documentation.wazuh.com/current/user-manual/ruleset/custom.html

**Comment by adri9valle** [comment]
Solved => https://github.com/wazuh/wazuh-splunk/pull/501

**Comment by adri9valle** [comment]
Working on this branch => [3.9-edit-config](https://github.com/wazuh/wazuh-splunk/tree/3.9-edit-conf)

**Comment by adri9valle** [comment]
Implemented these new functionalities today,(pending testing) :
	- Add pagination to CDB lists content(Ruleset and Management section).
	- Remove button to filter by local rules/decoders.
	- Add navigation to parent states in the breadcrumb.
	- Add rules/decoders file from Management > Configuration.

**Comment by adri9valle** [comment]
- `Fix`: Caughts error when try to fetch CDB List content and fails in Managemente > Configuration > Ruleset > CDB Lists
- `Added`: Filter bar to CDB lists in Managemente > Configuration > Ruleset > CDB Lists
- `Added`: Filter the content of the CDB list
- `Added`: Add new CDB list file in Managemente > Configuration > Ruleset > CDB Lists
