### ISSUE TITLE
Store the API database into a Splunk service

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#514]
Hi, in order to get rid of the API database in a search head cluster, the entries must be stored on a service provided by Splunk itself, like a new `index` or making use of the `KV store`.

- [x] Communicate the app's backend with an index without writing credentials.
- [x] Communicate the app's backend with KVstore service without writing credentials.
- [x] Evaluate both options and chose one.
- [x] Write to an index without using credentials from backend.
- [x] Research how to distribute the new storage to every search head instance in a cluster.

Cheers

**Comment by manuasir** [comment]
The main idea of this issue is about completely migrating the current API local database to a distributed KVstore database along with every node. This new architecture allows the app to work properly under Search Head clusters so the user is not required to manually enter API credentials on each node.

The first issue that we faced was the need of requesting to the Splunk REST API from the Python backend _without_ writing any credentials in plaintext on the `.splunkrc` file, because that would force the users to perform that step before using the app, and the expected behavior about this app is just to be installed and used without any additional step.

This task was already solved. After researching, the proceeding was about importing the `splunk` internal Python libraries, (**not** the `splunklib` that the documentation refers to), and in order to keep the same session credentials, this method was discovered within the source code: 

```
import splunk
from splunk import entity, rest
self.sessionKey = splunk.getSessionKey()
```

So, having the `session key` it's possible to perform requests to the Splunk REST API like this:

```
self.kvstoreUri = entity.buildEndpoint(
            entityClass=["storage", "collections", "data"],
            entityName="credentials",
            owner="nobody",
            namespace="SplunkAppForWazuh",
            hostPath=rest.makeSplunkdUri().strip("/")
        )
```
And then adding headers:

```
self.session.post(kvstoreUri, data=obj, headers={"Authorization": "Splunk %s" % splunk.getSessionKey(), "Content-Type": "application/json"}, verify=False).json()
```

For the next steps, it will be needed to completely rewrite the `database` module and the `CRUD` methods.

**Comment by manuasir** [comment]
After rewriting the back-end `db` module, the `CRUD` methods were reimplemented in order to use the new distributed KVstore Splunk service.
The current state of this task is, the full front-end logic is being rewritten so the performance will be much improved, due to several methods had redundant functionalities and also were performing more requests than they need to. Additionally, parallelization is being implemented in the requests so the speedup has been increased.

**Comment by adri9valle** [comment]
- `Fixed` API check connection
- `Fixed` Can delete an API
- `Fixed` Set key when adding API
- `Fixed` Set yellow star after select new manager

**Comment by adri9valle** [comment]
- `Fixed`: Change filterType when cluster is enabled or disabled
- `Added`: Set as default when addiing the first API entry
- `Fixed`: When checking connection the first entry was selected
