### ISSUE TITLE
UI improvements in Groups dashboard

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#515]
Hi, it'd be needed to implement several UX improvements in `Management > Groups` configuration:

- [ ] Avoid button flicker when changing section.
- [x] Adapt `back` button to the groups table.

Cheers

**Comment by manuasir** [comment]
The button still flickering when changing between both tabs. It'd be needed to research what's going on there because the `ng-cloak` nor the forced `diggest` didn't solve the issue.

**Comment by jesusgn90** [comment]
Included in #657
