### ISSUE TITLE
Edit manager configuration - 2nd iteration - cluster

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#524]
First iteration was https://github.com/wazuh/wazuh-splunk/issues/492

Tasks:

- [x] Cluster 
  - [x] Master
  - [x] Worker

**Comment by adri9valle** [comment]
Working on this branch => [3.9-edit-cluster-confg](https://github.com/wazuh/wazuh-splunk/tree/3.9-edit-cluster-config)
