### ISSUE TITLE
Add a way to expand specific visualization to full screen mode

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#540]
Every dashboard has a few visualizations. Sometimes, the user sets a large time range so our visualizations show all data in a small rectangle, the idea behind this issue is to add an option to expand specific visualization to full-screen mode so the user can see the data in a more human way. 

Tasks:

- [x] Overview
- [x] Agents
- [x] Cluster

**Comment by pablotr9** [comment]
working on this branch https://github.com/wazuh/wazuh-splunk/tree/3.9-fixstyling
