### ISSUE TITLE
Not to use scroll in a container when it could fill the windows height

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#542]
Hi team,

It would be great if any container could fill the height of the window and not have to use a scrolling bar if it is not needed.

e.g.:

![image](https://user-images.githubusercontent.com/21195730/52475820-0da09b80-2b9d-11e9-9304-fcf7fa45274f.png)

Regards

**Comment by pablotr9** [comment]
working on https://github.com/wazuh/wazuh-splunk/tree/issue-542
-The style of all containers in the configuration tab  now fit the windows' height and are just scrollable if needed
