### ISSUE TITLE
Standard test battery - Testing 3.9.0

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#543]
# Wazuh App test

__Minimum checks for any Wazuh app. Add extra checks depending on the new features for this version.__

#### API management checks

- [x] Acces to Splunk without any API saved
  - [x] Should take you to Settings and warn you there are no API credentials available
  - [x] If it's a clean install, should appear "No API" on the top right corner
  - [x] Should appear the index on the top right corner
  - [x] The extensions tab should be disabled
- [x] Filling "Add API" form badly once per every form field. Should appear the appropriate error message for every wrong inserted form field 
- [x] Filling "Add API" form correctly Should connect successfully and show the data in the upper right corner
- [x] Check manager button right after inserting API credentials. Should success and not modify anything on the fields
- [x] Check the currently active extensions. Should be the same as the config.conf file
- [x] Insert a new API and check everyone with the Check button Should not change the currently selected API
- [x] Edit an API entry. The API is edited properly
- [x] Press F5 to reload the page. Should reload properly the currently active tab (Settings)
- [x] Go to a new tab (Management). After the health check should open the selected tab
- [x] Delete all the existing APIs 
  - [x] The extensions tab should be disabled
  - [x] **FIXED** The top menu bar should be updated indicating that there's no API selected 

#### Basic functions checks (Overview and Agents)   

- [x] Click in Overview/Agents tab and select a proper time range
  - [x] **FIXED** Should appear a loading bar and disappear after finishing loading 
  - [x] Data should appear if there are alerts
  - [x] Visualizations should appear correctly without errors
- [x] Click Overview/Agent -> Discover subtab. Should appear the selected index only
- [x] Go to Dashboard subtab and activate a filter. The filter should be working
- [x] Go again to Discover subtab. The filter should be still working and appear as a chip
- [x] Go back to Dashboard and remove the filter. The visualizations should reload properly after deleting the filter
- [x] Press F5 to reload the page. The filters shouldn't keep applied unless they're pinned
- [x] Click several times the app buttons and tabs while you're on the same tab
  - [x] Filters should persist and not disappear
  - [x] The visualizations watchers should not lose data
- [x] Search something on the search bar, press Enter, remove the content and press Enter again. Should always perform correctly the search and change the visualizations accordingly.
- [x] Go to Settings and select different extensions, and then go back to Overview/Agents. The extensions configuration should keep on Overview.
- [x] Go to Settings, select a different API with different extensions and go back to Overview/Agents. Should keep its own configuration between API selections
- [x] Disable all the extensions, go to General and go back to Settings. The extensions should not be restored on any of the inserted APIs
- [x] Type something and press Enter on the different Discover search bars. After pressing Enter, the search should start
- [x] Go to Manager/Reporting prior to generating any report. Should appear a card about no reports available yet
- [x] Click on the Report button on different tabs on Overview/Agents. After a wait, a new report should appear on Manager/Reporting
- [x] Download a report on Management/Reporting
  - [x] The report should be downloaded successfully
  - [x] The report has to be related to the tab where it was generated
  - [x] The report visualizations shouldn't have scrollbars
- [x] From the Welcome screen, go to General, go back to Welcome and open again the General tab. The tab should reload properly after coming from Welcome
- [x] Go from General to Welcome, then VirusTotal, then to Welcome, and then go again to General. Visualizations should load properly if there's actual data to show
- [x] Enable the cluster on the Manager and open the app again. The app should load properly without errors
 - [x] The Overview/Agents tabs should work properly with the "cluster.name" filter enabled
- [x] Add a simple filter and go to Discover, then back to Dashboard. The new filter should not be moved to the first position on the filter list

#### Filter checks (Overview and Agents)    

- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Discover" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/General/Discover" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists
- [x] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Discover -> Add `rule.level:7` -> Go to Overview/General/Dashboard" Filters shouldn't change
- [x] "Overview/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Dashboard" The filter "rule.level:7" is removed
- [x] "Overview/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Dashboard" The filter "rule.level:7" persists
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/General/Discover" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/General/Discover" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" persists
- [x] Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/FIM/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Discover -> Add `rule.level:7` -> Go to Agents/General/Dashboard" Filters shouldn't change
- [x] "Agents/General/Dashboard -> Add `rule.level:7` -> Go to Overview/General/Dashboard" The filter "rule.level:7" is removed
- [x] "Agents/General/Dashboard -> Add `rule.level:7` and make it pinned -> Go to Overview/FIM/Dashboard" The filter "rule.level:7" persists

#### Index pattern checks  

- [x] Go to the Settings -> Index tab Should not appear an incompatible index
- [x] Go to Overview/Agents Visualizations should still show data
- [x] Go to Discover subtab The index that you selected should be present on Discover
- [x] Change to a previous index with the selector or in the Settings -> Pattern tab Should change successfully
- [x] Go to Discover subtab The selected index pattern should appear

#### Management tab checks   

- [x] Go to Management/Status. The current Wazuh Manager version should be the same version as the installed with the current selected API 
- [x] Go to Management/Ruleset
 - [x] The Rules table should work properly (pagination, sorting, etc.)
 - [x] The Decoders table should work properly (pagination, sorting, etc.)
 - [x] The search should work correctly applying different filters
 - [x] On Ruleset, open a rule or decoder and click on the filters Should take you back to the list and apply the filter properly
 - [x] Remove the applied rule or decoder filter Should update the table and not apply the filter indeed
- [x] Go to Management/Groups
 - [x] Searching agents, click agents and files should work correctly
 - [x] **FIXED** All the tables from the tab (agents, files, groups) should work properly (pagination, sorting, etc.)
 - [x] Edit group configuration
 - [x] Create/remove a group
 - [x] Add/remove agents
- [x] Go to Management/Logs
 - [x] The Logs table should work properly (pagination, sorting, etc.)
 - [x] The search should work correctly
 - [x] The "Play real-time" button should work properly and update the table every few seconds
- [x] Go to Management/Monitoring without cluster
 - [x] Should appear a warning about not having the cluster-enabled, and don't show anything else
 - [x] Enable the cluster and go back again to Monitoring. Should appear the main Monitoring tab with visualizations and cluster data
 - [x] Navigate through the different Monitoring tabs Everything should work properly

#### Agents tab checks    

- [x] Go to Agents Preview The agent's table should work properly (pagination, sorting, etc.)
- [x] Check the different filters (node, agent version, OS, etc) All the filters should work properly and show the correct information
- [x] Disable the cluster and check the node filter It should not appear along with the other filters since the cluster is disabled
- [x] Go to a single agent The scrolling search bar from the upper right corner should work properly
- [x] Reload (F5) the page while on the Configuration tab The agent name, ID and status should be reloaded again
- [x] Reload (F5) the page while on the Inventory tab Everything should work properly and the tab should appear
- [x] Add some agent group configuration to the default group.  The Configuration tab in Agents should say SYNCHRONIZED

#### Miscellaneous checks  

- [x] "Insert a secured API in Settings and check it
(/var/ossec/api/scrips/configure_api.sh)" Should connect successfully, and not fail the form when inserting it
- [x] "Cat the logs file
(/usr/share/kibana/plugins/wazuh-logs/wazuhapp.log)" The file should be registering the logs, for example after restarting Kibana
- [x] The last 20 logs should appear con Settings > Logs
- [x] Download some tables using the CSV formatted button Should work properly and download a file to your computer 
- [x] The max amount of data that should download is 45k entries, even if there's more data to download
- [x] Open the Settings > Logs tab It should load the logs properly
- [x] If you click on the refresh button, it should reload them properly

**Comment by adri9valle** [comment]
23.04.19
------------

- Filling "Add API" form badly once per every form field. Should appear the appropriate error message for every wrong inserted form field https://github.com/wazuh/wazuh-splunk/pull/668/commits/c61965066a7d3257058c87e3f96ee5e62116450c

**Comment by pablotr9** [comment]
**Update**
- Avoid flicks when buttons are pressed and correct styles in Management -> Logs. https://github.com/wazuh/wazuh-splunk/commit/c54a29a82d873cb6a7fe6c5388a268c88c12277b
- Fix Management -> Cluster styling. https://github.com/wazuh/wazuh-splunk/commit/6a355637ccb5be6a275a927be82993bb564a600c

**Comment by adri9valle** [comment]
###### 23.04.19 

- Should appear a loading bar and disappear after finishing loading  https://github.com/wazuh/wazuh-splunk/pull/668/commits/08c18467302be06bc029f5b42ce8e093d5709c73 https://github.com/wazuh/wazuh-splunk/pull/668/commits/3f036c136907b76b4ee7c83743faa9c6e743ae8b https://github.com/wazuh/wazuh-splunk/pull/668/commits/da54d5c8fe869563a2e598a312957e009eb5c7f2 https://github.com/wazuh/wazuh-splunk/pull/668/commits/caeda7f77dfd838854c3f6e7c74993c7ee6aaf74 https://github.com/wazuh/wazuh-splunk/pull/668/commits/fe9b2619a2ed4d49cd2875eac37a22bb642bda52 https://github.com/wazuh/wazuh-splunk/pull/668/commits/10a7b6eddd6cc9949456deb86b955c0a36407589 https://github.com/wazuh/wazuh-splunk/pull/668/commits/da9159a194741ddb32a5b62a50e2ac22d833259b https://github.com/wazuh/wazuh-splunk/pull/668/commits/5a038d26b0115f84c2d932fb32c65b2c445e3c05

**Comment by pablotr9** [comment]
**Update**
- Fix Osquery error when loading visualizations https://github.com/wazuh/wazuh-splunk/commit/bac190acb14df7cc7fe045e2b6dd23d7039b6c8b  https://github.com/wazuh/wazuh-splunk/commit/1f41fa3447b01a70bdc083937cee79abb750475a
- Remove button flicks rules & decoders https://github.com/wazuh/wazuh-splunk/commit/ca8901c26f6d99e7993cd7bd6b21c931bdcabf10
- Fix filter bar at rules tab https://github.com/wazuh/wazuh-splunk/commit/f49995ea9644abcdb00a81ccb9170ebd50931060
- Update Overview->SCA dashboard https://github.com/wazuh/wazuh-splunk/commit/195606463fbc0471f0555c427a0bf209e5b0b80e
