### ISSUE TITLE
Restart agent from the App

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#549]
Hi team,

It's necessary to add a button on the overview of an agent to restart it.

- [x] Add button in the overview section.
- [x] Disable button until getting the API response.
- [x] Check response was ok.

Regards,

**Comment by pablotr9** [comment]
Working on this branch https://github.com/wazuh/wazuh-splunk/tree/issue-549

**Comment by adri9valle** [comment]
- `Fixed`: Check if the agent could be restarted
