### ISSUE TITLE
More UI/UX improvements for 3.9.0

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#571]
**Configuration assessment** **(@adri9valle & @pablotr9)**

- [x] Rule group now is `sca`(@adri9valle)
- [x] Wazuh API related endpoints have been changed from `/configuration-assessment/` to `/sca/`(@pablotr9)
- [x] Reduce column size for last four columns in the policies list from `sca`, title and description should be enough big to be human readable.
- [x] Improve expandable box for check details under a specific policy.(@adri9valle)
- [x] Replace "Lorem ipsum" from `sca` in the agents' welcome view with a meaningful text.
- [x] Add `dynamic columns` feature for checks table under a specific policy.(@pablotr9)
- [x] Replace `sca` visualizations with some more meaningful visualizations.(@pablotr9)

**Dashboards**

- [x] Create new visualizations for all Overview > Security Events dashboard
- [x] Change some visualizations in the main dashboards.

**File edition (rules, decoders, CDB lists, ossec.conf)** **(@adri9valle )**

- [x] Do not close the editor regardless the API calls result
- [x] Do not remove/hide the rule name input box even if the user has entered the name.
- [x] Once the user clicks on "Save" we want to replace the _save_ icon with a loading spinner inside the button until the request ends.
- [x] The multiline red errors we are showing under "Edit <file>..." must be relocated to a new card box in the top of the current box. Its style must be the same (white background, small border). This new box is located under the buttons and in the top of the "Edit <file>..." box.
- [x] Do not use a toaster for "Restart now or I'll do it later", we want to show it next to the action buttons (in-line).
- [x] Review all messages where we say "Restarting manager" even if it's a cluster, it's wrong right now.
- [x] Replace "Only custom" with "Custom rules" / "Custom decoders" ...

**Groups** **(@adri9valle)**

- [x] Replace "Group _group-name_ will be added to agent _agent-id_" with "Agent __agent-name__ will be added to group __group-name__"

**App buttons** **(@pablotr9)**

- [x] Do not use `<span>` or any other tag different to `<md-button>` or `<button>`
- [x] Do not use `btn-primary` as CSS class, we have `wz-button`, unify all occurrences of this is crucial.

**Cluster restarting behavior** **(@adri9valle )**

> Since files replication is not instantaneous, we must add an intended delay, transparent to the user.

- [x] Add delay after the `validation` and before the `restarting` action itself, the restart must be triggered after 15s (`setTimeout(() => restart(),15000)` ??)
- [x] Replace "It may take a few seconds..." with "It will take up to 15 seconds"

**Agents table** **(@pablotr9)**

- [x] ID column is too much large, reduce it, please. We can even detect if it's an agents table and hardcode its width.

**Comment by pablotr9** [comment]
working on this branch: https://github.com/wazuh/wazuh-splunk/tree/issue-571

**Comment by adri9valle** [comment]
Working on **File edition (rules, decoders, CDB lists, ossec.conf)**. Branch: [3.9-edition-changes](https://github.com/wazuh/wazuh-splunk/tree/3.9-edition-changes)

**Comment by adri9valle** [comment]
Working on **Cluster restarting behavior**
Branch: [3.9-delay-cluster-restart](https://github.com/wazuh/wazuh-splunk/tree/3.9-delay-cluster-restart)
Implemented: https://github.com/wazuh/wazuh-splunk/pull/573

**Comment by adri9valle** [comment]
Working on **Groups**
Branch: [3.9-groups-rename](https://github.com/wazuh/wazuh-splunk/tree/3.9-groups-rename)
Implemented: https://github.com/wazuh/wazuh-splunk/pull/576

**Comment by adri9valle** [comment]
Working on **Configuration assessment** with @pablotr9
Branch: [3.9-sca](https://github.com/wazuh/wazuh-splunk/tree/3.9-sca)
