### ISSUE TITLE
Will Wazuh  work on Splunk Cloud?

### ISSUE THREAD

**Issue by peachy8** [wazuh/wazuh-splunk#574]

**Comment by jesusgn90** [comment]
Hi @peachy8 ,

Sorry for the late response. Our Splunk app is commonly installed in a *search ahead* instance and there is no reason to do not work on Splunk cloud. The only thing to take care is about networking and ports.

Per our documentation you can see a common architecture for Splunk and Wazuh:

![image](https://user-images.githubusercontent.com/8860227/55537683-14d7b780-56bd-11e9-8b3d-f0ca5a07d183.png)

You can read more about it at [architecture.html#required-ports](https://documentation.wazuh.com/current/getting-started/architecture.html#required-ports), we also have an installation guide for Splunk, [installing-splunk](https://documentation.wazuh.com/current/installing-splunk/index.html).

Regards
