### ISSUE TITLE
Unable to process certain characters when inserting API credentials

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#577]
Hi team,

It's been reported that the app's backend is not able to process data fields with the `+` character. It's not known if this bug applies to any other characters, but possibly it does.
Thanks!

**Additional info:** When adding a new API with different credentials, if you select again the previous API, even if the credentials saved are bad, it's possible to select the API, this is wrong because the check connection must fail to prevent requests to an invalid API. 

- [x] Permit special charsets in API credentials(username and password).
- [x] Can't select API that connection fails. 

Cheers

**Comment by adri9valle** [comment]
Solved: https://github.com/wazuh/wazuh-splunk/pull/578
