### ISSUE TITLE
Ability to disable reporting feature

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-splunk#579]
Hi folks,

It's been reported that the app should provide a way to disable the  _reporting feature_, because in Search Head cluster environments the number of files could fill the storage, and also it may be not desired to keep anything on Search Heads.
The first steps for approaching this task could be these:

- [x]  Add the _reporting_ feature as a extension.
- [x] Implement the ability to disable/enable the _reporting_ feature.
- [x] Test the new behavior.

Cheers

**Comment by adri9valle** [comment]
Working on this branch: [3.9-reporting-extension](https://github.com/wazuh/wazuh-splunk/tree/3.9-reporting-extension)
