### ISSUE TITLE
Feature request - Logs summary viewer

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#602]
Currently, we are using `wz-table` to show logs from the ossec.log, it makes sense to use something like our file editor to show those logs.

Tasks:

- [x] Adapt the view to use "file editor" component
- [x] Disable edition for this use case
- [x] Adapt real-time logic for this new design

**Comment by pablotr9** [comment]
working on this branch: https://github.com/wazuh/wazuh-splunk/tree/3.9-log-viewer-improvements

- [x] Increase the number of logs shown when the bottom of the log viewer is reached.
- [ ] In real-time mode, add newer logs to the current list of logs.
