### ISSUE TITLE
Export agent configuration

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#640]
Currently, we can see the applied configuration for an agent, the goal here is to export that configuration well formatted using the "Reporting" features.

- [x] Adapt the reporting module to receive _agent.conf_ like inputs.
- [x] Export agent configuration well formatted  

Regards

**Comment by pablotr9** [comment]
Working on https://github.com/wazuh/wazuh-splunk/tree/3.10-export-agent-conf
**Update**
It has been added a new method to the reporting service to export an agent configuration.
Now I'm working on the backend to generate a report with that configuration

**Comment by adri9valle** [comment]
###### 29.04.19

- Create an *Export agent config* link to execute the request.
- Check if is an agent.conf report to prevent unnecessary requests in the backend.

**Comment by pablotr9** [comment]
**Update**
We are now generating a pdf with a given configuration in raw JSON, 
Now we are working on beautifying that configuration output in the pdf.

**Comment by pablotr9** [comment]
**Update**
Working on styling the pdf output to show it similar to how the configuration is shown in our app.

**Comment by pablotr9** [comment]
**Update**
- Fix error when importing modules in the backend.
- Styling pdf

**Comment by pablotr9** [comment]
**Update**
- Handle configuration when its type is dict or a list, a new table is created for that configuration.
- Show wodles configuration
- Styling pdf

**Comment by pablotr9** [comment]
**Update**
- Handle current page height, so a new page is added if necessary.
- Handle error when a configuration is unavailable.
- Fix log-collection tables that were not shown

**Comment by pablotr9** [comment]
**Update**
I am currently working on handling the data when its type is not a key-value configuration or a data table. It has also been improved the way the data is shown depending on its type.

**Comment by pablotr9** [comment]
**Update**
Working and testing that the pdf generated works as expected with different agent-configuration

**Comment by pablotr9** [comment]
**Update**
There was an error when a table had multiple fields and one of them exceeded the max size allowed, it has been fixed.
All data types that are received from our API are handled and transformed into a table with no errors.
It has been added a method to create different tables depending on a filter field.
Working on the pdf style:
![Screenshot from 2019-05-14 13-10-26](https://user-images.githubusercontent.com/35685689/57694786-ef8b8100-764c-11e9-9965-5fc0a27537f7.png)
![Screenshot from 2019-05-14 13-10-52](https://user-images.githubusercontent.com/35685689/57694792-f31f0800-764c-11e9-8541-5e11fd440224.png)

**Comment by jesusgn90** [comment]
We don't want technical words:

![image](https://user-images.githubusercontent.com/8860227/57770469-a7359700-7710-11e9-87d8-94e5765f345d.png)

Example:

```
"rootkit_files": "/var/ossec/etc/shared/rootkit_files.txt"
```

We don't want this, we want something like this:

_Rootkit trojans database path is /var/ossec/etc/shared/rootkit_files.txt_

Or some other format more human-readable.

The header is poorly designed, please unify with the Kibana report headers.

![image](https://user-images.githubusercontent.com/8860227/57770130-eb746780-770f-11e9-8169-08cc9474af13.png)

Tables are not well formatted. Headers, title, font color...

![image](https://user-images.githubusercontent.com/8860227/57770230-224a7d80-7710-11e9-9b76-812984f62b47.png)

So much white spaces between columns:

![image](https://user-images.githubusercontent.com/8860227/57770283-3d1cf200-7710-11e9-8d27-06c9e8b9a4ac.png)

Take care of the details:

![image](https://user-images.githubusercontent.com/8860227/57770304-473ef080-7710-11e9-8939-3c5b21dbe257.png)

Unify the fonts:

![image](https://user-images.githubusercontent.com/8860227/57770344-5f167480-7710-11e9-87ba-03ac80680976.png)

Add padding please:

![image](https://user-images.githubusercontent.com/8860227/57770357-6a69a000-7710-11e9-9b4a-2f3a6c14a6b6.png)

Format this kind of headers:

![image](https://user-images.githubusercontent.com/8860227/57770389-7ce3d980-7710-11e9-9a0b-b90174781d40.png)

Unnecessary word breaking:

![image](https://user-images.githubusercontent.com/8860227/57770432-9422c700-7710-11e9-9f71-4efca20711c1.png)

No Python/Programming references:

![image](https://user-images.githubusercontent.com/8860227/57770630-0693a700-7711-11e9-8adc-9fe4ad35237c.png)

Translate the keys, don't say "full_command", use "Full command". Also, format the column names, don't use "ignore_binaries".

![image](https://user-images.githubusercontent.com/8860227/57770721-3b9ff980-7711-11e9-80c3-40678b2e4dbf.png)

This is weird:

![image](https://user-images.githubusercontent.com/8860227/57770746-4c506f80-7711-11e9-8bf7-ecde7e30e84f.png)

Please guys, more love to your work!

**Comment by pablotr9** [comment]
**Update**
The use of technical words is fixed, now its shown a more human-readable format, the headers are fixed and the keys are translated.

- [ ] Avoid technical words, use human-readable format.
- [ ] Format headers
- [ ] Avoid unnecessary word breaking
- [ ] Translate the keys,
- [ ]  Add header padding
- [ ]  Unify header with the Kibana report headers.
- [ ] Unify the fonts.

**Comment by pablotr9** [comment]
**UPDATE**
- Fix header padding,
- Unify the headers with Kibana style. 
- Add new fonts
Currently working on avoiding unnecessary word breaking by setting a specific width to every row field depending on its size.

**Comment by pablotr9** [comment]
**Update**
All errors in the previous comment are now fixed, the tables now calculate the width depending on its content.
- [ ] Tables with more than 2 fields have a longer width than they should have.

An example pdf can be found:
[wazuh-exampleagentconfiguration-20190517112845.pdf](https://github.com/wazuh/wazuh-splunk/files/3191244/wazuh-exampleagentconfiguration-20190517112845.pdf)

**Comment by pablotr9** [comment]
**Update** 
The style of the pdf has been updated, an example of how the pdf looks like: 
[wazuh-pablotr9-agent-conf-20190524112720.pdf](https://github.com/wazuh/wazuh-splunk/files/3216642/wazuh-pablotr9-agent-conf-20190524112720.pdf)

**Comment by pablotr9** [comment]
**UPDATE**
It has been fixed an error when the length was bigger than the available space.
Some minor fixes in style/fonts have been added.
Integrity Monitoring -> Monitored Directories table have been replaced with a new table to use the available space more efficiently, an example of this new table: 
![Screenshot from 2019-05-28 13-07-49](https://user-images.githubusercontent.com/35685689/58474085-89255900-814a-11e9-8508-856763320454.png)

Current pdf example: 
[wazuh-agent-config.pdf](https://github.com/wazuh/wazuh-splunk/files/3227369/wazuh-agent-config.pdf)

**Comment by pablotr9** [comment]
**UPDATE**
It has been added a button to generate a pdf:
![generatepdf](https://user-images.githubusercontent.com/35685689/59044164-ebced100-887d-11e9-84f1-77e3d3960049.gif)

The styling have been improved and the pdf result is: [agent-configuration.pdf](https://github.com/wazuh/wazuh-splunk/files/3262234/agent-configuration.pdf)
