### ISSUE TITLE
Export group related information

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#641]
We have no way to export a group and its related information such as the agents or the files included in that group. We can do it by parts but definitively we want to collect all the information into one well-formatted exportable PDF.

Tasks:

- [x] Adapt the reporting module 
- [x] Minimum info
  - [x] Group name
  - [x] Configuration 
  - [x] Agents in the group

Regards

**Comment by pablotr9** [comment]
**UPDATE**
The group controller has been updated to send a request to generate a pdf with current group configuration.
The method that generates configurations has been adapted to also handle group configuration.
Currently working on handling the group data that it's being received to print the tables.

**Comment by pablotr9** [comment]
**UPDATE**
Working on this branch: https://github.com/wazuh/wazuh-splunk/tree/3.10-export-group-conf
Now a pdf with group information (name, agent count...) and agent.conf configuration is being generated, currently working on styling the pdf to show this data.

**Comment by pablotr9** [comment]
**Update**
The pdf now contains the group configuration divided by its configuration filters.
The agent list in that group is also shown with its information

**Comment by pablotr9** [comment]
**UPDATE**
It has been a button to generate a pdf of the current group related information:
![generatepdf-agents](https://user-images.githubusercontent.com/35685689/59044331-4405d300-887e-11e9-828a-86e7881eee4b.gif)
I am currently testing that pdf is generated correctly with a huge amount of agents and with different configurations.

**Comment by pablotr9** [comment]
**UPDATE**
This is an example of the pdf generated with different configurations and ~10k+ agents:
[wazuh-group-conf2.pdf](https://github.com/wazuh/wazuh-splunk/files/3266067/wazuh-group-conf2.pdf)

**Comment by pablotr9** [comment]
**Update**
When the selected group had no configuration available or no agents were assigned to it, generating a pdf produced an error. This error have been fixed.
