### ISSUE TITLE
Prevent errors when Wazuh is not ready yet.

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#642]
Hi team,

In order to prevent several errors when the App is used, would be necessary to implement a new feature that checks if Wazuh is ready to serve the App requests.

Regards,

**Comment by adri9valle** [comment]
Working on this branch: [equalize-k](https://github.com/wazuh/wazuh-splunk/tree/equalize-k)

**Comment by Aditya654** [comment]
Wazuh api log says 
Wazuh API is online but Wazuh is not ready yet
Kibana cannot connect to wazuh app after 30 seconds of restart. It shows "wazuh not ready yet"
How to solve this?
