### ISSUE TITLE
Request fixes after general review

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#657]
Hi team,

After a general review of the Wazuh App for Kibana, there are several request changes and fixes.

## Global changes

- [x]  Remove {} from the chips. @adri9valle 
- [x] Percent while report is generating. @pablotr9 
- [x] Change expands icons.(**Svg inserted**) @adri9valle 
- [x] Remove `index:wazuh` from the filters chips. @adri9valle 
- [x] Improve reports style. @adri9valle 
- [x] Set the same order for the elements in the welcome cards. @adri9valle 
- [x]  Set the Kibana App style to welcome cards. @adri9valle 
- [x] Add loupe to the filter bars. @pablotr9 
- [x] Change the switch style. @adri9valle 
- [x] Change formatted button style. @adri9valle 
- [x]  Remove `Next >` and `<Prev` now we use `>` and `<`. @adri9valle 
- [x] Remove tooltip in welcome cards. @adri9valle 
- [x] Set the same blue that Kibana uses in the metrics. @adri9valle 
- [x] Fix extra padding in subtab navbar @pablotr9 
- [x] Change col-resizable lib @adri9valle 
- [x] Add fetching data loading spinner while the visualizations are loading @adri9valle 
- [x] When changing the value of the dropdown the style is wrong @adri9valle 
![image](https://user-images.githubusercontent.com/7983984/56656110-e84c0580-6694-11e9-817c-3bc661bbb444.png)

#### Welcome
- [x] Overview welcome, remove loading ring. @adri9valle 
- [x] Remove breadcrumb and overview in Overview welcome. @pablotr9 

#### Dashboards
- [x] Geomaps in AWS @pablotr9 

## Management
- [x] Remove loading ring when access in this section. @adri9valle 
- [x] Remove headers and breadcrumbs. @pablotr9 
- [x] Set the same title that Kibana has. @pablotr9 
- [x] Missing sub-tabs nav-bar menú. @pablotr9 
- [x] Add navbar in Status and reports section @adri9valle 

#### Reporting
- [x] Remove grey line under the table. @pablotr9 
- [x] Change the icons. @adri9valle 

#### Logs
- [x] Adjust width of the selectors.
- [x] Set the same order that Kibana has in the selectors. @pablotr9 
- [x] Empty results are not controlled.  @adri9valle 
- [x] Remove "mini" header. @pablotr9 

#### Status
- [x] Fix padding in the daemons box. @pablotr9 
- [x] Remove "mini" header. @pablotr9 
- [x] Flicks when the restart button is pressed. @pablotr9 
- [x] Spinning in the restart button while Wazuh is restarting. @adri9valle 

#### Groups
- [x] Remove md-cards actions.  @pablotr9 
- [x] Change the way to add a new group. @adri9valle 
- [x] Flick when hiding a column. @pablotr9 
- [x] `Groups sum` rename to `configuration checksum` @pablotr9 
- [x] Tooltip edit -> `Edit this group configuration` @pablotr9 
- [x] Change the icons. @adri9valle 
- [x] Table witdh agents must be resizable and has custom columns. @pablotr9 
- [x] `MD5 sym` rename to `Checksum` @pablotr9 
- [x] Change the **x** style when open a file in the of a file that is not the agent.conf. @adri9valle 
- [x] Fix scroll in the content of a file. @pablotr9 
- [x] Fix witdh of the file column. @pablotr9 
- [x] Increase number of rows. @pablotr9 
- [x] Tile of the xml box when editing a agent.conf file -> `Edit agent.conf of ${group}`. @pablotr9 

#### Configuration
- [x] Change icons style. @adri9valle 
- [x] Repeated titles. @adri9valle 
- [x] Check transitions.

###### Editing configuration @adri9valle 
- [x] Missing breadcrumb.
- [x] XML box title: `Edit ossec.conf of ${manager/node}`
- [x] Cancel without the border.
- [x] While Wazuh is restarting change the triangle icon for a floater icon.
- [x] Set the same toaster messages that Kibana.
- [x] Restart button set as Kibana. And the order of cancel, confirm.
- [x] Spinning in the restart button while the restart is in progress.

#### Ruleset @adri9valle 
- [x] Add a sub-nav-bar to change between rules, decoders, and lists.
- [x] Remove breadcrumbs.
- [x] Set the same columns order that Kibana has.

###### Rule detail @adri9valle 
- [x] Fix box padding.
- [x] Remove breadcrumbs, add tabs.
- [x] **Replicate in decoders**

 ###### CDB lists @adri9valle 
- [x] Remove breadcrumbs, add tabs.
- [x] Missing metrics with clicked name and path.
- [x] Inputs width must fill all the column.
- [x] When an entry is edited, there is a flick. @pablotr9 
- [x] When an entry is edited, do not hide add a new entry.

## Dev- Tools 

- [x] Fix padding icons. @pablotr9 
- [x] Always show the raw output even if has errors. @pablotr9 
- [x] When access to Dev-tools the play button in the first line is misplaced. @pablotr9 
- [x] Tooltip download `Export as JSON` @pablotr9 

## Settings @adri9valle 

- [x] Check icons, and transitions.
- [x] Set the same titles that Kibana has.  
- [x] Set the same buttons that Kibana has. 
- [x] Welcome message when there is not an API saved. 
- [x] `Index` must have the same style that `Patterns` in Kibana. 
- [x] Change about section. 
- [x] When there is not an API show the form opened and hide the add API button. 
- [x] Change the text in the add API button. 

## Agents @adri9valle 
- [x] Change header style in the welcome state.
- [x] ~~Missing restart agent button.~~ **Agent must be active**
- [x] Missing `active/disconnected` status near the agent name.
- [x] Remove `welcome` from the breadcrumb. @pablotr9 

## Menu

- [x] Change the icons. @adri9valle 

## Additional fixes
` In this clause will be added the improvements or error that have been founded while the other checks were implemented`

- [x] Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy' @adri9valle 
- [x] Fix nosortable wz-table @adri9valle 
- [x] Implicit filters cannot be deleted even if is only showing the chip and are not applied. @adri9valle 
- [x] ID fields in wz-table are split. @adri9valle

**Comment by adri9valle** [comment]
Working on this branch: [request-fixes](https://github.com/wazuh/wazuh-splunk/tree/request-fixes) with @pablotr9

**Comment by pablotr9** [comment]
**Update** 

Today, I have removed headers and breadcrumbs from Management/Logs/Status sections, added missing sub-tabs nav-bar to Management sections. removed grey line under the table in reporting section. edit the order in Logs selectors and fixed style in Cluster/Status.

**Comment by adri9valle** [comment]
**Update** 
Today progress:
- Agents (done)
- CDB List: need to be done -> flick
- Ruleset and Rule details (done)
- Configuration: Repeated sections (done)
- Editing configuration (done)
- Groups: Fix **x** icon (done)
- Status: Spinning in the restart button (done)
- Global changes
    - Set the same order in the welcome (done)
    - Set Kibana style in the welcome cards (done)
    - Remove next and prev (done)
    - Remove tooltip (done)
    - Set the same blue that Kibana (done)

**Comment by adri9valle** [comment]
***Today progress:***

- Global changes
    - Remove {} from the chips.
    - Change expands icons
    - Remove index:wazuh from the filters chips
    - Change formatted button style
    - Remove loading ring
    - Improve reports style **Some style changes**

- Overview
    - Welcome
        - Overview welcome, remove loading ring
        - Dashboard Set the same dashboards that Kibana has. **In progress**

- Management 
    - Remove loading ring when access in this section
    - Add navbar in Status and reports section

- Settings
    - Check icons, and transitions.
    - Set the same titles that Kibana has.
    - Set the same buttons that Kibana has.
    - Welcome message when there is not an API saved.
    - Index must have the same style that Patterns in Kibana.
    - Change about section.
    - When there is not an API show the form opened and hide the add API button.
    - Change the text in the add API button.
    - Change some visualizations

**Comment by pablotr9** [comment]
**Update**

Today's progress:
Dev-Tools now shows the raw output even if it has errors, icons padding and input/output boxes size have been fixed, the play button is correctly placed in the first line and the tooltip now shows some meaningful text.
Groups, in group and agent tables MD5 sym and Group Sum headers have been replaced, the agent table is now resizable and has custom columns. When visualizing a group file we can now scroll through it.  The width of the column file has been decreased and now we have more rows per table. It has also been fixed the header text when editing agent.conf.

**Comment by pablotr9** [comment]
** Update ** 
All navbars in subsections are now fixed and its links.
Now working on **Set the same dashboards that Kibana has.**

**Comment by adri9valle** [comment]
Today progress:
- Change the switch style.
- Change col-resizable lib.
- Geomaps in AWS (**Added but the query does not return results**).
- Change the icons in the reporting and configuration section.
- Change col-resizable lib.
- Working on the flicks

**Comment by pablotr9** [comment]
**Update**
Fixed unexpected flickers and added loupe icon to search inputs

**Comment by adri9valle** [comment]
22.04.19

Working in this and other issues have been discovered three problems:

-  Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'destroy' 
-  ~~Fix nosortable wz-table~~
- ~~Implicit filters cannot be deleted even if is only showing the chip and are not applied~~

The capped points have been resolved today.

**Comment by pablotr9** [comment]
**Update** 
Now a percent is shown while a report is being generated.
Still working on setting the same dashboards that Kibana has.

**Comment by adri9valle** [comment]
23.04.19

Testing the App have been found an error when changing between sub states the filters were not removed always. Fixed here https://github.com/wazuh/wazuh-splunk/pull/668/commits/b40f50ed73622bdd32734149033f78dd688d3293

**Comment by adri9valle** [comment]
24.04.19

- Added fetching data loading spinner while the visualizations are loading

**Comment by pablotr9** [comment]
**Update**

Updating dashboards:
Update agent SCA dashboard https://github.com/wazuh/wazuh-splunk/commit/a8dc1e2c3356da237ea8c11639e1545c86d9a5b4
Update agent openscap dashboard https://github.com/wazuh/wazuh-splunk/commit/0e2dd4f2d5b627663f3e2c70478b38befd8ecbb2
Update ciscat dashboard https://github.com/wazuh/wazuh-splunk/commit/1a79b3a79620d2306eac44b58a0155f7587bd172

Styling fixes https://github.com/wazuh/wazuh-splunk/commit/e0e32111dd5b30e95d18f7883cca913895ff2fd5  https://github.com/wazuh/wazuh-splunk/commit/3ac946c87f4c94d37c9be9a082ad199ffc72da59
Add new type of visualizations (gauge & singleValue)  https://github.com/wazuh/wazuh-splunk/commit/e6a5eb5b45b663956df762a6800b4579039422ae
Add trellis layout option to pie charts https://github.com/wazuh/wazuh-splunk/commit/4d6bcd96141e398750cf2362e155a11ccccb30f9

**Comment by adri9valle** [comment]
25.04.19

- Added no scans available and refresh button when are not SCA scans.
- Working to implement angular charts.
