### ISSUE TITLE
Add SCA checks 

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#676]
Tasks:

- [x] Add SCA regex fields in the checks table.
- [x] Add description field in the checks table.
- [x] Add policy checksum.
- [x] Add the policy ID to the table.
- [x] Add filter bar.
- [x] Add stats in title bar.

**Comment by adri9valle** [comment]
Working on this branch: [sca-info](https://github.com/wazuh/wazuh-splunk/tree/sca-info)
