### ISSUE TITLE
Adapt all dashboards to be the same as Kibana app dashboards

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#677]
Tasks:

###### Overview:

- [x] Security Events 
- [x] Fim             
- [x] Aws             
- [x] Policy monitoring
- [x] SCA
- [x] Audit
- [x] Open Scap
- [x] Cis-cat
- [x] Vulnerabilities
- [x] VirusTotal
- [x] Osquery
- [x] Docker
- [x] Pci
- [x] Gdpr

###### Manager -> Cluster monitoring:

- [x] Cluster
- [x] Nodes
- [x] Overview

###### Agents:

- [x] Security Events 
- [x] Fim   
- [x] Inventory data     
- [x] Policy monitoring
- [x] SCA
- [x] Audit
- [x] Open Scap
- [x] Cis-cat
- [x] Vulnerabilities
- [x] VirusTotal
- [x] Osquery
- [x] Docker
- [x] Pci
- [x] Gdpr

Regards

**Comment by pablotr9** [comment]
**Update**
-Update agent-pcidss dashboard https://github.com/wazuh/wazuh-splunk/commit/c6011869caeb994f9ac863cb4404c714626f170b
-Cluster Monitoring fixes https://github.com/wazuh/wazuh-splunk/commit/351fc53fd917f0d1f5d7681fdf360a55b0fed681
-Update agent-virustotal dashboard https://github.com/wazuh/wazuh-splunk/commit/ccfed7530177acca9c2b8ff5549a70970b92da02 
-Update overview vulnerabilities dashboard https://github.com/wazuh/wazuh-splunk/commit/020aaf847270ecb4367716455fcff61de439c76c
-Update overview-virustotal dashboard https://github.com/wazuh/wazuh-splunk/commit/1528fa414ecb15e478eb7c0ccbca27799200d049
-Some other fixes  https://github.com/wazuh/wazuh-splunk/commit/a0f45bfdbed3dcf9ea8925f4ba1607bd5e6e231c https://github.com/wazuh/wazuh-splunk/commit/4852d00feaa3e7df978168283e3f3fc4842fc003 https://github.com/wazuh/wazuh-splunk/commit/60adf739195928373263d8f18fc3b44a85249732

**Comment by adri9valle** [comment]
###### 26.04.19

I have been configuring the bellow modules to generate alerts and compare the dashboards with Kibana:

- Osquery
- Vulnerabilities
- Openscap
- CIS-CAT
