### ISSUE TITLE
Testing 3.9.1 - 7.2.6

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#706]
Tasks:

- [x] Review all tables (resizable + no resizable)
- [x] Check configuration, rule, decoder, list editors error handling
- [ ] Ensure Agent label configuration and Agent client configuration sections are shown the right information
- [x] Check Management > Logs scrolling
- [x] Check Management > Logs infinite fetching solution
- [x] Verify the timezone for all the parts where we are using dates
- [ ] Ensure "dynamic height" for editors is working as expected
- [x] Test different use cases for Wazuh version validation
- [x] Test the kvStore not ready yet behavior

On a side note:

- [x] Fully test [#686](https://github.com/wazuh/wazuh-splunk/pull/686) and [#692](https://github.com/wazuh/wazuh-splunk/pull/692)

**Comment by adri9valle** [comment]
**Update**:

After test the related point of this issue, there are found several errors:

- **Review all tables (resizable + no resizable)**: Agents table does not apply the resizable capability to all columns.
- **Manager/Agents configuration**: When clicking on help, the displayed div has a different background color, this break the aesthetics of the app.
- **Ensure "dynamic height" for editors is working as expected**: *Manager > Logs* section has a `formatted` button that provokes that the page shows a little scroll.

Also while checking **Verify the timezone for all the parts where we are using dates** I found an unused code line in `inventoryCtrl.js`  -> `this.setBrowserOffset('2019/04/24 10:59:03')`.

Regards,

**Comment by adri9valle** [comment]
**Update**:

I have solved the related problems in the previous comment in this PR https://github.com/wazuh/wazuh-splunk/pull/707.

Regards,

**Comment by adri9valle** [comment]
**Update:**

In the second testing were found several reports when missing visualizations, also the navbar in agents `Threat Detection and Response` section was redirecting to overview in some tabs.

These errors were solved in this PR: https://github.com/wazuh/wazuh-splunk/pull/708
