### ISSUE TITLE
Error when APP makes a DELETE API request

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#711]
Hi team,

Has been detected an error when trying to delete several agents with this API request `DELETE /agents?status=Disconnected&older_than=100s` concretely. The problem is that for this request the parameters are sent in the body of the request and is necessary to send them in the query string. 

- [x] Check for others possible API requests with errors.
- [x] Find the way to avoid API request errors.

**Update**

While working on this issue I have found another error, if you try to use the param `id` in the devTools, an error is thrown from the backed:

```
POST /agents/insert
{
  "id": "005"
}
```
Result: 
```
{
  "error": "'userapi'"
}
```

- [x] Fix `id` field error.

Regards,

**Comment by jesusgn90** [comment]
Hi team,  

**Proposal**

Replace:

https://github.com/wazuh/wazuh-kibana-app/blob/bab06e572187ef35cdd7c92f912d5e5ee06592e5/public/controllers/dev-tools/dev-tools.js#L599-L602


with:

https://github.com/wazuh/wazuh-kibana-app/blob/e836fd11fa9ad14f08d52e3c19cc71d329b702d3/public/controllers/dev-tools/dev-tools.js#L599-L612

**Tests**

|                                            | GET | POST | PUT | DELETE |
|-------------------------------------|--------|---------|--------|--------------|
| NO PARAMS                      | --  | --   | --  | --     |
| INLINE PARAMS                | --  | --   | --  | --     |
| JSON PARAMS                  | --  | --   | --  | --     |
| INLINE + JSON PARAMS  | --  | --   | --  | --     |

_Inline has precedence_

**Comment by adri9valle** [comment]
**Update**

- Fix `id` field error. -> This error was provoked because we sent the **id** of the API as `id` param too, then when the backend tried to connect with the API using an incorrect **id** an error was thrown.

**Comment by adri9valle** [comment]
**Test results**

The tests after the proposal fix have been passed successfully. The values used were:
- **OK**: For success test.
- **KO**: For fail test.
- **--**: For cannot check this test.

There are two tests that cannot be checked because the API has not the possibility to test it.
