### ISSUE TITLE
Redesign Overview > Welcome view

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-splunk#726]
| Wazuh | Splunk |
|-----------|----------|
| 3.10.0  | 7.2.6      |

**Description**

Our _welcome screen_ is a bit confusing for new users so we need a drastic change for that view (the very first view is opened once you enter the app).

**Proposal**

Here are some ideas, but we are open to different ideas:

- Cards with a similar style to `/app/kibana#/home?_g=()` from Kibana.
- Draggable items, store distribution.
- Remove the "extensions" from settings, instead, put an auxiliary icon or something similar in the welcome screen, so the user can quickly show/hide extensions. This feature doesn't enable the module, just show/hide it and we are giving the user a full view in settings that seems to enable the modules.
- Add a friendly guide for empty results in dashboards, so the user can quickly enable that module (through the app?)
- Any other change that makes the Overview > Welcome looks very different from past releases, we need changes.

Regards

**Comment by adri9valle** [comment]
**Update**

As a proposal, I've changed the icons from the Welcome views and the color palette in order to adapt to the Splunk style.

##### Overview Welcome
![image](https://user-images.githubusercontent.com/7983984/58807057-a9a45600-8617-11e9-8377-5ad947d8d867.png)

##### Agents Welcome
![image](https://user-images.githubusercontent.com/7983984/58807127-c771bb00-8617-11e9-8744-526716230ba8.png)

##### Management Welcome
![image](https://user-images.githubusercontent.com/7983984/58807718-ea509f00-8618-11e9-964b-91e9d77f4fe3.png)


##### Overview General

![image](https://user-images.githubusercontent.com/7983984/58807309-16b7eb80-8618-11e9-9fd8-292e8843fca6.png)


##### Settings API
![image](https://user-images.githubusercontent.com/7983984/58807847-25eb6900-8619-11e9-93ae-f58b68f5436d.png)


##### Settings Extensions
![image](https://user-images.githubusercontent.com/7983984/58807874-33085800-8619-11e9-98de-2638ede6cc2d.png)


##### Management Ruleset

![image](https://user-images.githubusercontent.com/7983984/58807955-5b905200-8619-11e9-91a3-4df25edd6acd.png)

**Comment by adri9valle** [comment]
**Update**

I've redesigned the welcome look:

![image](https://user-images.githubusercontent.com/7983984/58865725-5f72b180-86b7-11e9-9fa3-3c5030aeb57a.png)


**Not finished yet**

**Comment by adri9valle** [comment]
**Update**

The Agent welcome section has been redesigned

![image](https://user-images.githubusercontent.com/7983984/58873213-18d88380-86c6-11e9-8b80-a01fe1077457.png)

**Comment by adri9valle** [comment]
**Updated**

I've changed some colors and the Overview Welcome screen.

![image](https://user-images.githubusercontent.com/7983984/58889560-674b4980-86e9-11e9-9be7-e15208c6ab20.png)

**Comment by adri9valle** [comment]
**Update**

Some colors and heights have been modified. Also, the 3.10 branch has been merged to apply the last changes.

**Final result** (subject to change):

![image](https://user-images.githubusercontent.com/7983984/58964051-8b249300-87ae-11e9-9f82-e7f1b06a3b7e.png)

![image](https://user-images.githubusercontent.com/7983984/58964079-937cce00-87ae-11e9-8d65-a95e61810a3f.png)

![image](https://user-images.githubusercontent.com/7983984/58964105-9f689000-87ae-11e9-8dba-acce071dec48.png)

![image](https://user-images.githubusercontent.com/7983984/58964131-af806f80-87ae-11e9-835c-3829f799ffce.png)

![image](https://user-images.githubusercontent.com/7983984/58964151-b7d8aa80-87ae-11e9-8541-fb3d832b7b47.png)

![image](https://user-images.githubusercontent.com/7983984/58964163-bf984f00-87ae-11e9-9db9-e137be8a9ae3.png)

![image](https://user-images.githubusercontent.com/7983984/58964185-c9ba4d80-87ae-11e9-9e88-97c27606c98e.png)

![image](https://user-images.githubusercontent.com/7983984/58964241-dccd1d80-87ae-11e9-98df-1a5f6400c8cd.png)

![image](https://user-images.githubusercontent.com/7983984/58964302-f1a9b100-87ae-11e9-9cc7-0e4c56cc809a.png)

The most significate screenshots are posted here.

**Comment by adri9valle** [comment]
**Update**

I've merged the last 3.10 features and resolved the conflicts. Also, I've changed the color of the bottom border in the nav-bars:

![image](https://user-images.githubusercontent.com/7983984/59101529-87694b80-8929-11e9-8781-8dd69880ccb2.png)

**Comment by adri9valle** [comment]
**Update**

I've added an eye, this eye will open the extension related to the card:

![image](https://user-images.githubusercontent.com/7983984/59103179-6ce5a100-892e-11e9-88c0-4e8ebcbe9729.png)

**Comment by adri9valle** [comment]
**Update**

A list with the extensions is shown:

![image](https://user-images.githubusercontent.com/7983984/59110289-19c81a00-893f-11e9-85ea-1de8b62c72af.png)

Is a first iteration the style will change.

**Comment by adri9valle** [comment]
**Update**

I've changed the popover style and added to all welcome cards of Overview:

![image](https://user-images.githubusercontent.com/7983984/59280927-af78e780-8c66-11e9-8ec2-64fe8b292ad3.png)


**TODO**: Implement the function to execute when the switch changes.

**Comment by adri9valle** [comment]
**Update**

I've implemented the function to hide or show extensions, also if all the extensions are hidden an information message is shown.

![hide-ext](https://user-images.githubusercontent.com/7983984/59341595-77c27c00-8d08-11e9-93a3-92dcfdb91092.gif)

**Comment by adri9valle** [comment]
**Updated**

Applied en the `Agents > Welcome` the popover. Removed from `Settings` the extensions tab.

![image](https://user-images.githubusercontent.com/7983984/59345986-9e38e500-8d11-11e9-8a0a-6560bd56b7b2.png)


Working on a directive to implement a popover.

**Comment by pablotr9** [comment]
**Update** 
- The agent status badge has bee replaced https://github.com/wazuh/wazuh-splunk/commit/05c8dccb475470a3a191ccf3b901804053efd5ad
![image](https://user-images.githubusercontent.com/35685689/60089515-ee1ba100-9740-11e9-8d56-d66d138fd5be.png)
- Management section has been changed too, so it now looks like other welcome screens: https://github.com/wazuh/wazuh-splunk/commit/fcbf38dfb6d9119671448901ec201899d3ea2471
![image](https://user-images.githubusercontent.com/35685689/60089662-45ba0c80-9741-11e9-8262-d96ce3281794.png)

**Comment by pablotr9** [comment]
**Update** 
- Corrected the width for certain columns on the metrics bar of the agent welcome screen. Now the ID field is shorter and the OS field has a minimum width of 400px. 
![ag-metrics](https://user-images.githubusercontent.com/35685689/60186260-b50c2b00-982b-11e9-8f52-b95872832bbc.png)
- Redesigned API entries table in Settings:
![image](https://user-images.githubusercontent.com/35685689/60186523-42e81600-982c-11e9-9aa4-7b8de5748b93.png)
  -  View when there are no API entries:
![api](https://user-images.githubusercontent.com/35685689/60186422-01576b00-982c-11e9-8ccc-fa2874874c95.png)
  -  And this is how it looks when editing an existing one API entry:
![image](https://user-images.githubusercontent.com/35685689/60186542-4d0a1480-982c-11e9-844c-562a7da6c713.png)
- A new directive `<wz-alert-metrics>` for alerts metrics has been added:
![image](https://user-images.githubusercontent.com/35685689/60186690-9c504500-982c-11e9-8729-9c2da9490df7.png)

**Comment by pablotr9** [comment]
**Update**
Minor API section style improvements
![Peek 2019-06-27 11-55](https://user-images.githubusercontent.com/35685689/60256769-74b3b800-98d2-11e9-8668-f104c2cf15c0.gif)

**Comment by pablotr9** [comment]
**Update** 
Some styles were not correctly applied, fixed here:  https://github.com/wazuh/wazuh-splunk/commit/1282d6213a9f3f1cab65e50181ecf84ed521906d
-Navbar: 
![navbarmal](https://user-images.githubusercontent.com/35685689/60353802-1a4a5280-99cb-11e9-92de-5ad8390967d8.gif)
-Settings icon was blank when clicked.
![settingsmal](https://user-images.githubusercontent.com/35685689/60353872-41a11f80-99cb-11e9-8c95-9c87404e6157.png)
