### ISSUE TITLE
Filters are not applied in the wz-bar

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#732]
| Wazuh | Splunk | Rev |
|-----------|----------|-------|
|  3.10      |  7.2.6      | 28 |

**Description**

When applying a filter in the `wz-bar` directive the filter is not applied.

**Steps to reproduce**
1. Go to any dashboard.
2. Input some filter in the `wz-bar`
3. Press enter to apply the filter
4. See how the filter is not applied.

![nofil](https://user-images.githubusercontent.com/7983984/58789663-fc1d4c80-85ee-11e9-8096-3e2658e38c94.gif)

**Comment by pablotr9** [comment]
Hi team,
I found out that every time we added a new filter the current state was reloaded and we were deleting all added filters as shown here:
![image](https://user-images.githubusercontent.com/35685689/58795101-101a7b80-85fa-11e9-8167-f1f96773591c.png)
This have been fixed ( https://github.com/wazuh/wazuh-splunk/pull/733) , we can now successfully add new filters.

**Comment by jesusgn90** [comment]
Blocked by https://github.com/wazuh/wazuh-splunk/issues/705
