### ISSUE TITLE
Agents search bar not applying filter when refreshing

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#742]
| Wazuh | Splunk | Rev |
|-----------|-----------|-------|
|  3.9.x   |  7.3.0 | n/a |

**Description**
If I click on Agents and then in "Add a filter or search" I type in all or part of one of the agent names, it successfully filters the list but if I click the Refresh button to the right, the full unfiltered list of agents appears even though the filter criteria still appears.

**Steps to reproduce**
1. Go to _Agents preview_
2. Click on the search bar
3. Write something that would reduce the results, eg: "specific agent name"
4. Click on the "Refresh" button
5. The results are reloaded, the filter is shown but it's not being applied.

**Screenshots**

![image](https://user-images.githubusercontent.com/8860227/59014145-2748ab80-883c-11e9-8207-341126a275ba.png)

![image](https://user-images.githubusercontent.com/8860227/59014174-434c4d00-883c-11e9-9341-7a2b59a57b45.png)

**Comment by adri9valle** [comment]
**Update**

Solves in this PR https://github.com/wazuh/wazuh-splunk/pull/743.

The problem was that the refresh button was re-initializing the Wazuh table and didn't apply the set filters in the new search.

Also, the PR adds a loading bar while the table is refreshing the data.

**Comment by pablotr9** [comment]
**Update**
It has been added try/catch blocks in order to correctly handle errors.
