### ISSUE TITLE
Granular options for agent configuration reports

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-splunk#749]
In https://github.com/wazuh/wazuh-splunk/issues/640 we've created a new kind of reports for the Wazuh app, the agent configuration reports, with this ticket we are improving this new feature.

When the user clicks the PDF button, we want to show a dropdown with the one check per component, this way the user can customize the report.

Example:

 > I want a document where I can see the FIM configuration for the agent 003.

Something like this:
![](https://user-images.githubusercontent.com/8860227/59093819-2172c900-8915-11e9-9a6c-29c14b430c73.png)

**Comment by pablotr9** [comment]
**Update**
Our export agent configuration method was generating a PDF with all available configurations of an agent, now the back-end have been modified so the PDF can now contain a dynamic number of configurations that the user has previously selected.
Just the logic has been added and the dropdown to select the desired configurations have not been added yet as we are currently working on #628

**Comment by adri9valle** [comment]
**Update**

I've implemented a `popover` to select the desired modules to export their configuration. Also, was implemented the option to select/unselect all and a function to return the key equivalence.

![image](https://user-images.githubusercontent.com/7983984/59358830-92f3b280-8d2d-11e9-8fdb-a68cad5fa536.png)


**Note**: If there aren't any module selected the button to generate the report is disabled.

**Comment by pablotr9** [comment]
**Update**
The `popover` mentioned in the previous comment has been enabled to call our backend and generate a PDF depending on the options that has been selected.
We found out a problem generating a PDF: the title of every subsection was being generated even if it had been unselected. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/a7da4c803dbe52aa39613fd9dbe400795f68e8e2.

Example of the procedure and the obtained result:
![Screenshot from 2019-06-12 16-32-59](https://user-images.githubusercontent.com/35685689/59362216-5dea5e80-8d33-11e9-8f73-b7d3eadd2ce2.png)
PDF: [wazuh-agent-conf.pdf](https://github.com/wazuh/wazuh-splunk/files/3281897/wazuh-agent-conf.pdf)

**Comment by pablotr9** [comment]
**UPDATE**
- If agent is not Active, the PDF button is disabled.
- Some sections are hidden depending on the agent OS. e.g (docker and openscap are hidden for non linux agents):
Windows agent: 
![image](https://user-images.githubusercontent.com/35685689/60426765-9aec9700-9bf5-11e9-885f-e22848f29c2b.png)
Linux agent:
![image](https://user-images.githubusercontent.com/35685689/60426814-b061c100-9bf5-11e9-9f00-25dc02fa714e.png)

**Comment by pablotr9** [comment]
**Update**
Testing different Windows agents configuration reports to check that is being succesfully generated.
- Some windows-only keys have been added to the key-equivalences in order to show human-readable text in generated reports. https://github.com/wazuh/wazuh-splunk/commit/9c8e54ba74e15272781112a93eefa3de689f101d

**Comment by pablotr9** [comment]
Configuration block |  SQLite
:------------ | :-------------
Global configuration | :heavy_check_mark: 
Communication | :heavy_check_mark: 
Anti-flooding | :heavy_check_mark: 
Labels | :heavy_check_mark: 
Policy monitoring | :heavy_check_mark: 
OpenSCAP (**Linux-only**) | :heavy_check_mark: 
CIS-CAT | :heavy_check_mark: 
Osquery | :heavy_check_mark: 
Inventory data | :heavy_check_mark: 
Active response | :heavy_check_mark: 
Commands | :heavy_check_mark: 
Docker listener  (**Linux-only**)  | :heavy_check_mark: 
Log collection | :heavy_check_mark: 
Integrity monitoring | :heavy_check_mark:
