### ISSUE TITLE
App crashes after configuring API and browsing

### ISSUE THREAD

**Issue by tqnguyen9** [wazuh/wazuh-splunk#789]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 3.9.3   | 7.3.0     | 33 |

**Description**
I am running Splunk in a distributed environment with a deployment server serving apps to a single search head cluster. After deploying the Wazuh app and entering API credentials, the app crashes. Wherever I click in the app now, it redirects me to the API configuration screen. That screen shows a "Disabled" cluster and I am unable to remove, edit, or re-add it.

I tried to remove the app and reinstall, but the app is still in the same failed state. I get the same error using both Firefox and Chrome browsers.

**Steps to reproduce**

1. Download https://packages.wazuh.com/3.x/splunkapp/v3.9.3_7.3.0.tar.gz and untar it on the deployment server under `/opt/splunk/etc/shcluster/apps/`
2. Deploy the app using the standard command with the target of a search head in the cluster
```bash
./splunk apply shcluster-bundle -target https://X.X.X.X:8089
```
3. In Splunk, go to the Wazuh App and enter API credentials.
4. Navigate around the app. I don't remember exactly what I clicked, but I believe it was the agent/discovery tab that broke the app.

**Screenshots**
![Image of broken API configuration screen](https://i.imgur.com/OQkvw50.png)

**Additional context**
Excerpt from `/opt/splunk/var/log/SplunkAppForWazuh.log`
```
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:22:31,245" , "level": "ERROR" , "message": "Error at get document DB: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 94, in get
    data = self.db.search(self.Api.id == id)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 570, in search
    docs = [doc for doc in self.all() if cond(doc)]
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 401, in all
    return list(itervalues(self._read()))
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 374, in _read
    return self._storage.read()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 85, in read
    raw_data = self._storage.read() or {}
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/storages.py", line 108, in read
    return json.load(self._handle)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/splunk/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:22:31,245" , "level": "ERROR" , "message": "Error making API request: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "<string>", line 115, in request
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 97, in get
    raise e
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:22:31,411" , "level": "ERROR" , "message": "Error at get all documents DB module: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 86, in all
    all = self.db.all()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 401, in all
    return list(itervalues(self._read()))
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 374, in _read
    return self._storage.read()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 85, in read
    raw_data = self._storage.read() or {}
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/storages.py", line 108, in read
    return json.load(self._handle)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/splunk/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:22:31,411" , "level": "ERROR" , "message": "{"error": "Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)"}" }
Traceback (most recent call last):
  File "<string>", line 115, in get_apis
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 89, in all
    raise e
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:22:35,145" , "level": "ERROR" , "message": "Error at get document DB: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 94, in get
    data = self.db.search(self.Api.id == id)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 570, in search
    docs = [doc for doc in self.all() if cond(doc)]
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 401, in all
    return list(itervalues(self._read()))
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 374, in _read
    return self._storage.read()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 85, in read
    raw_data = self._storage.read() or {}
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/storages.py", line 108, in read
    return json.load(self._handle)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/splunk/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:22:35,146" , "level": "ERROR" , "message": "Error in get_apis endpoint: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "<string>", line 105, in get_api
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 97, in get
    raise e
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:22:35,307" , "level": "ERROR" , "message": "Error at get document DB: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 94, in get
    data = self.db.search(self.Api.id == id)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 570, in search
    docs = [doc for doc in self.all() if cond(doc)]
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 401, in all
    return list(itervalues(self._read()))
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 374, in _read
    return self._storage.read()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 85, in read
    raw_data = self._storage.read() or {}
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/storages.py", line 108, in read
    return json.load(self._handle)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/splunk/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:22:35,308" , "level": "ERROR" , "message": "Error making API request: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "<string>", line 115, in request
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 97, in get
    raise e
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:27:28,873" , "level": "ERROR" , "message": "Error in API module constructor: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "<string>", line 33, in __init__
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 25, in __init__
    self.origin = TinyDB(os.path.dirname(os.path.abspath(__file__))+'/apilist.json')
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 160, in __init__
    self._table = self.table(default_table)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 179, in table
    table = table_class(self._cls_storage_proxy(self._storage, name), name, **options)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 276, in __init__
    data = self._read()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 374, in _read
    return self._storage.read()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 85, in read
    raw_data = self._storage.read() or {}
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/storages.py", line 108, in read
    return json.load(self._handle)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/splunk/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:27:28,878" , "level": "ERROR" , "message": "Error in manager module constructor: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)" }
Traceback (most recent call last):
  File "<string>", line 51, in __init__
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/db.py", line 25, in __init__
    self.origin = TinyDB(os.path.dirname(os.path.abspath(__file__))+'/apilist.json')
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 160, in __init__
    self._table = self.table(default_table)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 179, in table
    table = table_class(self._cls_storage_proxy(self._storage, name), name, **options)
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 276, in __init__
    data = self._read()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 374, in _read
    return self._storage.read()
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 85, in read
    raw_data = self._storage.read() or {}
  File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/storages.py", line 108, in read
    return json.load(self._handle)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/opt/splunk/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/splunk/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 13 - line 1 column 309 (char 12 - 308)
{ "date": "2019-07-18 01:28:25,530" , "level": "ERROR" , "message": "Error in get_apis endpoint: 'manager' object has no attribute 'db'" }
Traceback (most recent call last):
  File "<string>", line 105, in get_api
AttributeError: 'manager' object has no attribute 'db'
{ "date": "2019-07-18 01:28:26,485" , "level": "ERROR" , "message": "Error making API request: 'api' object has no attribute 'db'" }
Traceback (most recent call last):
  File "<string>", line 115, in request
AttributeError: 'api' object has no attribute 'db'
{ "date": "2019-07-18 01:28:26,671" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" }
Traceback (most recent call last):
  File "<string>", line 115, in get_apis
AttributeError: 'manager' object has no attribute 'db'
{ "date": "2019-07-18 01:28:39,062" , "level": "ERROR" , "message": "Error in get_apis endpoint: 'manager' object has no attribute 'db'" }
Traceback (most recent call last):
  File "<string>", line 105, in get_api
AttributeError: 'manager' object has no attribute 'db'
{ "date": "2019-07-18 01:28:39,238" , "level": "ERROR" , "message": "Error making API request: 'api' object has no attribute 'db'" }
Traceback (most recent call last):
  File "<string>", line 115, in request
AttributeError: 'api' object has no attribute 'db'
{ "date": "2019-07-18 01:28:39,490" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" }
Traceback (most recent call last):
  File "<string>", line 115, in get_apis
AttributeError: 'manager' object has no attribute 'db'
{ "date": "2019-07-18 01:29:33,087" , "level": "ERROR" , "message": "Cannot connect to API : 'manager' object has no attribute 'session'" }
Traceback (most recent call last):
  File "<string>", line 68, in check_connection
AttributeError: 'manager' object has no attribute 'session'
{ "date": "2019-07-18 01:29:55,227" , "level": "ERROR" , "message": "Cannot connect to API : 'manager' object has no attribute 'session'" }
Traceback (most recent call last):
  File "<string>", line 68, in check_connection
AttributeError: 'manager' object has no attribute 'session'
{ "date": "2019-07-18 01:30:44,294" , "level": "ERROR" , "message": "Error in get_apis endpoint: 'manager' object has no attribute 'db'" }
Traceback (most recent call last):
  File "<string>", line 105, in get_api
AttributeError: 'manager' object has no attribute 'db'
{ "date": "2019-07-18 01:30:44,464" , "level": "ERROR" , "message": "Error making API request: 'api' object has no attribute 'db'" }
Traceback (most recent call last):
  File "<string>", line 115, in request
AttributeError: 'api' object has no attribute 'db'
{ "date": "2019-07-18 01:30:44,718" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" }
Traceback (most recent call last):
  File "<string>", line 115, in get_apis
AttributeError: 'manager' object has no attribute 'db'
```
Excerpt from `/opt/splunk/var/log/splunkd.log`
```
07-18-2019 14:25:56.681 +0000 WARN  HttpListener - Returning a 405 error from URL "/en-US/custom/SplunkAppForWazuh//api/request?endpoint=%2Fcluster%2Fstatus&id=67e4cf35-ec79-4aad-ba7c-9c909f85a228&method=GET" but was not given the list of valid methods, so cannot send Allow: header
```

**Comment by pablotr9** [comment]
Hello @tqnguyen9,

Is that a fresh installation (did you follow our cluster installation guide? https://documentation.wazuh.com/3.x/installing-splunk/splunk-distributed.html#splunk-distributed) or were you using a previous version of Wazuh App and upgraded it to 3.9.3-7.3.0 ? in that case what version were you using?

Could you give us more information about your cluster environment and could you please check that you are using Wazuh 3.9.3 and Splunk 7.3.0?
![image](https://user-images.githubusercontent.com/35685689/61524250-6448b600-aa16-11e9-85c3-712cfaef4938.png)
I'm asking that because the screenshot you sent shows a previous version of Wazuh App 3.9.3, check that icons are slightly different from 3.8.x to 3.9.x.
![image](https://user-images.githubusercontent.com/35685689/61524488-d5886900-aa16-11e9-95df-6117e181f1f7.png)
![image](https://user-images.githubusercontent.com/35685689/61524540-eafd9300-aa16-11e9-85a9-d5e9c2ae5cb7.png)

Apart from that, lets try to remove Wazuh App from the cluster and reinstall it again,
- In your deployer machine, remove the Wazuh App:
`rm -rf /opt/splunk/etc/shcluster/apps/SplunkAppForWazuh/`
- Now apply this changes to the cluster:
`/opt/splunk/bin/splunk apply shcluster-bundle -target https://SEARCH_HEAD_NODE_IP:8089 -auth admin:changeme -force true`
- Check in your search head node that Wazuh App has been uninstalled.

Now that Wazuh app has been removed, let's reinstall it:
- Download the v3.9.3-7.3.0 package:
`wget https://packages.wazuh.com/3.x/splunkapp/v3.9.3_7.3.0.tar.gz`
- Untar the app on the deployment server:
`tar -zxf v3.9.3_7.3.0.tar.gz -C /opt/splunk/etc/shcluster/apps/`
- Now deploy the app:
`/opt/splunk/bin/splunk apply shcluster-bundle -target https://SEARCH_HEAD_NODE_IP:8089 -auth admin:changeme`
- Wait a few minutes and access to the Wazuh App in your Search Head node:

Check that I am receiving a similar error:
![image](https://user-images.githubusercontent.com/35685689/61525698-34e77880-aa19-11e9-8fc7-a84154c39193.png)
In the Wazuh App, Press F12 to open browser Dev Tools, it should look like this:
![image](https://user-images.githubusercontent.com/35685689/61525989-d4a50680-aa19-11e9-960a-107bc4737069.png)
Now access to Application, Click on Clear Storage and then Clear Site Data:
![image](https://user-images.githubusercontent.com/35685689/61526078-06b66880-aa1a-11e9-8efa-b451216c56bc.png)
Sometimes there are problems with cached data, once you clear site data, access again to the search node and check if Wazuh App is successfully working.


I hope it helps, if that doesn't solve your issue or you have any other question I'll be happy to help.

Best regards,
Pablo Torres

**Comment by tqnguyen9** [comment]
This is a fresh install of v3.9.3. Regarding the icons, I cleared my browser cache and they then matched the new ones in your screenshot. 

![About Wazuh](https://i.imgur.com/qFQsUTh.png)

I followed your directions to remove the app, reinstall, and clear cache, but still ran into the same problem. I did add a step to remove inputs.conf from the deploy bundle. indexes.conf was not present as the instructions mentioned. I originally did this as well.

The "error loading data" message has become a bit more detailed. When I try to refresh the connection to the "Disabled" API or edit it with the same credentials and save, I get `SyntaxError: JSON.parse: unexpected character at line 1 column 2 of the JSON data`. When I try to delete it, I get `Cannot remove API: this.scope.apiList.indexOf is not a function`.

![API Config Error](https://i.imgur.com/94S9iXy.png)


I've gone through the logs some more and these are the only anomalies I found
```
X.X.X.X - <user> [19/Jul/2019:13:53:46.785 +0000] "POST /servicesNS/nobody/SplunkAppForWazuh/storage/collections/data/credentials/?output_mode=json HTTP/1.1" 503 90 - - - 0ms
X.X.X.X - - [19/Jul/2019:13:54:01.026 +0000] "GET /static/app/SplunkAppForWazuh/js/libs/angular.min.js.map HTTP/1.1" 303 455 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" - - 0ms
2019-07-19 13:54:01,121 INFO	[5d31cb791d7f879443cad0] error:311 - Masking the original 404 message: 'The path '/en-US/static/app/SplunkAppForWazuh/js/libs/angular.min.js.map' was not found.' with 'Page not found!' for security reasons
X.X.X.X - - [19/Jul/2019:13:54:01.116 +0000] "GET /en-US/static/app/SplunkAppForWazuh/js/libs/angular.min.js.map HTTP/1.1" 404 57131 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" - 5d31cb791d7f879443cad0 5ms
X.X.X.X - - [19/Jul/2019:13:54:01.116 +0000] "GET /en-US/static/app/SplunkAppForWazuh/js/libs/angular.min.js.map HTTP/1.1" 404 18766 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" - - 9ms
```

On the Wazuh manager api log, I can see that when I re-enter the API credentials, Splunk is reaching the API and getting successful responses.

```
WazuhAPI 2019-07-19 13:23:32 <wazuh-api-user>: [X.X.X.X] GET /agents/000?select=name - 200 - error: '0'.
WazuhAPI 2019-07-19 13:23:32 <wazuh-api-user>: [X.X.X.X] GET /cluster/status - 200 - error: '0'.
WazuhAPI 2019-07-19 13:23:32 <wazuh-api-user>: [X.X.X.X] GET /cluster/node - 200 - error: '0'.
WazuhAPI 2019-07-19 13:23:32 <wazuh-api-user>: [X.X.X.X] GET /version - 200 - error: '0'.
WazuhAPI 2019-07-19 13:23:33 <wazuh-api-user>: [X.X.X.X] GET /manager/status - 200 - error: '0'.
```

**Comment by pablotr9** [comment]
Hi @tqnguyen9 ,

Sorry for the late reply, after some tries we finally reproduced it and got that same error. The problem is due to the KV Store is still initializing as the app has just been installed. This causes that unexpected behaviour and those error messages (indeed these error messages are a bit confusing and we are currently working on more meaningful messages). All we have to do (do not forget to clean browser cache) is to wait some seconds/minutes and refreshing the page until the KV Store is initialized and then it will just work as expected.
We have opened this issue (https://github.com/wazuh/wazuh-splunk/issues/791) to investigate further about this error and change those error messages.

Please let us know if it works now, if you still need help we'll be happy to help

Best Regards,
Pablo Torres

**Comment by mcbradfordwcb** [comment]
I am also having an issue with the Splunk app and the API.  I can curl to the api from the splunk server, but using the app, when I enter the API information and attempt to save, I get the following:

 Error: There was an error connecting to the api. Please check your api configuration.

Note, our Wazuh instance is not using https at the moment, could this be the issue?  I see where in the API form, the example is https.  I have also just upgraded to the most recent Splunk Wazuh version.

**Comment by mcbradfordwcb** [comment]
{ "date": "2019-07-25 08:47:25,819" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" } Traceback (most recent call last):   File "<string>", line 194, in get_apis AttributeError: 'manager' object has no attribute 'db'
--
  | { "date": "2019-07-25 08:46:18,367" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" } Traceback (most recent call last):   File "<string>", line 194, in get_apis AttributeError: 'manager' object has no attribute 'db'
  | { "date": "2019-07-25 08:46:12,168" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" } Traceback (most recent call last):   File "<string>", line 194, in get_apis AttributeError: 'manager' object has no attribute 'db'
  | { "date": "2019-07-25 08:46:06,142" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" } Traceback (most recent call last):   File "<string>", line 194, in get_apis AttributeError: 'manager' object has no attribute 'db'
  | { "date": "2019-07-25 08:39:31,830" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" } Traceback (most recent call last):   File "<string>", line 194, in get_apis AttributeError: 'manager' object has no attribute 'db'
  | { "date": "2019-07-25 08:37:14,770" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" } Traceback (most recent call last):   File "<string>", line 194, in get_apis AttributeError: 'manager' object has no attribute 'db'
  | { "date": "2019-07-25 08:36:32,520" , "level": "ERROR" , "message": "Error in manager module constructor: Extra data: line 1 column 14 - line 1 column 306 (char 13 - 305)" } Traceback (most recent call last):   File "<string>", line 75, in __init__   File "<string>", line 35, in __init__   File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 160, in __init__Show all 23 lines
  | { "date": "2019-07-25 08:36:32,514" , "level": "ERROR" , "message": "Error in API module constructor: Extra data: line 1 column 14 - line 1 column 306 (char 13 - 305)" } Traceback (most recent call last):   File "<string>", line 39, in __init__   File "<string>", line 35, in __init__   File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 160, in __init__Show all 23 lines
  | { "date": "2019-07-25 08:35:23,521" , "level": "ERROR" , "message": "Error in manager module constructor: Extra data: line 1 column 14 - line 1 column 306 (char 13 - 305)" } Traceback (most recent call last):   File "<string>", line 75, in __init__   File "<string>", line 35, in __init__   File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 160, in __init__Show all 23 lines
  | { "date": "2019-07-25 08:35:23,515" , "level": "ERROR" , "message": "Error in API module constructor: Extra data: line 1 column 14 - line 1 column 306 (char 13 - 305)" } Traceback (most recent call last):   File "<string>", line 39, in __init__   File "<string>", line 35, in __init__   File "/opt/splunk/etc/apps/SplunkAppForWazuh/bin/tinydb/database.py", line 160, in __init__Show all 23 lines
  | { "date": "2019-07-25 08:11:18,355" , "level": "ERROR" , "message": "Cannot connect to API : 'manager' object has no attribute 'session'" } Traceback (most recent call last):   File "<string>", line 68, in check_connection AttributeError: 'manager' object has no attribute 'session'
  | { "date": "2019-07-25 08:10:19,310" , "level": "ERROR" , "message": "Cannot connect to API : 'manager' object has no attribute 'session'" } Traceback (most recent call last):   File "<string>", line 68, in check_connection AttributeError: 'manager' object has no attribute 'session'
  | { "date": "2019-07-25 08:10:03,518" , "level": "ERROR" , "message": "Cannot connect to API : 'manager' object has no attribute 'session'" } Traceback (most recent call last):   File "<string>", line 68, in check_connection AttributeError: 'manager' object has no attribute 'session'
  | { "date": "2019-07-25 08:07:30,129" , "level": "ERROR" , "message": "Cannot connect to API : 'manager' object has no attribute 'session'" } Traceback (most recent call last):   File "<string>", line 68, in check_connection AttributeError: 'manager' object has no attribute 'session'
  | { "date": "2019-07-25 08:06:07,675" , "level": "ERROR" , "message": "{"error": "'manager' object has no attribute 'db'"}" } Traceback (most recent call last):   File "<string>", line 115, in get_apis AttributeError: 'manager' object has no attribute 'db'

**Comment by pablotr9** [comment]
Hi @mcbradfordwcb ,

Sorry for the late reply, could you please tell me from what version of Splunk and Wazuh you upgraded to?
And could you also tell me if you are using a single host architecture or are you using a Splunk cluster?

> Note, our Wazuh instance is not using https at the moment, could this be the issue? I see where in the API form, the example is https.

- No, that shouldn't be the cause of the problem. If your API is configured with https you have to connect to it via https, otherwise you'll have to use http. 

As mentioned in my previous comment, is common to have problems with the cache of the browser when upgrading, could you try deleting cache (Open Browser DevTools -> Application -> Clear Storage -> Clear site data) then refresh and try adding a new API.
When installing the app in a sh cluster, it can takes a few seconds to initialize the KvStore where data is stored, so it's recommend to wait a few seconds.

If you still have problems, please let me know.

Kind regards,
Pablo Torres
