### ISSUE TITLE
Bugs found on Wazuh v3.10.0 - Splunk 7.3

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-splunk#821]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 3.10   | 7.3     |  37 |

# Wazuh v3.10.0 - Splunk 7.3

 - [x] Unable to select an API when accessing the APP for first time: Fixed here: https://github.com/wazuh/wazuh-splunk/commit/031ce10451d0bfaab2fc081a85ab3d74dfe11eaa
![](https://user-images.githubusercontent.com/35685689/63765812-21f27e80-c8ca-11e9-826a-a268d4b56282.png)
- [x] Errors when enabling/disabling extensions. Fixed here: https://github.com/wazuh/wazuh-splunk/issues/820
- [x]  Can't see the file content of a rule when clicking on its name from the rule details tab. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/5bb70fdb6b3d1d579481220d65ebcc88452cc34a
![](https://user-images.githubusercontent.com/35685689/63765969-7990ea00-c8ca-11e9-916a-f3d88e1e0d71.png)
- [x] Export group configuration: Granular options are missing.
- [x] HIPAA & NIST 800 53 columns are missing in Management -> Rules table. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/dd39928509ad08a0641772d56ac68a51e15e233e
- [x] (Only on Firefox). Check the "eye" button for enabling/disabling extensions. It can't be seen/clicked correctly. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/2856c53e57e4b44f6ddaeaeece394e7b77c6102d
- [x] Reports tables first row is misplaced. f124c90662b73467804c7c70ed9a279327aa9af8
- [x] Inventory Report "Processes table" is being printed wrong. dd3b8568c5acef0bfdb4317f550612e69913d93a
- [x] Inventory data. Last scan time is wrong: a025f453259171d472868949be059698e792cdc9
![image](https://user-images.githubusercontent.com/35685689/63930271-47f75a80-ca53-11e9-8624-85d4651d3252.png)

- [x] Styling error at CDB Lists. Fixed here: fb2b06188bd737e2d2317085dc001312967b9e8c
![](https://user-images.githubusercontent.com/35685689/63834592-f331e200-c975-11e9-89bb-43f621cfb433.png) 
- [x] Management -> Configuration -> Policy monitoring: SCA tab is missing. f20a2e04954e6bf571a724c23c1a4998c6a98291 https://github.com/wazuh/wazuh-splunk/commit/23625b0cecdc35549364376cf004184dc78abf81
- [x] When doing a PUT/POST/DELETE request with ADMIN MODE disabled we get this message: "The requested URL was not found on this server"
Even if the request URL exists, we obtain that result, it can cause confusion to users.  Fixed here: https://github.com/wazuh/wazuh-splunk/commit/3ff6148ecf7d213171d5acdff2f665e572d25092
- [x] (Only on Firefox) Agent status indicator is misplaced. https://github.com/wazuh/wazuh-splunk/commit/3b88bc14638abebd30f7a87521e305e9f291cd1e
- [x] When admin mode is disabled and we try to edit a rules/decoders file we get this error. Fixed here: 25bf5a398618e96773ddf7ca70cd8d75a539bcc6
![](https://user-images.githubusercontent.com/35685689/63852145-ede58f00-c997-11e9-8e50-1d71d1a18772.png)
- [x] (ADMIN MODE DISABLED)  Close file button doesn't work. Fixed here: 25bf5a398618e96773ddf7ca70cd8d75a539bcc6
![image](https://user-images.githubusercontent.com/35685689/63998877-72ecb780-cb02-11e9-8308-76da13a0dde6.png)

- [x]  Overview -> Policy Monitoring. Alerts summary visualization is empty even when there are existing alerts of Policy Monitoring. Fixed here https://github.com/wazuh/wazuh-splunk/commit/aa90d47dbc70818dda87f80e2ad739da1ad2fa08
- [x] Overview -> VirusTotal dashboard is not working correctly. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/0c63df1edac2c6b512e283e163e870e15823d9c9
- [x] Agents -> OpenSCAP dashboard is not working properly. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/1cd26b0625880c64e2932f5c6ebc35393b18a797
- [x] Agents -> Osquery. Error toast is being thrown even if there were no errors. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/0c63df1edac2c6b512e283e163e870e15823d9c9
- [x] Agents -> VirusTotal: Alerts summary is empty. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/0c63df1edac2c6b512e283e163e870e15823d9c9
- [x] Agents -> Docker Listener: Null Labels on visualizations Fixed here: https://github.com/wazuh/wazuh-splunk/commit/1cd26b0625880c64e2932f5c6ebc35393b18a797
- [x] Agents -> HIPAA & NIST 800 53: Alerts summary table should be in descending order. Fixed here: https://github.com/wazuh/wazuh-splunk/commit/7a1a526186ddbc10fbbdf4b8125f5c7ad88a6c5a
- [x]  'Dashboard' button should has the same style as any other button in the app:
![image](https://user-images.githubusercontent.com/35685689/64099325-4a1a2b80-cd69-11e9-9122-aeb2b2db8c77.png)

-  Microsoft Edge Browser styling errors:
   - [x] The Dashboard button in discover does not float on the right
   - [x] Agents List -> The filter list has no background
    ![](https://user-images.githubusercontent.com/3064506/63848536-52045500-c990-11e9-8102-b094278878c5.png)
    - [x] All reports generated in Edge do not show the graphics.
     ![](https://user-images.githubusercontent.com/3064506/63844649-d6eb7080-c988-11e9-8432-58655e99b808.png)

**Comment by jsanchez91** [comment]
I fix the problem to generate reports in Microsoft Edge, but the background of the images is black.

![image](https://user-images.githubusercontent.com/3064506/64024403-90d60e80-cb3a-11e9-85e3-1cdb6eb4d9f2.png)

**Comment by jsanchez91** [comment]
Reports are generated well in Microsoft Edge, Chrome and Firefox.
