### ISSUE TITLE
Hide index pattern selector in case that only one exists

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-splunk#836]
Hi team,

It would be nice that when there's an only index pattern hide it, otherwise show a selector in order to change between them.

![image](https://user-images.githubusercontent.com/7983984/64842122-676cb680-d601-11e9-9225-695261ea8490.png)

Regards,

**Comment by snaow** [comment]
Not applicable for Splunk.
Index patterns are changed in App settings.
