### ISSUE TITLE
Implement auto-selection of first added API

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-splunk#84]
Hello Splunkers!

Currently, when we add the first API entry on the Wazuh app for Splunk, it's not selected as the favourite API, so you have to click on the start icon to mark it as selected.

The Kibana app has this functionality, and I think the Splunk app deserves the same feature. If I add the first API, auto-select it as the favourite one. If I add an API when there's another one inserted, don't make it the favourite one.

This probably would change the way APIs are managed on the Splunk app.

Regards,
Juanjo

**Comment by manuasir** [comment]
Done [here #47a1fe7](https://github.com/wazuh/wazuh-splunk/commit/47a1fe71f8b32c27b2ac51c3134b93447bd8d6f4). It'd be great if you could test this new behavior. Thanks!
