### ISSUE TITLE
Make the Wazuh logo button redirect to Overview/General

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-splunk#85]
Hello Splunkers!

We should research about the possibility of redirecting the user to Overview/General whenever he press the Wazuh logo button on the top right corner of the Splunk app.

Regards,
Juanjo

**Comment by manuasir** [comment]
Done [here #2e59564](https://github.com/wazuh/wazuh-splunk/commit/2e595642295b117de67d76e4cd2cc863fa9c5ea7)
