### ISSUE TITLE
No message about "No group configuration available" when clicking on an agent

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-splunk#86]
Hello Splunkers!

When I'm on Agents/Configuration, I get a message about "No group configuration available", but if I click on an agent, I'm not getting that same message. See attached screenshots below.

![agentconf](https://user-images.githubusercontent.com/10928321/40714895-20fc8358-6404-11e8-8337-1a9190c7221f.PNG)
![agentconf2](https://user-images.githubusercontent.com/10928321/40714896-211afb26-6404-11e8-8c0d-34719c44556a.PNG)

Regards,
Juanjo

**Comment by manuasir** [comment]
Done [here #27ab703](https://github.com/wazuh/wazuh-splunk/commit/27ab7033f61476241a4b72bf2af770321a8c853c)
