### ISSUE TITLE
"Null" tag when deleting the selected index on LocalStorage

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-splunk#87]
Hello Splunkers!

If I remove the selected index from LocalStorage, and I reload the page, I get this on the top left section of the app in Overview tabs:

![null](https://user-images.githubusercontent.com/10928321/40715065-b65b6202-6404-11e8-9321-42f67b24c647.PNG)

Although I get the `null` tag on the app, visualizations are still working properly.

Regards,
Juanjo

**Comment by manuasir** [comment]
Done [here #3024da4](https://github.com/wazuh/wazuh-splunk/commit/3024da4f68b28ab8463c3a5628980138305adb7f).
