### ISSUE TITLE
Kv Store won't initialize in Splunk 8.0

### ISSUE THREAD

**Issue by HoorayJorge** [wazuh/wazuh-splunk#876]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 3.10  | 8.0.0     | 444 |
Splunk Build: 1357bef0a7f6

**Description**
Wazuh app reports "Kv Store is being initialized please wait some seconds and try again later." perpetually, despite Splunk Kv Store properly ready.

![Screen Shot 2019-11-02 at 00 16 03](https://user-images.githubusercontent.com/17163659/68065955-365a5980-fd07-11e9-832f-2687a54eca94.png)

**Steps to reproduce**

1. Go to Wazuh app in Splunk 8.0

**Additional context**

![Screen Shot 2019-11-02 at 00 21 31](https://user-images.githubusercontent.com/17163659/68065939-d6fc4980-fd06-11e9-81db-6da8a32f0bd2.png)

**Comment by HoorayJorge** [comment]
This issue appeared to resolve itself after a few days, but now there's an error when attempting to add API configurations.   The error appears before attempting to add API configurations.

![Screen Shot 2019-11-03 at 11 22 55](https://user-images.githubusercontent.com/17163659/68088954-24290a00-fe32-11e9-98d2-59ef4343f7ea.png)

**Comment by pablotr9** [comment]
Hi @HoorayJorge ,

Thanks for reporting it, indeed our Wazuh app is not compatible with the latest version of Splunk 8.0.
We are working on it and will be ready in the next hours, I'll keep you updated.

Let us know if you need anything else

Best regards,
Pablo Torres

**Comment by pablotr9** [comment]
Hi @HoorayJorge ,

The Wazuh App for Splunk 8.0.0 have been released: https://github.com/wazuh/wazuh-splunk/releases/tag/v3.10.2-8.0.0

You can download that app in this link: https://packages.wazuh.com/3.x/splunkapp/wazuhapp-splunk-3.10.2_8.0.0.tar.gz 

Let me know if you need anything else.

Best regards,
Pablo Torres

**Comment by HoorayJorge** [comment]
Thanks Pablo!  That seems to have resolved the issues.  Thanks to the whole team for quickly getting a new version out.
