### ISSUE TITLE
Documentation link in README.md is broken

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-splunk#877]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| n/a   | n/a     | n/a |

**Description**
Documentation link to Wazuh Splunk in the README.md is broken:

**Steps to reproduce**

1. Go to README.md
2. Click on Documentation link (which redirects to https://documentation.wazuh.com/current/installing-splunk/index.html)
3. You can see the redirect is broken

Best regards,

Jose

**Comment by AlexRuiz7** [comment]
The link does work now
