### ISSUE TITLE
Adapt Wazuh app for new log rotation module

### ISSUE THREAD

**Issue by pablotr9** [wazuh/wazuh-splunk#881]
Hi team,

We should adapt the Wazuh app in order to include the new [log rotation](https://github.com/wazuh/wazuh/issues/3072) module options.
As for now,  the logging options are shown here:

![log](https://user-images.githubusercontent.com/10405193/67278898-3918ab80-f4ca-11e9-8cef-d69d38512cbd.png)

This module should be called "Log settings" and it should include three tabs: `alerts`, `archives` and`internal`. Every tab will have the same options:

- Plain format.
- JSON format.
- Compress rotation.
- Saved rotations.
- Schedule.
- Maximum log size.
- Minimum log size.
- Maximum log age.

This options are provided by:

- Endpoint: GET /manager/config/analysis/logging (for `alerts` and `archives` logs, only available in manager).
- Endpoint: GET /manager/config/monitor/logging (for internal `ossec.log`, for manager).
- Endpoint: GET /agents/:agent_id/config/agent/logging (for internal `ossec.log` for agents).

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
