### ISSUE TITLE
wazuhapp ver 3.11.2 and 3.11.1 in splunk ver 8.0.0 get blank page 

### ISSUE THREAD

**Issue by trungkienkma1994** [wazuh/wazuh-splunk#909]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 3.x   | 8.0.0     | 444 |

**Description**
Short description of your issue.

**Steps to reproduce**

**Screenshots**

**Additional context**
Add any other context about the problem here. Here you can paste log entries too or any other useful information that may help with the issue.

**Comment by pablotr9** [comment]
Hi @trungkienkma1994 ,

Could you please give us some more information about your environment?
1. Is it a fresh installation or did you upgrade from a previous version?
1. What steps did you follow to install/upgrade the Wazuh UI for Splunk 8.0?
3. What package are you installing? note that we have two different packages for Wazuh 3.11.2, 3.11.3 and 3.11.4, one for version 7.3.x and another one for Splunk 8.0.x, please check that you are downloading and installing the correct package. (You can find here the compatibility list of Wazuh UI for Splunk https://github.com/wazuh/wazuh-splunk#installation)
4. Could you please try removing the cookies of your browser or access it using an incognito window? In some cases, cookies can cause some compatibility problems.
5. The error you are getting when accessing the Wazuh UI for Splunk is a blank screen without any information? or is there any error being shown? Could you please share with us some logs, you can find these logs here: `cat /opt/splunk/var/log/splunk/SplunkAppForWazuh.log`

Best Regards,
Pablo Torres

**Comment by trungkienkma1994** [comment]
I have install wazuh app ver 3.11.0 and 3.11.1 for splunk 8.0.0. And this is log of wazuh app 
![image](https://user-images.githubusercontent.com/45995675/75507246-22073e80-5a13-11ea-878f-01bd59dcaad1.png)

**Comment by wkleinhenz** [comment]
Im not sure if theres been traffic on this but im also seeing this in a Single Node Docker based deployment running 8.0.4.1, if needed i can try and figure out where to grab logs from
