### ISSUE TITLE
The link to the documentation is broke

### ISSUE THREAD

**Issue by jlruizmlg** [wazuh/wazuh-splunk#91]
Hello, I'm tying to go to the documentation through the link in the README.md but seems like it is broke:

https://documentation.wazuh.com/current/not_found.html

**Comment by manuasir** [comment]
Hi @jlruizmlg ,

This issue was fixed in [#77546e9](https://github.com/wazuh/wazuh-splunk/commit/77546e962df46820afeadd1966bdb4c69ea42e6d). Thank you for your report and apologies for the inconvenience.

Best regards,
Manu
