### ISSUE TITLE
How to set default index?

### ISSUE THREAD

**Issue by 2ZZ** [wazuh/wazuh-splunk#921]
Hi,

Is it possible to set the default Splunk index to something other than 'wazuh'?

I've found I need to set the index every time I use the app and sometimes the setting gets lost mid-session. This can be frustrating as it's not immediately obvious why events are missing until I notice the index has been reverted.

**Comment by pablotr9** [comment]
Hi @2ZZ ,

Sorry for the late reply, unfortunately, that is not currently possible using the app, but I can show you how to edit the source code to override the behaviour of the Wazuh app.

The service that manages the current index selected is located in the **apiIndexStorageService.js** file: 
`/opt/splunk/etc/apps/SplunkAppForWazuh/appserver/static/js/services/apiIndexStorageService/apiIndexStorageService.js`
So all you have do is editing that file. In that file you can see this method: 
![image](https://user-images.githubusercontent.com/35685689/82661806-00da7680-9c2d-11ea-8774-7e24c1a05d6f.png)
You can see that when the App doesn't found a valid index, it automatically sets the ''wazuh'' index as the default one. if you want to use a different index, just change that value to the index name you want to use and then restart Splunk:
```
pkill splunkd; /opt/splunk/bin/splunk restart
```

Please let me know if that helps, thanks for reporting that, we will add it to our roadmap for future versions

Best Regards,
Pablo Torres

**Comment by 2ZZ** [comment]
Thanks @pablotr9 that's really helpful
