### ISSUE TITLE
Splunk 7.3.5 - wazuh 3.13 - KV store not being initializing

### ISSUE THREAD

**Issue by b4b857f6ee** [wazuh/wazuh-splunk#929]
| Wazuh | Splunk | Rev |
| ----- | ------- | --- |
| 3.13   | 7.3.5     | |

**Description**
kvstore is not initialize

**Steps to reproduce**

Install Splunk wazuh app for 7.3.5 version 3.13

You need to modify the splunk/etc/apps/SplunkAppForWazuh/default/package.conf from 8.0.2 to 7.3.5 :)

I test : https://community.splunk.com/t5/All-Apps-and-Add-ons/Why-is-my-KV-store-not-being-initializing-after-new-app-install/td-p/483925

I hope it's work :)

**Comment by b4b857f6ee** [comment]
I find this because this is not working yet :/
https://community.splunk.com/t5/All-Apps-and-Add-ons/Why-is-my-KV-store-not-being-initializing-after-new-app-install/td-p/483925

**Comment by pablotr9** [comment]
Hi @b4b857f6ee,

Please check the compatibility matrix to find the correct package https://github.com/wazuh/wazuh-splunk#installation.

The Wazuh app package is different for Splunk v7.x.y and 8.x.y versions: 
Wazuh 3.13.0 - Splunk 7.3.5: https://packages.wazuh.com/3.x/splunkapp/wazuhapp-splunk-3.13.0_7.3.5.tar.gz
Wazuh 3.13.0 - Splunk 8.0.x: https://packages.wazuh.com/3.x/splunkapp/wazuhapp-splunk-3.13.0_8.0.2.tar.gz

Let me know if it helps!

Best Regards,
Pablo Torres

**Comment by b4b857f6ee** [comment]
Yes, i have use carefully the right version so this is not helping :/...

**Comment by pablotr9** [comment]
Hi @b4b857f6ee, 

Are you using Splunk on a search head cluster or is it a single host installation? Also try removing browser cache data or accessing the App on a private window (it sometimes causes cache issues)

Please could you please share with me the revision of the package you installed? ( you can find this info in the About subtab of the settings section)

You can check the KvStore with this command: (don't forget to replace `SPLUNK-SERVER-IP` with its IP)
```
curl -k -u admin:changeme -s https://SPLUNK-SERVER-IP:8089/services/server/info | grep kvStoreStatus
```

Best Regards,
Pablo Torres

**Comment by b4b857f6ee** [comment]
Hi @pablotr9 
Single host
Already try the private nav

[app]
version = 3.13.0
revision = 63
[wazuh]
version = 3.13.0
[splunk]
version = 7.3.5

Curl result : <s:key name="kvStoreStatus">ready</s:key>

**Comment by pablotr9** [comment]
Hi @b4b857f6ee ,

You are right, it seems that there was an error with the 3.13.0-7.3.5 package, as the revision should be `64` instead of 63.
Please try reinstalling the package with this package link: https://packages.wazuh.com/3.x/splunkapp/wazuhapp-splunk-3.13.0_7.3.5.tar.gz
You can reinstall it following these 2 steps:
- Remove current App:
```
$SPLUNK_HOME/bin/splunk remove app SplunkAppForWazuh
```
- Download the package (https://packages.wazuh.com/3.x/splunkapp/wazuhapp-splunk-3.13.0_7.3.5.tar.gz) and install that new package:
```
 $SPLUNK_HOME/bin/splunk install app <package file>
```

Please let me know if it helps!

Best Regards,
Pablo Torres

**Comment by b4b857f6ee** [comment]
Not the same size as my previous package.
Revision 64 and it's work!

Thank you!! @pablotr9
