### ISSUE TITLE
data.vulnerability.reference in search command is not valid on Vulnerabilities - Alert summary panel for Wazuh 3.13 security events

### ISSUE THREAD

**Issue by pmcclammer** [wazuh/wazuh-splunk#930]
The "overview" controller overviewVulnerabilitiesCtrl.js uses data.vulnerability.reference in the search command for the "Alert summary" panel.  

Wazuh 3.13 Vulnerability Detector now generates alerts with data.vulnerability.references element rather than data.vulnerability.reference. 

This causes the Alert summary panel to display no results since search command is not valid for latest vulnerability detector security events.

To work around the issue, I have updated the search command to use a single "cve" element in the search command.  This doesn't provide the same results but does give some additional information.

Wazuh App for Splunk 3.13 version should align with the data elements generated by Wazuh Manager 3.13 version. Though, I suspect it may not have been modified for backward compatibility?

**Comment by pablotr9** [comment]
Hi @pmcclammer !

The latest App should be fully compatible with the latest version of Wazuh so this is a bug, thanks for reporting it!

I have just opened a PR to fix that bug: https://github.com/wazuh/wazuh-splunk/pull/931

Thanks again for reporting the error, do not hesitate to open a new issue if you find any other bug or have any question!

Best Regards,
Pablo Torres
