### ISSUE TITLE
Support for Wazuh v3.8

### ISSUE THREAD

**Issue by vncloudsco** [wazuh/wazuh-splunk#937]
Can you upgrade it to use the newer wazuh version

**Comment by pablotr9** [comment]
Hi @vncloudsco, 

Could you please give us some more information of what you are trying to achieve?

The newer Wazuh version is 3.13.1 and it's compatible with Splunk 8.x and 7.3.x , you can find the download link and all available packages here: https://github.com/wazuh/wazuh-splunk#installation.

To upgrade it you just have to follow these steps: 

Remove the app using splunk plugin tool
`$SPLUNK_HOME/bin/splunk remove app SplunkAppForWazuh
`
Install the app
` $SPLUNK_HOME/bin/splunk install app <package file>`

If you want to use the specific Wazuh version 3.8, you can find the package here: https://packages.wazuh.com/3.x/splunkapp/v3.8.2_7.2.6.tar.gz. This older version is only available in Splunk 7.x.

Best Regards,
Pablo Torres

**Comment by vncloudsco** [comment]
Dear: @pablotr9 
Thank you so much for reply

I need to support the following versions:

Splunk version: 8.0.5
Wazuh version 3.8.0
--

**Comment by pablotr9** [comment]
Hi @vncloudsco,

Unfortunately, Wazuh 3.8 is not supported with Splunk 8.0.  You can see the full list of Wazuh versions compatible with Splunk 8.0 here https://github.com/wazuh/wazuh-splunk#installation
I recommend you to upgrade Wazuh for the latest version, you can find more information about the upgrade here: https://documentation.wazuh.com/3.13/upgrade-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor

Best Regards,
Pablo Torres
