### ISSUE TITLE
Support Wazuh plugin for Python3

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-splunk#947]
Hello team,

Python 3 is the default for all python calls; including CLI commands, custom search commands, and scripts in Splunk Enterprise and its apps in the 8.1 version.  

A customer upgrading from 8.0.x that manually configured an app to use Python2 should not see an immediate break-in functionality for that app, as Python 2 has not been removed from Splunk Enterprise 8.1. However, we should consider starting to work on this migration before the deprecation.

Reference: https://docs.splunk.com/Documentation/Splunk/8.1.1/ReleaseNotes/MeetSplunk

Regards,

Miguel Casares

**Comment by asteriscos** [comment]
Hi team,

I'm currently removing python 2 backwards compatibility and verifying the rest of the code according to this article:
https://python-future.org/compatible_idioms.html

So far I have modified these files and I'm adding this comment `# REMOVE PYTHON2 COMPAT` while I'm testing it, so I can easily find the changes and reverse them.

> SplunkAppForWazuh/bin/PIL/EpsImagePlugin.py
> SplunkAppForWazuh/bin/PIL/Image.py
> SplunkAppForWazuh/bin/PIL/ImageFont.py
> SplunkAppForWazuh/bin/PIL/ImageMath.py 
> SplunkAppForWazuh/bin/PIL/ImageQt.py
> SplunkAppForWazuh/bin/PIL/ImageShow.py
> SplunkAppForWazuh/bin/PIL/ImageTk.py
> SplunkAppForWazuh/bin/PIL/PdfParser.py
> SplunkAppForWazuh/bin/PIL/PngImagePlugin.py
> SplunkAppForWazuh/bin/PIL/TarIO.py
> SplunkAppForWazuh/bin/PIL/TiffImagePlugin.py
> SplunkAppForWazuh/bin/PIL/WmfImagePlugin.py
> SplunkAppForWazuh/bin/PIL/_binary.py
> SplunkAppForWazuh/bin/PIL/_tkinter_finder.py
> SplunkAppForWazuh/bin/PIL/_util.py
> SplunkAppForWazuh/bin/fpdf/fpdf.py
> SplunkAppForWazuh/bin/fpdf/php.py
> SplunkAppForWazuh/bin/fpdf/py3k.py
> SplunkAppForWazuh/bin/fpdf/template.py
> SplunkAppForWazuh/bin/requestsbak/compat.py
> SplunkAppForWazuh/bin/requestsbak/utils.py
> SplunkAppForWazuh/bin/tailer/__init__.py

The branch I'm currently working on is:
https://github.com/wazuh/wazuh-splunk/tree/enhance/delete-deprecated-python2-code-947
