### ISSUE TITLE
Adapt for break changes to consume Wazuh API (compatible with RBAC)

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#950]
EPIC
|---|
#949 

Hi team we need to adapt the Splunk App for break changes to consume Wazuh API (compatible with RBAC)
We need to analyze and achieve these themes: 
- [x] Survey the number of API usages
- [x] Authentication: Update to get JWT
- [x] Store token in server-side (json db)
- [x] Authorization request: Added JWT to all API request
- [x] Migrate all API endpoints deprecated or changed 
  - [x] Explore server-side API request 
  - [x] Explore front-side API request
  
Main Branch
|---|
https://github.com/wazuh/wazuh-splunk/tree/feature/change-api-3.1.3-to-4.0

**Comment by eze9252** [comment]
- Migrate Api versión from 3.13.3 to 4.1.1
- Add method to get token_id
- Impact analysis throughout the app

**Comment by frankeros** [comment]
### **Update:**
- Table of API compatibility 3.x with 4.x https://github.com/wazuh/wazuh-documentation/issues/2413
-

**Comment by Machi3mfl** [comment]
- Wazuh api 3.13 endpoints trace in wazuh-splunk
File : [Drive Doc .xls](https://docs.google.com/spreadsheets/d/1FtTfvZI8G4GCu54Rr9uXxLD7Rj857aTvRjaf9VFXpnI/edit#gid=0)

**Comment by eze9252** [comment]
- Migrate services manager from 3.13.3 to 4.1.1

**Comment by Machi3mfl** [comment]
- Migrating view `agents` y `overview-agents`
<img width="1440" alt="Screen Shot 2021-02-22 at 17 19 26" src="https://user-images.githubusercontent.com/6089438/108769621-01939680-7538-11eb-9d44-b12704cba209.png">
<img width="1440" alt="Screen Shot 2021-02-22 at 17 19 44" src="https://user-images.githubusercontent.com/6089438/108769648-0a846800-7538-11eb-899e-c836aafbc04f.png">

**Comment by eze9252** [comment]
Migrating and fixing view `configuration`

![Captura de pantalla de 2021-02-23 17-44-29](https://user-images.githubusercontent.com/36004787/108905838-f2c3e700-75fe-11eb-9632-340c67b0e405.png)
![Captura de pantalla de 2021-02-23 17-44-42](https://user-images.githubusercontent.com/36004787/108905845-f6576e00-75fe-11eb-986e-7a9bda256266.png)

**Comment by eze9252** [comment]
Migrating view `ruleset` (rules,decoders and list) 

![Captura de pantalla de 2021-02-24 17-56-47](https://user-images.githubusercontent.com/36004787/109065103-fa03f700-76c9-11eb-9837-fdd1f9675d7d.png)

**Comment by Machi3mfl** [comment]
Migrating Agents Features:

**SECURITY INFORMATION MANAGEMENT**
- Security events
- Integrity monitoring
- Configuration
- Inventory data

**AUDITING AND POLICY MONITORING**
- Policy monitoring
- Security configuration assessments

**REGULATORY COMPLIANCE**
- PCI DSS
- GDPR

**Comment by Machi3mfl** [comment]
Migrating `overview` 

<img width="1440" alt="Screen Shot 2021-02-25 at 16 28 09" src="https://user-images.githubusercontent.com/6089438/109209136-f33cb900-7789-11eb-8bcd-40f6fa7df3b4.png">

**Comment by eze9252** [comment]
Migrating `Group` Views:

![Captura de pantalla de 2021-02-25 18-12-06](https://user-images.githubusercontent.com/36004787/109217988-51bb6480-7795-11eb-8c2d-0852c35c9963.png)

**Comment by Machi3mfl** [comment]
Migrating `dev-tools` **autocomplete** feature

- Updating pi restful endpoints

**Comment by eze9252** [comment]
Miagrate status views. 

![Captura de pantalla de 2021-03-03 18-06-35](https://user-images.githubusercontent.com/36004787/109872634-727b3280-7c4b-11eb-8b71-cbe3d861cff8.png)

**Comment by eze9252** [comment]
Pending:

https://docs.google.com/spreadsheets/d/1FtTfvZI8G4GCu54Rr9uXxLD7Rj857aTvRjaf9VFXpnI/edit#gid=1485201075
