### ISSUE TITLE
wazuh app does not work when behind a reverse proxy

### ISSUE THREAD

**Issue by xkilian** [wazuh/wazuh-splunk#96]
Using splunk 6.6.7
Installed the app
Restarted Splunk

When accessed directly the app works. When accessing via a reverse proxy, I get 404s in the reverse proxy that it cannot find the js files.
Looking in the controller js code, I noticed that there are a bunch of static paths. This breaks compatibility with running behind a proxy (nginx in my case).

Expected behaviour : be able to access the app when run behind a reverse proxy

Thank you,

**Comment by xkilian** [comment]
Using the app 3.2.3 wazuh app.

**Comment by manuasir** [comment]
Hi @xkilian , 
this issue will be researched and I will inform you about any resolution.
Thank you for your report and apologies for the inconvenience. 

Best regards,
Manu

**Comment by manuasir** [comment]
Hi @xkilian ,

Please, could you tell me more details abour your reverse proxy configuration? I will try to reproduce your environment in order to approach a solution to your issue. 

Regards

**Comment by xkilian** [comment]
[wazuh_notes.txt](https://github.com/wazuh/wazuh-splunk/files/2098792/wazuh_notes.txt)

You will find attached logs and nginx configuration.

We use NGINX as a reverse proxy for authentication, and each app has its own endpoint https://x.x.x.x/splunk or https://x.x.x.x/multisite

**Comment by xkilian** [comment]
Let me know if you need anything else?

**Comment by manuasir** [comment]
Hi @xkilian ,

Unfortunately, after several tries, we concluded that Splunk needs static routes in order to work with resources and it's not possible to run the app behind a reverse proxy. Sorry about the inconveniences.
Please, don't hesitate to open a new issue whenever you need it.

Kind regards

**Comment by xkilian** [comment]
Strange. All examples that I have seen that use require, will all use relative paths. I 

One of the Splunk answers provides a useful description of how the require paths work : https://answers.splunk.com/answers/482069/how-to-include-js-file-inside-another-js-file.html

It is these requires which break the reverse proxy which have a static path, these are defined in SplunkAppForWazuh/appserver/static/js/viewControllers/audit.js

  "/static/app/SplunkAppForWazuh/js/services/credentialService.js",
  "/static/app/SplunkAppForWazuh/js/directives/toaster.js",
  "/static/app/SplunkAppForWazuh/js/services/indexService.js",
"/static/app/SplunkAppForWazuh/js/directives/selectedCredentialsDirective.js"

My understanding is that the path should look something like this "../app/SplunkAppForWazuh/x/x/x.js"

**Comment by manuasir** [comment]
Hi again @xkilian ,

Currently we're changing our Splunk app for Wazuh architecture and technology. We're migrating it from RequireJS + BackboneJS to AngularJS, which also allows us to use the app behind a reverse proxy. Stay tuned to our progress in [this branch](https://github.com/wazuh/wazuh-splunk/tree/3.4-rebrand), I'll also let you know when this version's released.
Thanks for your participation.

Best regards

**Comment by xkilian** [comment]
Thank you for the feedback.
I look forward to testing it!

Cheers
