### ISSUE TITLE
Reporting table only shows 15 reports

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh-splunk#998]
Currently the Reporting table list only 15 reports. I should list all of them may be paginated.
Also, the table should be sorted by the most recent report to the oldest.

![image](https://user-images.githubusercontent.com/26828184/111626999-5dff7400-87cd-11eb-9427-e9f581a2f98a.png)

**Comment by gabiwassan** [comment]
[PR](https://github.com/wazuh/wazuh-splunk/pull/1001) on revision.
